### ISSUE TITLE
MapChart - setting homeGeoPoint causes an error

### ISSUE THREAD

**Issue by camden-kid** [amcharts/amcharts4#640] opened 2018-12-06 12:38 UTC
This simple statement:

`chart.homeGeoPoint = {
    latitude: 0,
    longitude: 0
  };
`

causes the following error:

![image](https://user-images.githubusercontent.com/890197/49584703-01f1e800-f954-11e8-9557-72083d317788.png)

It also happens if I set homeGeoPoint in the config data.

Using:
    "@amcharts/amcharts4": "^4.0.1",
    "@amcharts/amcharts4-geodata": "^4.0.20",

It works fine in CodePen so I am unable to create a working version that shows the error.

**Comment by martynasma** [comment] 2018-12-06 14:30
What about when you use the latest version? (4.0.5)

**Comment by camden-kid** [comment] 2018-12-06 18:52
Same problem with 4.0.5.

**Comment by martynasma** [comment] 2018-12-07 04:38
OK, since I'm not able to reproduce this error, could you please share your map code so that we can test your setup?

This is what I have tried so far:
https://codepen.io/team/amcharts/pen/bbed21c6a8b83ad4e3329dd27dab0d98?editors=0010

**Comment by martynasma** [comment] 2018-12-17 19:40
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2018-12-17 19:40 UTC
Labels: question

**Comment by camden-kid** [comment] 2018-12-19 15:36
@martynasma Sorry for the late reply. In the end I didn't need to change homeGeoPoint and I couldn't replicate the issue. Will keep an eye out for it in future. Thanks.
