### ISSUE TITLE
Wrong tool tips on date axis with milliseconds

### ISSUE THREAD

**Issue by lticadler** [amcharts/amcharts4#2716] opened 2020-07-20 09:00 UTC
**Bug description**
- XYChart with date axis
- timeUnit: 'millisecond'

Tooltips showing every second time wrong info if the the date has no minutes/seconds/milliseconds. Like one millisecond is missing.
![image](https://user-images.githubusercontent.com/58069494/87917645-98b1e080-ca75-11ea-9639-a6dcb53ecca7.png)

Happens on hours as well.
![image](https://user-images.githubusercontent.com/58069494/87919114-9fd9ee00-ca77-11ea-81ac-43b4a42fe402.png)

And on minutes
![image](https://user-images.githubusercontent.com/58069494/87920281-44106480-ca79-11ea-91c1-7c68ac598664.png)

If changing timeunit to seconds it works as expected.

**Pen**
https://codepen.io/chrisadler/pen/zYryrxO?editors=1010

**Environment (if applicable)**
 - amCharts version: 4.9.30 (and earlier)
 - Browser and its version: all Browsers

**Comment by martynasma** [comment] 2020-07-21 09:05
Fixed in [4.9.31](https://github.com/amcharts/amcharts4/releases/tag/4.9.31).

## [4.9.31] - 2020-07-21

### Changed
- Global adapters are being deprecated due to performance reasons. They will still work on some properties, but may be turned off at some future version. If you are using `am4core.globalAdapter`, please consider refactoring your code in some other way.
- If `groupInterval` is manually set, `DateAxis` now prepares all intervals. Normally, the chart does not prepare data sets for time intervals longer than the span of dates in the data. This causes problem in case user sets these intervals manually using `groupInterval`. Note, the groupInterval must be set initially, before data parsing in order data to be grouped into all groupIntervals.

### Fixed
- "Year of week" (`YYYY`) was not being calculated correctly by `DateFormatter`.
- Regression plugin was not working correctly in an all-`ValueAxis` scenarios.
- `ColumnSeries` were not working with `dropFromPreviousState`.
- If data was changed on a chart which was zoomed and there were less data items in the new data than there was before, a JS error was triggered.
- Sometimes a chart with `XYChartScrollbar` with series in it could produce a JS error if series has its `fillOpacity > 0`.
- Series in an `XYChartScrollbar` was not being shown if `options.onlyShowOnViewport = true`.
- `zoomToRectangle()` call was resulting in an error if called after the `MapChart` was rotated.
- `CurvedColumnSeries` columns were not being filled with proper color (black was being used instead).
- A chart with multiple series starting/ending not at the same position could result in wrong zoom on `ValueAxis`.
- `DateAxis` with millisecond `baseInterval` sometimes could show one millisecond less than actual data point in its tooltip.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-07-21 09:05 UTC
Labels: bug, in next release
