### ISSUE TITLE
Strange behavior when using external JSON data with DateAxis

### ISSUE THREAD

**Issue by simialbi** [amcharts/amcharts4#1108] opened 2019-03-22 08:18 UTC
I try using external data with date and value Axis. After loading the external data the chart is rendered correctly but instantly updates his view and then the chart line itself is some kind of pressed at the left edge. This looks like this:

![chart1](https://user-images.githubusercontent.com/3023342/54809281-1b107180-4c83-11e9-9f94-5538ef75cb16.PNG)
![chart2](https://user-images.githubusercontent.com/3023342/54809286-1e0b6200-4c83-11e9-879d-e51d68dfd6ec.PNG)

The code I use:
```js
var chartChart23 = am4core.create('chart_23', am4charts.XYChart);
chartChart23.dataSource.url = 'https://fmv.tonic.ag/data/index';
chartChart23.dataSource.parser = new am4core.JSONParser();
chartChart23.dataSource.parser.options.dateFormat = 'yyyy-MM-dd HH:mm';
chartChart23.dataSource.parser.options.emptyAs = 0;

var dateAxisSaCo1 = new am4charts.DateAxis();
dateAxisSaCo1.baseInterval = {
    "timeUnit": "minute",
    "count": 1
};
chartChart23.xAxes.push(dateAxisSaCo1);
var valueAxisSaCo2 = new am4charts.ValueAxis();
chartChart23.yAxes.push(valueAxisSaCo2);
var lineSeriesSaCo3 = new am4charts.LineSeries();
lineSeriesSaCo3.name = "Usage";
lineSeriesSaCo3.dataFields.dateX = 'timestamp';
lineSeriesSaCo3.dataFields.valueY = 'usage';
chartChart23.series.push(lineSeriesSaCo3);
```

**Comment by martynasma** [comment] 2019-03-22 10:28
That was a bug in 4.2.5 fixed in 4.2.6. Sorry about that.

Make sure you update and clear your browser cache.

**Comment by simialbi** [comment] 2019-03-22 10:41
Hey @martynasma 
Thanks for your reply. That's exactly what I tested before i opened this issue. I updated to 4.2.6 and that did not change anything.

**Comment by martynasma** [comment] 2019-03-22 10:50
Hm, I can't seem to be able to reproduce this.

Would you be able to post your whole chart and code as a codepen so that we can test?

**Comment by simialbi** [comment] 2019-03-22 11:00
https://codepen.io/simialbi/pen/JzwKRG

**Comment by martynasma** [comment] 2019-03-22 11:24
Your data seems to be coming in reverse order. Chart can't handle that.

You can either change the order at your data backend, or reverse it when loaded:

```
chartChart23.dataSource.adapter.add("parsedData", function(data) {
  return data.reverse();
});
```

**Comment by simialbi** [comment] 2019-03-22 12:53
Sorry. My bad. I feel so silly right now. Sorry for bothering you.
Thank you ver much.  Can be closed.

**Comment by martynasma** [comment] 2019-03-22 15:06
No worries ;)

**Closed by martynasma** 2019-03-22 15:06 UTC
Labels: question
