### ISSUE TITLE
Tooltip out of chart when zoom in oX 

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#620] opened 2018-12-01 21:51 UTC
When we zoom in and move up on the oY axis the tooltip will show out of chart.

https://codepen.io/aniov/pen/JexppB?editors=0010

![image](https://user-images.githubusercontent.com/21243081/49333245-d40f4b00-f5c3-11e8-8a07-22357c979965.png)

**Comment by martynasma** [comment] 2018-12-02 13:33
Duplicate of #574. Closing this one. Please subscribe to the linked issue for updates.

**Closed by martynasma** 2018-12-02 13:33 UTC
