### ISSUE TITLE
AmCharts display tooltip for series based on ValueX and ValueY axes very STRANGE

### ISSUE THREAD

**Issue by russeljo** [amcharts/amcharts4#3055] opened 2020-11-03 00:59 UTC
**Bug description**

Very strange behavior of cursor, when two value axes, in my situation - three.

Let me show video example 
https://monosnap.com/file/A5nAWqy93QDCHV2E07bZsclACXr0Et

`
// Add cursor

    Chart.main.chart.cursor = new am4charts.XYCursor();

Chart.main.chart.cursor.maxTooltipDistance = 200;
    Chart.main.chart.cursor.snapToSeries = [
        Chart.main.line.h,
    ];
`

Maybe better make tooltip follow only X or only Y - cursor value, and better set it when set snapToSeries 

And another one:
https://monosnap.com/file/m8xhNcxRTww7L0GNCNwZRcORyZdcXq
A have multi axies, and dashed line always look to left axes, even if tooltip on line that depend on right side axis.

**Comment by martynasma** [comment] 2020-11-03 05:32
Seems to be duplicate of #3049. Closing.

**Closed by martynasma** 2020-11-03 05:32 UTC
Labels: duplicate, question
