### ISSUE TITLE
Q: Gantt chart is not updating live data

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#1210] opened 2019-04-16 12:21 UTC
I am trying to add live mode to a gantt chart. I have a running task and it updates every 5 seconds.
I followed the examples in the docs [Manipulating existing data points](https://www.amcharts.com/docs/v4/concepts/data/#Manipulating_existing_data_points), but with no success on the gantt chart.

I have created a minimal setup showing the behavior. I hope there is a solution to update the columns. [Code Pen](https://codepen.io/anon/pen/KYZVVX?editors=0010)

Thanks!

**Comment by martynasma** [comment] 2019-04-17 17:06
Looks like a bug in `invalidateRawData()`. It seems it does not take in the new `dateX` data field.

We'll need to fix this.

Will keep you posted. Thanks!

**Comment by martynasma** [comment] 2019-05-02 12:36
Fixed in [4.4.2](https://github.com/amcharts/amcharts4/releases/tag/4.4.2).

## [4.4.2] - 2019-05-02

### Added
- New property for `Label`: `baseLineRatio` (default `-0.27`) controls how "base line" for a label is calculated, and affects positioning of text. The default might not work for all fonts, so this setting can be used to adjust it for precise positioning.
- New event for `Sprite`: `"dragged"`. It kicks in right after `"drag"` and can be used to manipulate or correct element's position, which might not be possible using `"drag"` which has built-in position-altering handlers.

### Fixed
- Export to SVG was not working on Firefox.
- Some touch issues wit iOS Safari fixed.
- `ValueAxis` could display non-rounded numbers (caused by floating point problem) sometimes.
- `maxPanOut` of `MapChart` was being ignored.
- Chart scrollbar was not being zoomed out when data of a chart changed.
- `RadarChart` with multiple `RadarColumnSeries` with Y as base axis was displaying columns of a 2nd+ series from wrong position.
- `chart.dispose()` with a lot of data was very slow. Now it's super fast.
- Zoom with mouse wheel was buggy when zooming already zoomed-in `XYChart`.
- Gant chart was not updating columns when `chart.invalidateRawData()` was called.
- Issue with some `propertyFields` set on a `LineSeries` with no data fixed.
- Reseting `relativeRotation` of `AxisLabelCircular` to `undefined` didn't work.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-05-02 12:36 UTC
Labels: bug, in next release
