### ISSUE TITLE
Zoom with mouse wheel is funky

### ISSUE THREAD

**Issue by dorsharon** [amcharts/amcharts4#1226] opened 2019-04-23 07:19 UTC
Example:
https://codepen.io/team/amcharts/pen/66c62670e319b59a00f474cea7d2478a?editors=0010.

In this codepen, if you zoom in enough with the mouse wheel, at some point it will zoom to a location that's not where the cursor is placed, but somewhere near to the left or right.

Also, once fully max zoomed in, if you take the cursor only a little bit to either side and try scrolling up again, it will jump quite a lot to that side, more than it should be for a proper UX. 

I found no way so far to overcome this issue. Please help.
Having minZoomCount didn't help me.

**Comment by martynasma** [comment] 2019-04-25 04:22
Indeed. Thanks for bringing this to our attention!

Will keep you posted.

**Comment by dorsharon** [comment] 2019-04-28 08:09
Awesome, let me know when it's fixed, looking forward to it :)

**Comment by martynasma** [comment] 2019-05-02 12:36
Fixed in [4.4.2](https://github.com/amcharts/amcharts4/releases/tag/4.4.2).

## [4.4.2] - 2019-05-02

### Added
- New property for `Label`: `baseLineRatio` (default `-0.27`) controls how "base line" for a label is calculated, and affects positioning of text. The default might not work for all fonts, so this setting can be used to adjust it for precise positioning.
- New event for `Sprite`: `"dragged"`. It kicks in right after `"drag"` and can be used to manipulate or correct element's position, which might not be possible using `"drag"` which has built-in position-altering handlers.

### Fixed
- Export to SVG was not working on Firefox.
- Some touch issues wit iOS Safari fixed.
- `ValueAxis` could display non-rounded numbers (caused by floating point problem) sometimes.
- `maxPanOut` of `MapChart` was being ignored.
- Chart scrollbar was not being zoomed out when data of a chart changed.
- `RadarChart` with multiple `RadarColumnSeries` with Y as base axis was displaying columns of a 2nd+ series from wrong position.
- `chart.dispose()` with a lot of data was very slow. Now it's super fast.
- Zoom with mouse wheel was buggy when zooming already zoomed-in `XYChart`.
- Gant chart was not updating columns when `chart.invalidateRawData()` was called.
- Issue with some `propertyFields` set on a `LineSeries` with no data fixed.
- Reseting `relativeRotation` of `AxisLabelCircular` to `undefined` didn't work.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-05-02 12:36 UTC
Labels: bug, in next release
