### ISSUE TITLE
Extra empty day shown in chart and some other questions

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#627] opened 2018-12-03 16:27 UTC
Long time user, but now trying to convert to amcharts 4 and having some troubles.  I have created a fiddle [here](https://jsfiddle.net/0s2zok6u/1/) with an example.

The example takes a timestamp of the current day and creates random values for it and the previous 6 days before it.  For some reason or another I am getting a 'future' day with no value shown on the chart.  This is not from the data being sent to it, but how the chart is being produced.  Why is this and what can I do to fix that?

I am also running into times where the first day/value is cutoff and pushed to the left of the x/y axes every now and then which I would like to fix.

Lastly, I can't seem to find a way to center the tooltip when you hover over the chart instead of its default 'side' position next to the data point.

If anyone can help that would be great.  I have read the docs, but I can't seem to find what I am looking for to correct these.

**Comment by zeroin** [comment] 2018-12-03 18:36
Try to reset Hours to 0, like:

`var date = new Date();
date.setHours(0,0,0,0);
var curr_date = date.getTime();`

To change pointer orientation set: `series.tooltip.pointerOrientation = "vertical";`

**Comment by morrow95** [comment] 2018-12-03 19:36
@zeroin Thank you.  That helped out a bit, but not sure who that is going to work with actual data (timestamps) as I wouldn't want to change them.

Any idea why the tooltips (text specifically) is fuzzy and pixelated?  It is nowhere near as clear as the cursor with the date. Never had that issue with the last version, but maybe this is something which needs done in the settings?

**Comment by zeroin** [comment] 2018-12-04 06:15
Most likely we will soon add some feature which will allow not to reset date to minimum like I suggested. 

Speaking about fuzzy and pixelated - not sure I see it, but I think this might be caused by the filter you apply on the whole tooltip in these lines: 
```
var dropShadow = new am4core.DropShadowFilter();
dropShadow.dy = 0;
dropShadow.dx = 0;
dropShadow.opacity = 0;
series.tooltip.filters.push(dropShadow);```

From what I see you most likely want to remove the filter at all? then you can simply set:

```series.tooltip.filters.clear();```

And your question gave me idea which I'll try, maybe it would be better to apply filter on the tooltip background only instead of the whole tooltip.

**Comment by morrow95** [comment] 2018-12-04 17:38
@zeroin Clearing did the trick.  The reason I was setting the shadow properties to 0 was to remove it and I had seen in the docs or a demo somewhere that way as an example.

**Comment by martynasma** [comment] 2018-12-17 19:38
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2018-12-17 19:38 UTC
Labels: question
