### ISSUE TITLE
chart.dispose() throws error

### ISSUE THREAD

**Issue by sersh88** [amcharts/amcharts4#17] opened 2018-05-09 10:41 UTC
<img width="1031" alt="2018-05-09 13 40 08" src="https://user-images.githubusercontent.com/6498585/39810679-8d2d6bea-538e-11e8-9e2a-87cfc31fead3.png">

It worked before at least in beta4

**Comment by martynasma** [comment] 2018-05-10 18:08
Fixed in [4.0.0-beta.21](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.21)

**Closed by martynasma** 2018-05-10 18:08 UTC
Labels: bug, in next release

**Comment by sersh88** [comment] 2018-05-14 06:25
Now after dispose() it is impossible to create chart again. I get error:
`Uncaught Error: EventDispatcher is disposed
    at SpriteEventDispatcher.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js.EventDispatcher.isEnabled (:3003/static/js/13.chunk.js:41014)
    at Container.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js.Sprite.setPropertyValue (:3003/static/js/13.chunk.js:7643)
    at Container.set [as maxWidth] (:3003/static/js/13.chunk.js:2562)
    at SVGContainer.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/rendering/SVGContainer.js.SVGContainer.measure (:3003/static/js/13.chunk.js:33087)
    at :3003/static/js/13.chunk.js:12566
    at Object.each [as b] (:3003/static/js/13.chunk.js:37540)
    at System.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/System.js.System.measure (:3003/static/js/13.chunk.js:12564)
    at System.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/System.js.System.update (:3003/static/js/13.chunk.js:12371)
    at :3003/static/js/13.chunk.js:12512`

I just use chart as React component. When component will be unmount - I call dispose() to free memory, but when I want it again to be mounted - I get this error. 
Maybe should be some other option to free memory after chart dismount?

**Comment by sersh88** [comment] 2018-05-14 08:59
@Pauan , already upgraded. Same error.

**Comment by Pauan** [comment] 2018-05-31 07:21
@sersh88 Okay, I think I fixed it, please try version `4.0.0-beta.26`

**Comment by arm1n** [comment] 2018-06-11 21:07
I'm experiencing the same issue when using `ngOnDestroy` - I'm using `4.0.0-beta.28`. But this seems to be the same problem as somehow related to #65.

**Comment by Pauan** [comment] 2018-06-18 13:36
@arm1n @jimmykane We haven't been able to reproduce this issue, could you please share the code you are using to create your charts, so that way we can fix this ASAP?

**Comment by jimmykane** [comment] 2018-06-18 13:44
@Pauan  I tried with latest build and could not reproduce this as well.
