### ISSUE TITLE
How can I update a pie chart data that uses SliceGrouper plugin?

### ISSUE THREAD

**Issue by gagigante** [amcharts/amcharts4#3325] opened 2021-02-23 16:59 UTC
How can I update a pie chart data that uses SliceGrouper plugin?

 - amCharts version: 4.10.3 
 - Browser: Chrome
 - Angular 8
 
I have a component for this chart and this component should receive the data and the grouper threshold to render the chart. But when data input or threshold changes the SliceGrouper stops reponding and does not update the 'Other' slice even if threshold is 0.

The function `buildChart` is called on every input changes

```
buildChart() {
  am4core.useTheme(am4themes_animated);
    am4core.useTheme(this.getChartCustomTheme);

    if (this.chart) {
      this.chart.dispose();
    }

    this.chart = am4core.create("chartDiv", am4charts.PieChart);
    this.chart.legend = new am4charts.Legend();
    this.chart.legend.valueLabels.template.text = '';

    this.mainSeries = this.chart.series.push(new am4charts.PieSeries());
    this.mainSeries.dataFields.value = 'valor';
    this.mainSeries.dataFields.category = 'estrutura';
    this.mainSeries.labels.template.disabled = true;
    this.mainSeries.ticks.template.disabled = true;
    this.mainSeries.slices.template.states.getKey('active').properties.shiftRadius = 0;

    this.chart.data = this.chartData;

    const grouper = this.mainSeries.plugins.push(new am4plugins_sliceGrouper.SliceGrouper());
    grouper.clickBehavior = 'break';
    grouper.threshold = this.getGrouperThreshold(this.slicesConfig);
    grouper.syncLegend = true;
}

```

**Comment by martynasma** [comment] 2021-02-23 18:23
Duplicate of https://github.com/amcharts/amcharts4/issues/3297

**Closed by martynasma** 2021-02-23 18:23 UTC
Labels: duplicate, question
