### ISSUE TITLE
Exception when exporting graph to PDF

### ISSUE THREAD

**Issue by arielvol** [amcharts/amcharts4#2060] opened 2020-01-21 20:03 UTC
Hi,
I tried to activate the ExportMenu option in our amCharts.
Whenever I try to export a chart to PDF, I get this error:

Uncaught (in promise) ChunkLoadError: Loading chunk vendors~pdfmake failed.
(error: http://localhost:8010/vendors~pdfmake.js)
at Function.requireEnsure [as e] (http://localhost:9000/app.js:812:26)
at Function.fn.e (http://localhost:9000/app.js:156:40)
at eval (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:94:45)
at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:120:23)
at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:101:53)
at eval (webpack-internal:///./node_modules/tslib/tslib.es6.js:94:71)
at new Promise ()
at Module.__awaiter (webpack-internal:///./node_modules/tslib/tslib.es6.js:90:12)
at _pdfmake (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:89:59)
at Export.get [as pdfmake] (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:3626:34)
requireEnsure @ app.js:812
fn.e @ app.js:156
eval @ Export.js?7e9c:69
step @ tslib.es6.js?9ab4:99
eval @ tslib.es6.js?9ab4:80
eval @ tslib.es6.js?9ab4:73
__awaiter @ tslib.es6.js?9ab4:69
_pdfmake @ Export.js?7e9c:64
get @ Export.js?7e9c:3601
eval @ Export.js?7e9c:1792
step @ tslib.es6.js?9ab4:99
eval @ tslib.es6.js?9ab4:80
fulfilled @ tslib.es6.js?9ab4:70
Promise.then (async)
step @ tslib.es6.js?9ab4:72
eval @ tslib.es6.js?9ab4:73
__awaiter @ tslib.es6.js?9ab4:69
Export.export @ Export.js?7e9c:605
eval @ Export.js?7e9c:506
eval @ EventDispatcher.js?daec:380
eval @ EventDispatcher.js?daec:265
each @ Array.js?6e0f:74
EventDispatcher._eachListener @ EventDispatcher.js?daec:238
EventDispatcher.dispatchImmediately @ EventDispatcher.js?daec:263
eval @ ExportMenu.js?4c1f:299
eval @ EventDispatcher.js?daec:380
eval @ EventDispatcher.js?daec:265
each @ Array.js?6e0f:74
EventDispatcher._eachListener @ EventDispatcher.js?daec:238
EventDispatcher.dispatchImmediately @ EventDispatcher.js?daec:263
Interaction.handleHit @ Interaction.js?e243:1047
Interaction.handleUp @ Interaction.js?e243:1318
eval @ Interaction.js?e243:1263
eval @ Iterator.js?0357:57
eval @ List.js?f2c0:40
each @ Iterator.js?0357:56
Interaction.handleGlobalUp @ Interaction.js?e243:1259
Interaction.handleGlobalPointerUp @ Interaction.js?e243:767
eval @ Interaction.js?e243:288

anyone encountered this ?

**Comment by martynasma** [comment] 2020-01-22 15:41
We'll need some way to reproduce it. Would you be able to post your chart online somewhere?

**Comment by Ices-Eyes** [comment] 2020-01-30 10:20
Not sure if this is the same problem, but while exporting graph as image (pdf, jpg, png - bun not svg), in internet explorer, you alwas get an error of "Unhandled promise rejection TypeError: Cannot call a class as a function". Works good with other browsers and used to work also on IE. The problem is present also on the graph in the docs ie here https://www.amcharts.com/docs/v4/concepts/exporting/

**Comment by martynasma** [comment] 2020-02-07 20:23
Fixed in [4.8.9](https://github.com/amcharts/amcharts4/releases/tag/4.8.9).

## [4.8.9] - 2020-02-07

### Added
- Scrollbar.isBusy getter added, which is true when user interacts with Scrollbar.
- RadarColumnSeries now support two category axes.
- angleToPosition(angle) added to AxisRendererCircular.
- currentPosition getter added to ClockHand.

### Fixed
- Export on IE (and other setups with `simplifiedExport = false`) was broken since upgrading canvg version.
- When DateAxis had grouped set to true, in some cases the value axis was zoomed incorrectly after Data update.
- In some specific cases XYScrollbar with series could produce JS error when adding data to the chart.
- Funnel Series sliceLink could loose it's color after data update.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-02-07 20:23 UTC
Labels: bug, in next release
