### ISSUE TITLE
Only first chart from multiple charts inside owl carousel is loaded

### ISSUE THREAD

**Issue by thisisjaymehta** [amcharts/amcharts4#2616] opened 2020-06-21 11:47 UTC
**Bug description**

So I make an OWL Carousel with different items in it. In each item there is a chart. 
When I create chart for all items, only first is shown, others are not visible.

I think that is because when charts are created only first owl item is active and rendered, and so only first charts gets it height and width properly. While other items are not rendered yet.

Also I have an function which make chart for given id:

```
                function drawChart(id, val1, val2) {
			console.log("Drawing for : " + id);
			am4core.useTheme(am4themes_animated);
			var chart = am4core.create(id, am4charts.PieChart);
			chart.responsive.enabled = true;
			chart.data = [{
				"task": "Completed",
				"litres": val1
			}, {
				"task": "Pending",
				"litres": val2
			}];
			chart.innerRadius = am4core.percent(80);
			chart.radius = am4core.percent(100);
			var pieSeries = chart.series.push(new am4charts.PieSeries());
			pieSeries.dataFields.value = "litres";
			pieSeries.dataFields.category = "task";
			pieSeries.slices.template.stroke = am4core.color("#fff");
			pieSeries.slices.template.strokeWidth = 0.5;
			pieSeries.slices.template.strokeOpacity = 1;
			pieSeries.labels.template.disabled = true;
			pieSeries.colors.list = [
				am4core.color("#008000"),
				am4core.color("#800000")
			];
			pieSeries.hiddenState.properties.opacity = 1;
			pieSeries.hiddenState.properties.endAngle = -90;
			pieSeries.hiddenState.properties.startAngle = -90;
			var label = pieSeries.createChild(am4core.Label);
			label.text = "Order\nCompleted: 11201\nPending: 15021";
			label.horizontalCenter = "middle";
			label.verticalCenter = "middle";
			label.fontSize = 10;
			label.fill = am4core.color("#008000");
		}
```

**Environment (if applicable)**

Provide details about your development environment where you think it might be useful. E.g.:

 - amCharts version: 4
 - Browser and its version: All

**Comment by martynasma** [comment] 2020-06-22 06:02
Can you post a live demo?

**Comment by thisisjaymehta** [comment] 2020-06-22 07:45
Here is the live demo. 
[CodePen Demo](https://codepen.io/thisisjaymehta/pen/KKVWxeQ)
This is exactly what is the issue.
Notice following things,

- First chart will be rendered properly.
- Rest of the chart will not be rendered
- Last chart will become momentarily visible while carousel is sliding back to first chart.

**Comment by martynasma** [comment] 2020-06-22 08:02
Thanks.

Obviously carousel script is doing something weird that fools our resize sensor.

If your carousel has events, try triggering resizing of the chart when the slide slides into view:

```
chart.svgContainer.measure();
```

**Comment by thisisjaymehta** [comment] 2020-06-22 08:12
But the problem is I make chart with a function, so I don't have instance of chart to use inside event of carousel.
I tried this:
```
function getChart(id) {
    return am4core.registry.baseSprites.find(function (chartObj) {
        return chartObj.htmlContainer.id === id;
    });
}
$("#pattern_carousel").on('changed.owl.carousel', function (e) {
    if (e.property.value > 0) {
        var mychart = getChart(patternArr[e.property.value - 2]);     // patternArr contains name of id's which were used as chart
        mychart.svgContainer.measure();
    }
});
```
But nothing happens, same result.

**Comment by martynasma** [comment] 2020-06-22 08:23
What about delaying drawing of charts until carousel is fully initialized?

**Comment by thisisjaymehta** [comment] 2020-06-22 08:38
Nope: [CodePen](https://codepen.io/thisisjaymehta/pen/KKVWxeQ)
The problem I guess is, while chart is being created, only one carousel item is active. Which means only one chart container is rendered on screen, and so only one chart is rendered properly. Others are hidden, and so other charts are not able to render for that container.

**Comment by martynasma** [comment] 2020-06-22 08:46
I understand. However charts have resize sensors in place that should detect when size of the container changes, then redraw themeselves.

If this is not happening it means that carouse is doing something funky with those containers.

I'm not sure what to suggest. Have you tried some other carousel lib?

**Comment by thisisjaymehta** [comment] 2020-06-22 08:52
Is there a way to refresh charts? Link you suggested .measure() for detecting change in containers size. If by some mean I can refresh or redraw chart every time its container is rendered by carousel.

Meanwhile I will look for carousel alternatives.

**Comment by martynasma** [comment] 2020-06-22 08:56
I did try forcing `measure()` on charts in your demo, but that did not seem to work.

At this point it would require us debugging this particular setup, which goes well beyond scope of free support options.

If you could produce some kind of non-carousel repro setup, we'd be able to check if it's not a bug.

**Comment by thisisjaymehta** [comment] 2020-06-22 09:36
I tried with another carousel library [Swiper](https://swiperjs.com/), same problem exist. [Codepen](https://codepen.io/thisisjaymehta/pen/ExPWOyW)
About non-carousel repro setup, I think bug only exist for carousel items because of some items are rendered at a time while some aren't.

**Comment by martynasma** [comment] 2020-06-22 11:25
Gotcha. Thanks.

In that case, I suppose it would make sense to start chart creation for a slice that scrolls into view.

Naturally, you would need to check if chart was already created for a specific slide, so that you don't waste resources on re-creating same chart over and over again.

At this point I'm not sure what else to suggest, unless there's some easy way to repro this :(

**Comment by thisisjaymehta** [comment] 2020-06-24 06:35
So I got this working with including carousels change event inside am4core's ready event.
```
am4core.ready({
    
    //Draw chart1, chart2, chart3 and chart4 here

    $("#pattern_carousel").on('changed.owl.carousel', function (e) {
        chart1.svgContainer.measure();
        chart2.svgContainer.measure();
        chart3.svgContainer.measure();
        chart4.svgContainer.measure();
    });
});
```
Thanks for all your help.

Shall I close the issue?

**Comment by martynasma** [comment] 2020-06-24 06:37
Awesome. Thanks for sharing this!

Yes, please close this if you're done.

**Closed** 2020-06-24 06:40 UTC
Labels: question
