### ISSUE TITLE
Legend - ".strokeWidth, .strokeDasharray" doesn't seem to be applied.

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#279] opened 2018-08-26 11:59 UTC
In your example it doesn't seem to be working all options applied to marker (chart.legend.markers.template.children.getIndex(0)) , like:
'.strokeWidth, .strokeDasharray, .stroke, ... see pen below:

https://codepen.io/team/amcharts/pen/XqPbYd

Also if anyone can help how to inherit custom colors from LineSeries (they are also set for bullets, tooltip) when 'chart.legend.useDefaultMarker = true;' or another way to do it when having custom legend style.
Thank you

**Comment by aniov** [comment] 2018-08-26 14:07
I figure it out with the help part.

**Comment by martynasma** [comment] 2018-08-27 11:56
Thanks for the update!

So, are you all set, or still could use assistance with something?

**Comment by aniov** [comment] 2018-08-27 12:25
On your example: https://codepen.io/team/amcharts/pen/XqPbYd I can't see ".strokeWidth, .strokeDasharray" to be working on legend. That's why I opened a new issue.

`marker.strokeWidth = 2;
marker.stroke = am4core.color("#ccc");`

![image](https://user-images.githubusercontent.com/21243081/44659447-fb76da80-aa0c-11e8-8e7e-6d91759018c3.png)

![image](https://user-images.githubusercontent.com/21243081/44659583-62948f00-aa0d-11e8-9232-8f6206fc2c33.png)

**Comment by martynasma** [comment] 2018-08-27 12:51
Thanks for bringing this to our attention!

An outline (stroke) is normally is invisible (`strokeOpacity = 0`).

So, if you need it to be visible you also need to set `strokeOpacity` to a non-zero value.

I have now updated Legend article and related demo accordingly.

I hope that helps.

**Comment by aniov** [comment] 2018-08-27 18:29
I still have a question regarding this subject. How can I set individually custom "styles" for every legend ?
Let's say I want to make some of them have round shape some of them squares.
Ty.

**Comment by martynasma** [comment] 2018-08-27 18:38
Are the legend items completely custom, or they are built out of the chart's series?

**Comment by aniov** [comment] 2018-08-27 18:44
They are build out of chart's series, 
(like this https://codepen.io/team/amcharts/pen/XqPbYd?editors=0010), but
every of the chart line has a "twin" with same color but represented with "strokeDasharray". So I have to do the same to half of the lengends.

**Comment by martynasma** [comment] 2018-08-28 13:43
OK, so you can use adapters to set a function that would dynamically modify any property.

I put together an example here:
https://codepen.io/team/amcharts/pen/RYRJaG?editors=0010

I'm using multiple corner-related adapters for Legend's marker template.

The `target` is a marker `Rectangle`. It has a `dataItem` which in turn has `dataContext` which refers to the series it is created for. We can then extract custom data set in series' `dummyData` and modify parameters dynamically.

I hope this makes sense, and is what you were looking for.

**Comment by aniov** [comment] 2018-08-28 14:14
Thank you very much. You were very helpful.

**Comment by martynasma** [comment] 2018-08-28 14:16
FYI, just posted it as a tutorial:
https://www.amcharts.com/docs/v4/tutorials/using-adapters-to-modify-legend-item-appearance/

**Comment by martynasma** [comment] 2018-08-29 11:17
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by aniov** [comment] 2018-08-29 17:50
Modifying properties like color fill with adapter works fine, but when legend is toggled it's loses his initial color and set a default one. Is this normal behavior and I have to use adapters to re-apply color back, or it's a bug.
See pen bellow:

https://codepen.io/aniov/pen/zJKXVL?editors=0010

**Comment by martynasma** [comment] 2018-08-30 11:53
Hm, right. It happens because it setts gray fill for the "active" state (which is when item is toggled off), then when you set it back to default state it does not reset back to your original color.

I'll need to figure this one out, as I don't see any straightforward solutions to this right now.

Will get back to you. (re-opening this)

**Comment by zeroin** [comment] 2018-09-07 12:19
Hi Wezm, 

This happens because line series legend, in case  it has fill, creates line (on top of the square and a regular rectangle, not a RoundedRectangle. If it was rounded rectangle it would look weird - you would have a circle (or almost a circle) and a line above it. So I am afraid this is not possible.

**Comment by wezm** [comment] 2018-09-09 23:53
Thanks for following up @zeroin. With that in mind, I suppose another option would be to set `useDefaultMarker = true` and style them as circles like https://www.amcharts.com/docs/v4/concepts/legend/#Customizing_markers If I went down this path would it be possible to make one of them appear as a line?

**Comment by martynasma** [comment] 2018-09-10 09:43
@wezm I suppose you could do something like this:

```
marker.adapter.add("maxHeight", function(height, target) {
  return target.dataItem.name == 2017 ? 2 : height;
});
```

**Comment by wezm** [comment] 2018-09-11 00:11
Great, thanks @martynasma. I'll give that a try.

**Comment by sassomedia** [comment] 2018-12-06 06:45
Sorry to add to pile onto this but it appears like there might be yet another difference when using PieChart, is that possible?

I was looking to add a ring around the legend bullets on rollover. Basically adding a circle behind the bullet and adding a white stroke on the bullet would make it appear like a ring. Like in this screenshot:

<img width="153" alt="screen shot 2018-12-06 at 3 27 29 pm" src="https://user-images.githubusercontent.com/5614099/49566001-8f413680-f96c-11e8-9d9e-4de19e747d46.png">

In my [jsFiddle](https://jsfiddle.net/sassomedia/6ht82ryj/) adding the circle works, but I'm unable to add a `stroke` to the bullet, it just gets ignored. Also, if I tried to set a custom `fill` on the ring, it wouldn't work. Unless, I set `chart.legend.useDefaultMarker = true` and then the properties are accepted. However, by turning that on, I'm losing the series colors on the bullets, they all turn black. Is this supposed to happen? I don't see this happening in the LineChart example. If this is intended behavior, how would I be able to access the colors again? I've tried with a `fill` adapter but I'm not getting any colors there, just black.

For some reason though, in my actual project (screenshot above) I do get the ring to work without having to turn on `useDefaultMarker`. Meaning, the stroke on the bullet works and the colors are maintained. The only difference between my project and the sample jsFiddle is that I'm using a JSON-config for the chart and the legend is housed in a separate container. Shouldn't this be functionally the same to the object-based approach?

**Comment by zeroin** [comment] 2019-01-03 15:38
@sassomedia Here is a fiddle which does what you expect:

https://jsfiddle.net/2dk90fwp/

It might seem complicated, but the thing is that we need to modify children of marker in order to be able to do show/hide animations. That's why I recommend the following approach:
1) create hover state for `itemContainers` template, and set `setStateOnChildren = true` in order states to be applied to children
2) do the same on `markerTemplate`
3) create set opacity on ring to 0, also in `ring.defaultState.opacity`
4) set `opacity` to 1 on hover state of a ring.

This approach is also good as you won't need any events.

**Closed** 2019-01-03 15:39 UTC
Labels: bug, docs, question
