### ISSUE TITLE
Value Axis messed up when using strictMinMax, but only a single data item

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1014] opened 2019-02-27 13:45 UTC
A user might need the setting `strictMinMax = true` (without defining `min` or `max` values). 

This works fine when there are more than 1 data items in the `chart.data`: https://codepen.io/varshamathukumalli/pen/xBGRvY?editors=0010.

This doesn't work when there is only a single data item in `chart.data`: https://codepen.io/team/amcharts/pen/rRVwwJ?editors=0010.

You'll see that there are 2 labels on top of the axis that overlap.

**Comment by martynasma** [comment] 2019-02-27 15:00
Bug confirmed. Thanks!

**Comment by martynasma** [comment] 2019-03-14 18:07
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-03-14 18:07 UTC
Labels: bug
