### ISSUE TITLE
All legends are not visible when scroll is visible

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#283] opened 2018-08-27 05:13 UTC
Hi,

When more number of legends are available, i am providing scroll so that one can see all legends.
But that is not working. Below is the code pen link:
https://codepen.io/varshamathukumalli/pen/rZeMmZ?editors=0110

**Comment by martynasma** [comment] 2018-08-27 11:33
Technically, you would need to set the `legendContainer.height` to some value that would fit all of the legend. Then the `overflow: auto` on the wrapper would work.

E.g.:

```
legendContainer.width = am4core.percent(100);
legendContainer.height = 300;
```

However, that seems to be not working.

I'm chalking it up as a bug. Will let you know when it's fixed. (I'm hoping at some point next week)

**Comment by martynasma** [comment] 2018-09-03 06:08
OK, so it's not a bug after all.

The `Container` which holds the legend will always try to size itself to the parent `<div>` it is placed on.

So, the solution is to wrap your legend into additional div.

The outer div will have fixed height and `overflow: auto` set.

Inner div will be sized to the whole height of the legend by this code:

```
// Use this if needed, e.g. on viewport resize/orientationchange, anything that
// would change the height of the Legend.
function resizeLegendDiv() {
  // resize the external div so it matches the height of the generated legend
  legendDiv.style.height = chart.legend.measuredHeight + "px";
}

// Once the legend has been generated, we can resize the external div accordingly
chart.legend.events.on('inited', resizeLegendDiv);
```

Here's an example:
https://codepen.io/team/amcharts/pen/2c4fede5b6518c0ccf68535a508f28e3/

Hope it helps.

**Comment by martynasma** [comment] 2018-09-03 06:08
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2018-09-03 06:08 UTC
Labels: question

**Comment by Varshamathukumalli** [comment] 2018-10-05 10:47
In the sample you have provided also, it is not working.
Update the pen or provide some otherway to fix that issue

**Comment by martynasma** [comment] 2018-10-05 11:16
@Varshamathukumalli There's currently a bug that prevents `measuredHeight` to be calculated correctly. Once that it fixed, the demo will work once again.

Here's a separate issue you can subscribe to: #440

**Comment by martynasma** [comment] 2018-10-16 12:59
OK, so here's the deal. `measuredHeight` is entirely something else.

You can use `contentHeight` for this purpose.

**Comment by Varshamathukumalli** [comment] 2018-10-17 07:07
The way you are suggesting is to provide the height occupied by the legends to the parent container.
In that case scroll is not needed.
But the way we wanted is to provide a max-height to the parent div and then provide scroll.
Because in some case, we may get 100 legends then we will  display initially 30/40 and then provide scroll, so that the chart can look good.
Is there any way to do that?
