### ISSUE TITLE
How to reduce the gap between legend and chart

### ISSUE THREAD

**Issue by Varshamathukumalli** [amcharts/amcharts4#518] opened 2018-11-02 09:19 UTC
Hi,

There is a gap of around 20px between chart and legend as in the below link:
https://codepen.io/varshamathukumalli/pen/PxYKQB?editors=0010
How to customize the gap

**Comment by martynasma** [comment] 2018-11-02 10:12
That "gap" consists of two parts:

1) Legend item padding. To disable it use this:

```
chart.legend.itemContainers.template.paddingTop = 0
```

2) X axis' label padding:

```
categoryAxis.renderer.labels.template.paddingBottom = 0
```

Using above two will completely eliminate gap between legend text and axis labels.

Update according to your needs.

**Comment by Varshamathukumalli** [comment] 2018-11-02 12:43
This will work when the legends are at bottom.
How to change that when the legends are at left/right

**Comment by martynasma** [comment] 2018-11-02 12:54
The following should reduce the gap:

```
chart.legend.marginLeft = 0;
chart.legend.marginRight = 0;
```

Another thing to consider is that when legend is placed to the side, and its `width` is not explicitly set, it defaults to 200px.

So you may want to set some other `width` as per your requirements.

**Comment by Varshamathukumalli** [comment] 2018-11-02 13:31
I have changed the width of legend in the above url.
I applied margin and even padding, still there is space between chart and legend

**Comment by martynasma** [comment] 2018-11-02 13:56
If I add this:

```
chart.legend.position = "left";
chart.legend.marginLeft = 0;
chart.legend.marginRight = 0;
chart.legend.background.fill = am4core.color("red")
chart.legend.background.fillOpacity = 0.3;

valueAxis.background.fill = am4core.color("green")
valueAxis.background.fillOpacity = 0.3;
```

I get this:
![image](https://user-images.githubusercontent.com/1458520/47919290-adbc9980-deb7-11e8-8d9c-1a94bacfdf2b.png)

No gap between legend and axis.

The problem is that there's no way to apply legend item crop to be precisely happen and axis width. This is why you are seeing "gap".

**Comment by martynasma** [comment] 2018-11-24 14:15
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2018-11-24 14:15 UTC
Labels: question

**Comment by NPC** [comment] 2019-01-09 21:09
> Another thing to consider is that when legend is placed to the side, and its width is not explicitly set, it defaults to 200px.

@martynasma, is it possible to set legend width based on its contents by default? (+padding) I think this used to be the behaviour in V3, so now there's a massive gap for short labels — and for dynamic charts it is difficult to know text width before it is rendered.

**Comment by martynasma** [comment] 2019-01-11 16:53
@NPC We found that fixed-width legend works better in more cases. When legend width is dynamic, you get unpredictable leftover for the main chart, which could lead to chaotic view if you have several charts, or even one - if there's one single label your Pie chart will shrink to nothingness.

Maybe we will consider implementing the dynamic-width legends as well. If you really think those could be useful, can you open a new issue for that? :)

And yes, setting `position` to "left"/"right" also sets legend `width` as part of the process, hence `width` setting, set previously gets overridden.

**Comment by NPC** [comment] 2019-01-11 18:20
@martynasma Thank you for considering this. 

Fixed width works well (and I bet is much faster) for pre-determined charts, where you know the serie names in advance. 

Yet for dynamic charts it means that AmCharts library leaves it with developers to come up with external hacks to assess and adjust legend width, instead of providing it internally. So in my opinion this option would make your library more powerful. 

This also relates to axis label overlap, as I discussed with you in another issue.

PS For fixed width I think it'd be good to include simple tooltips on all potentially truncated text elements (doesn't have to be fancy, title="…" should be enough). I can probably add it via an adapter, still didn't delve into that part of your massive docs :)

**Comment by martynasma** [comment] 2019-01-14 12:48
I Agree. Makes sense.

Would you be up for opening separate issues for automatic dynamic-width legend and title or tooltip for truncated text?

The later is useful anywhere else, not just Legend, I think.

**Comment by manisha-seclogic** [comment] 2020-10-16 13:37
![image](https://user-images.githubusercontent.com/64947641/96265248-d5dd2e80-0fe2-11eb-8758-f1e2544a2e92.png)

How can we reduce the gap between 2 legends?

**Comment by Cheng007** [comment] 2021-06-09 10:35
How can we reduce the gap between 2 legends
___________

**Comment by manisha-seclogic** [comment] 2021-06-09 10:40
Hi
 
 chart.legend.horizontalGap = 0;
 chart.legend.labels.template.marginLeft = 4;
 chart.legend.labels.template.marginRight = 0;
 
 Update according to your needs.

**Comment by Cheng007** [comment] 2021-06-09 11:00
Not directly, it gave me ideas
3Q

**Comment by eduardmavliutov** [comment] 2024-06-06 14:37
Can anyone answer this, please: how can we change the gap between legend item's marker and its label? I've managed to reduce the gap between separate legend items, but don't know how to place marker and label closer. 
<img width="526" alt="Screenshot 2024-06-06 at 18 36 31" src="https://github.com/amcharts/amcharts4/assets/40761402/8d763c08-14bf-4273-97d6-817be7f9e0e8">
