### ISSUE TITLE
AxisRange/Guide Tooltip. Overlapping guides tooltip.

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#789] opened 2019-01-08 14:03 UTC
Is there a way to show a tooltip, when hovering a guide/date range (so it that it follows the cursor)? And is there a way to show the tooltips of overlapping guides at the same time, or somehow combined in one tooltip?
In amCharts 3, there was a event handler `handleGuideOver`. I used this, to show the tooltip with `chart.showBalloon(...)`. I also tried to figure out somehow, which guides are overlapping, and showed there tooltip content in one tooltip (e.g. with newline seperated).

**Comment by CipSoft-Components** [comment] 2019-01-08 15:38
I tried to use
```
...
"axisFill": {
        "fill": "#CC0000",
        "fillOpacity": 0.1,
        "stroke": "#CC0000",
        "strokeOpacity": 1,
        "strokeDasharray": "2",
        "tooltipText": "Guide title",
        "tooltipPosition": "pointer",
        "hoverable": true,
        "events": {
          "over": function() {
            console.log("guide hovered");
          }
        }
      }
...
```
But no tooltip is displayed and the event is not fired.

**Comment by martynasma** [comment] 2019-01-11 16:41
Axis fills by default have their interactions disabled, so they do not interfere with stuff. You need to enabled them:

```
axisFills: {
  // ...
  "interactionsEnabled": true
}
```

Notice `axisFills` is plural, not singular like in your code snippet.

The rest of the config looks good.

**Comment by CipSoft-Components** [comment] 2019-01-14 08:12
@martynasma thank you, with this attribute set to `true` it works. Suggestion: the default value of `false` should be in the API documentation. And best, all other attributes dependent to it like `hoverable` should have a hint to the `interactionsEnabled` attribute.

Btw. I looked clearly at the documentation because of plural of `axisFill`, but it is singular, and works with singular `axisFill`. What is plural is `axisRanges`, did you mean this?

**Comment by martynasma** [comment] 2019-01-14 08:21
Good catch. I feel stupid now :)

`axisFills` (plural) is a property of axis renderer. Which would work just as well.

So `axis.axisFill` is an eequivalent of `axis.renderer.axisFills.template`. (with some exceptions which I'm not going to get into detail here) :)

As for defaults, it's difficult. `interactionsEnabled` is an inherited property. So the description is inherited as well. Different objects might set it to `false` in their own constructors, which is not caught by TypeDoc while generating class reference.

**Comment by CipSoft-Components** [comment] 2019-01-14 08:30
Ok, I understand the documentation problem.
@martynasma about my other question with tooltip combination of overlapping axis ranges, is there a way to get all axis ranges for the mouse cursor? For example sth. like getAxisRanges(x, y)

**Comment by martynasma** [comment] 2019-01-14 08:42
No, I don't think so.

There's [`hitTest()`](https://www.amcharts.com/docs/v4/reference/sprite/#hitTest_method) which tests whether two elements have any overlapping parts. Maybe you can loop through axis ranges and test against some cursor element.

Or develop your own method based on code of `hitTest`:

```
	public hitTest(sprite: Sprite): boolean {
		// validate, otherwise we will not know measuredWidth and measuredHeight
		if (this.invalid) {
			this.validate();
		}
		if (sprite.invalid) {
			sprite.validate();
		}

		let ax1 = this.pixelX;
		let ay1 = this.pixelY;
		let ax2 = ax1 + this.measuredWidth;
		let ay2 = ay1 + this.measuredHeight;

		let bx1 = sprite.pixelX;
		let by1 = sprite.pixelY;
		let bx2 = bx1 + sprite.measuredWidth;
		let by2 = by1 + sprite.measuredHeight;

		return !(bx1 > ax2 || bx2 < ax1 || by1 > ay2 || by2 < ay1);
	}
```

Those are just raw ideas, not a definitive advice.

**Comment by CipSoft-Components** [comment] 2019-01-14 16:08
@martynasma I'm now using an adapter on `tooltipHTML`, use `cursor.point.x` for the mouse position, and `group.node.getBBbox()` to get axis fill positions and measures.
`measuredWidth` didn't worked out, because it always was 0 for the axis fills.

Theoretically it works now, but it has different problems. The adapter is called very irregularly, like the `over` event. When entering a axisFill, the `cursor.point.x` value is the previous one, before entering. And it updates at an undefined time, when moving over the axisFill (but sometimes it do not update at all). It looks like it updates when touching a grid line for example. This I could fix, because I know, if the adapter is called the cursor is over the axis range, so I can say the cursor is at least on one side of the ends (of course the nearest one).
But the next problem is, because it do not update on every move, I can't figure out, when it is moving over another overlapping axisFill, because the adapter is not triggering. So I thought, invalidating the tooltip in the track event, but this didn't worked out.
But by debugging this, I found out, that the track event fires, even when not hovering the element, it even fires, when not hovering the svg element, it is always firing. Then I played around with `hoverable` and `trackable` and the corresponding events, and it doesn't matter if they are false, the events are firing (with `interactionsEnabled` set to true).

Here my code snippet of the adapter:
```
...
"adapter": {
          tooltipHTML: (text, target, key) => {
            var toolTip = '<div>' + target.tooltipText + '</div>';
            var targetBBox = target.group.node.getBBox();
            var cursorX = chart.cursor.point.x;
            if (cursorX < targetBBox.x) {
              cursorX = targetBBox.x;
            } else if (cursorX > (targetBBox.x + targetBBox.width)) {
              cursorX = targetBBox.x + targetBBox.width;
            }
            var axisRanges = chart.xAxes.values[0].axisRanges.values;
            for (var i in axisRanges) {
              var axisRange = axisRanges[i];
              if (axisRange.axisFill == target) {
                continue;
              }
              var bBox = axisRange.axisFill.group.node.getBBox();
              if (cursorX >= bBox.x && cursorX <= (bBox.x + bBox.width)) {
                toolTip += '<div style="border-top: grey 1px solid;">' + axisRange.axisFill.tooltipText + '</div>'
              }
            }
            return toolTip;
          }
        }
...
```

**Comment by martynasma** [comment] 2019-01-16 08:35
Tracking event always firing is by design.

It's a very bad UX to discontinue tracking, say a cursor position, with user is moving mouse close to the edge of the tracked object, then moves out a a bit out and all activity stops.

User expects tracking to continue and pick up when he/she's back into tracked area.

You can, use object's [`fitsToBounds()`](https://www.amcharts.com/docs/v4/reference/container/#fitsToBounds_method) method to check if current position of the cursor is within the bounds.

**Comment by CipSoft-Components** [comment] 2019-01-16 14:18
@martynasma ok I think, i'm a bit confused. Here my questions/concerns:

- For what is the property `trackable`? In the docs its says "Indicates if the element is trackable (mouse position over it is reported to event listeners). Will invoke track events whenever pointer (cursor) changes position while over element." So I thought, this handles, if the track event is fireing or not, or I'm wrong? (I also tested this option the interactions property object)
- I thought, the event is only fireing, if the mouse is over the sprite, its defined to, like it says in the docs: "Invoked when pointer (mouse cursor or touch point) moves over trackable Sprite."
- I understand, that the mouse should be tracked everywhere, but the events should only be fired, if the mouse hovers the element, a event listener is defined to, or I'm wrong?
- In my case I have many axis ranges and added the event to their axisFill sprite. So, the event is fired for every axisFill at every time, the mouse is moved, even if its not over the element, It also fires if it is somewhere in the page not even the svg element.
- What is the best way to have mouse following tooltips when hovering over axis ranges,, which updates there content on mouse move? In my case, to detect overlapping axis ranges, and show a tooltip with the combined texts.

**Comment by martynasma** [comment] 2019-01-21 17:09
Quick note: adding "track" event on an object will automatically set it as `trackable`, because otherwise, what's the point of adding the event? :)

Yes, "track" event will trigger on object when pointer moves even if it does not directly over object. There are a number of situations where this is necessary, one of which I already explained.

In your case, you should probably just check if `ev.target.isHover` to disregard track invocations when element is not hovered.

**Comment by martynasma** [comment] 2019-01-25 13:11
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2019-01-25 13:11 UTC
Labels: question
