### ISSUE TITLE
Show first label on dateAxis

### ISSUE THREAD

**Issue by AnastasiiaTsvetkova** [amcharts/amcharts4#1899] opened 2019-11-19 11:21 UTC
Hi! 
I have a problem with showing the first label in the dateAxis. I want to show first and last label but label starts from the second.
When I set up minGridDistance first label will appear with all labels. But when width of the chart reduces the first label will disappear.  I don't need to show all labels. 
![image](https://user-images.githubusercontent.com/55182060/69141917-60b16280-0ace-11ea-8a51-f876c7b8133a.png)

How could I show label from the first point?
https://codepen.io/atsvetkova7/pen/eYYxBvQ

Thanks

**Comment by rmwever** [comment] 2019-11-20 08:23
Seems like this might be a duplicate of #1551

**Comment by martynasma** [comment] 2019-11-20 10:34
Well, the scale starts at timestamp of the first data item and ends with the timestamp of the last one.

The grid on the other hand is drawn according to a multitude of factors like [`minGridDistance`](https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#Setting_the_density_of_the_the_grid_labels) and [`gridIntervals`](https://www.amcharts.com/docs/v4/concepts/axes/date-axis/#Axis_grid_granularity).

If grid and start/end timestamps do not coincide, you don't get start/end labels.

Simple solutions might be:

1) Increasing grid granularity like you suggested.
2) Setting `min` and `max` of the `DateAxis` to the timestamps that are more likely to "get a grid line".

There are also other solutions, like manually placing an [axis range](https://www.amcharts.com/docs/v4/concepts/axes/axis-ranges/#Ranges_as_guides) with a label on specific arbitrary timestamps.

Hope this helps.

**Closed** 2019-12-30 05:44 UTC
Labels: question
