### ISSUE TITLE
StepLineSeries gap/connect makes the graph look awkward

### ISSUE THREAD

**Issue by Fawwad-Khan** [amcharts/amcharts4#1068] opened 2019-03-13 11:25 UTC
Hey,
 I've been trying to implement a SteppedLine chart with gaps in line when theres no presence detected. I've been successful up until the point of displaying gaps. When I set connect in StepLineSeries to false, it makes the graph look weird, the StepLineSeries is replaced with what I think is a normal LineSeries.

This is how it looks without the connect = false.
![Stepped Without connect](https://user-images.githubusercontent.com/41516971/54275481-889a0f00-45ac-11e9-8d33-f6f37ab94d2d.PNG)

and this is how it looks with the connect = false.
![Stepped With connect](https://user-images.githubusercontent.com/41516971/54275497-95b6fe00-45ac-11e9-853e-4acdc7593e92.PNG)

Thank you,

**Comment by martynasma** [comment] 2019-03-13 16:03
Indeed. Thanks for the heads up!

Will let you know when the fix is available.

Example for testing for the dev team:
https://codepen.io/team/amcharts/pen/df3ba84cf292fee4da8d79137e98acbd?editors=0010

**Comment by zeroin** [comment] 2019-03-13 18:04
You can solve this issue by setting:

`dateAxis.baseInterval = {timeUnit:"year", count:1};`

And most likely we will fix this issue in next release, but setting baseInterval is a good thing both for avoiding situations like these and also for a better performance.

**Comment by martynasma** [comment] 2019-03-14 18:05
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-03-14 18:05 UTC
Labels: bug, in next release

**Comment by Fawwad-Khan** [comment] 2019-03-15 11:22
Its still displaying the chart awkwardly, I tried setting the base interval and updated the library. It only happens when I set series.connect to true,
![still](https://user-images.githubusercontent.com/41516971/54428154-63d5a100-473e-11e9-898e-b96f5f146804.PNG)

**Comment by martynasma** [comment] 2019-03-15 11:43
Have you cleared your browser cache? :)

Also, if you are still seeing issue , can you post your chart as codepen so that we can test?

**Comment by Fawwad-Khan** [comment] 2019-03-15 11:49
I didn't exactly cleared my cache but I hard refreshed it with ctrl+f5, and tried running it in incognito, It looks better than before but still with diagonal risers.
Its a private repository, so I cant exactly share it, I'll try to replicate it after my work hours and post a codepen.
My data is coming with 20/30 seconds intervals and not years, if that helps.

**Comment by martynasma** [comment] 2019-03-15 11:52
Yes, that would help a lot. I can't seem to be able to reproduce it after update.
