### ISSUE TITLE
Cursor not working for series with data

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#237] opened 2018-08-14 14:39 UTC
It seems that cursors do not work when data is added to a series instead of global data property.

Here's a simple repro: https://codepen.io/victorjuliani/pen/RBOYdp?editors=0010

Just replace series.data with chart.data and cursor will be visible.

**Comment by martynasma** [comment] 2018-08-15 05:40
This is a duplicate of #158

I'm going to close this, but please subscribe to the updates on #158 so that you're posted about the progress.

**Closed by martynasma** 2018-08-15 05:40 UTC
