### ISSUE TITLE
Line charts series rendering hidden

### ISSUE THREAD

**Issue by tobiu** [amcharts/amcharts4#2553] opened 2020-06-06 21:30 UTC
This worked fine yesterday and now series render hidden by default.

Online demo:
https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/apps/covid/index.html#mainview=table

using: https://www.amcharts.com/lib/4/charts.js

Did something change?

Clicking on the series legends will show them again. setting hidden: false on a series does not fix it (was the default anyway).

Thanks for looking into it!

Best regards,
Tobias

**Comment by zeroin** [comment] 2020-06-07 06:42
Could you point us to the source of the chart setup or create a codepen which would reproduce this issue?

**Comment by zeroin** [comment] 2020-06-07 07:35
We reproduced the issue and will fix it shortly.

**Comment by martynasma** [comment] 2020-06-07 08:48
Fixed in [4.9.26](https://github.com/amcharts/amcharts4/releases/tag/4.9.26).

## [4.9.26] - 2020-06-07

### Fixed
- Series with `showOnInit = false` were not shown on a chart initially (since last release only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-06-07 08:48 UTC
Labels: bug, in next release

**Comment by tobiu** [comment] 2020-06-07 10:29
That was fast. Congrats!

Off topic: Would it be interesting for you to create demos which run in multiple browser windows at the same time without any backend communication?

Just finished the SharedWorkers support in the neo.mjs context and it was a top story on Medium yesterday.

Friends link:
https://medium.com/swlh/neo-mjs-v1-2-5-support-for-sharedworkers-including-firefox-b31f144cea3f?source=friends_link&sk=6bd4d0beb0e095c388153ce8f06aa76f

Best regards,
Tobias
