### ISSUE TITLE
panBehaviour enabled prevents map from zooming

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2711] opened 2020-07-17 07:34 UTC
Hi.
I am working with an am4charts map and I set the panBehaviour option of the `MapChart` to `rotateLong`
```
this.map = am4core.create('map_div', MapChart);
this.map.panBehavior = 'rotateLong';
```

If in the first place I drag the map and then I zoom using the `zoomToRectangle` function the map freezes, an error is shown in the console all interactions with the map are disabled.
![image](https://user-images.githubusercontent.com/37619567/87760667-c2ba9700-c818-11ea-8b23-014582e5fcd6.png)

If I don't drag the map and I zoom, it works fine.
I've created a simple CodePen demo: https://codepen.io/directcuteo/pen/wvMXzOe

**Comment by martynasma** [comment] 2020-07-21 09:08
Fixed in [4.9.31](https://github.com/amcharts/amcharts4/releases/tag/4.9.31).

## [4.9.31] - 2020-07-21

### Changed
- Global adapters are being deprecated due to performance reasons. They will still work on some properties, but may be turned off at some future version. If you are using `am4core.globalAdapter`, please consider refactoring your code in some other way.
- If `groupInterval` is manually set, `DateAxis` now prepares all intervals. Normally, the chart does not prepare data sets for time intervals longer than the span of dates in the data. This causes problem in case user sets these intervals manually using `groupInterval`. Note, the groupInterval must be set initially, before data parsing in order data to be grouped into all groupIntervals.

### Fixed
- "Year of week" (`YYYY`) was not being calculated correctly by `DateFormatter`.
- Regression plugin was not working correctly in an all-`ValueAxis` scenarios.
- `ColumnSeries` were not working with `dropFromPreviousState`.
- If data was changed on a chart which was zoomed and there were less data items in the new data than there was before, a JS error was triggered.
- Sometimes a chart with `XYChartScrollbar` with series in it could produce a JS error if series has its `fillOpacity > 0`.
- Series in an `XYChartScrollbar` was not being shown if `options.onlyShowOnViewport = true`.
- `zoomToRectangle()` call was resulting in an error if called after the `MapChart` was rotated.
- `CurvedColumnSeries` columns were not being filled with proper color (black was being used instead).
- A chart with multiple series starting/ending not at the same position could result in wrong zoom on `ValueAxis`.
- `DateAxis` with millisecond `baseInterval` sometimes could show one millisecond less than actual data point in its tooltip.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-07-21 09:08 UTC
Labels: bug, in next release
