### ISSUE TITLE
Export image with browser zoom creates black borders

### ISSUE THREAD

**Issue by apuntovanini** [amcharts/amcharts4#2598] opened 2020-06-17 14:18 UTC
When exporting charts in .jpg on .png with a browser zoom different than 100%, amcharts creates an image with a black-ish border

**Comment by martynasma** [comment] 2020-06-18 06:07
Does this happen in all browsers for you? I tried zooming a page with a simple chart in Chrome then export to PNG. No black border.

Can you provide more details on how to reproduce it?

**Comment by apuntovanini** [comment] 2020-06-18 06:08
Did you try to unzoom to 90% for instance?

**Comment by martynasma** [comment] 2020-06-18 07:49
Indeed, yours is somewhat off.

Though I still can't seem to reproduce it. Here's mine, exported at 90%:

![amCharts (7)](https://user-images.githubusercontent.com/1458520/84992924-3d788f80-b151-11ea-9814-99b50ec213c6.png)

Which browser are you using?

**Comment by apuntovanini** [comment] 2020-06-18 07:52
It's chrome 83.0.4103.97 on Mac

**Comment by martynasma** [comment] 2020-06-18 10:48
Still can't reproduce it :(

The below was exported on a Macbook with Chrome at 90%.

![amCharts (1) (1)](https://user-images.githubusercontent.com/1458520/85011579-635e5e00-b16a-11ea-81f6-cc26a18e9377.png)

**Comment by apuntovanini** [comment] 2020-06-18 13:40
I really don't know how to help reproducing it though, it happens to me in the official docs, no specific implementation...anyone else facing this issue?

**Comment by martynasma** [comment] 2020-06-18 13:57
I know it's a long shot, but can you clear your browser cache and try again? Just in case some older version of amCharts is cached there.

**Comment by martynasma** [comment] 2020-06-18 13:58
Also, are you testing directly from amCharts docs website through embeds, or open charts in CodePen?

**Comment by apuntovanini** [comment] 2020-06-18 14:01
Cleared the cache but nothing changed, tried both (CodePen and docs), unfortunately doesn't work.

**Comment by apuntovanini** [comment] 2020-06-19 06:07
Tested in:
- Firefox (on my Mac) => Not working
- Chrome on Windows (very last version, 64bit)  => Not working
- Safari (on my Mac) => Works!

**Comment by martynasma** [comment] 2020-06-19 06:44
I'm a bit stumped of what to do next. Technically, I can image why that might be happening, but it's hard to do anything without being able to reproduce it :/

I'll keep trying to reproduce it. Meanwhile if you could provide more details about your setup (OS/version; does this happen at all chart dimensions; etc.) that would be great.

**Comment by apuntovanini** [comment] 2020-06-20 13:35
I fully understand you...I don't know what happens either, I work on macOS Catalina 10.15.5 (but did not work on Windows either), it just happens everytime I try to export a chart with a 90% scale...how can I help you?

**Comment by martynasma** [comment] 2020-06-22 13:36
I'm sorry, but I don't know :(

I did try it on Windows as well. It exports fine on 90% zoom.

Maybe it's some size issue? Did you try with various chart sizes?

**Comment by martynasma** [comment] 2020-06-26 07:31
Update. Was finally able to reproduce this. The fix is already in place, and will be released soon.

Will notify here when it happens.

Thanks for hanging in!

**Comment by apuntovanini** [comment] 2020-06-27 07:30
Good to hear that, thank you very much!

**Comment by martynasma** [comment] 2020-06-29 12:09
Fixed in [4.9.28](https://github.com/amcharts/amcharts4/releases/tag/4.9.28).

## [4.9.28] - 2020-06-29

### Added
- New adapter `xlsxWorkbook` in `Export`. Will allow decorating a Workbook object before it is exported.
- `chart.exporting` text-based API functions (`getSVG()`, `getCSV()`, `getJSON()`, `getHTML()`) now have third parameter (boolean). If set to `false` they will return a raw output, rather than data:uri.
- `zoomable` property added to all axes (default: `true`). Setting it to `false` will make axis not react to zoom events from scrollbar/cursor.

### Changed
- Removed `focusable` from map chart background series.
- Polyfills in `.js` file will now only load on-demand, making it with some frameworks that override default objects.

### Fixed
- Regression plugin: the regression line was not being drawn correctly on a chart with horizontal `ValueAxis`.
- Export: images exported on zoomed-out pages sometimes were showing visual artifacts.
- If a chart cursor was visible (because of soft or hard `triggerMove()` calls) but the real mouse was out of the plot area, the cursor used to react to clicks even though it shouldn't have.
- `ForceDirectedNode`'s `fill` and `stroke` adapters were not working properly if nodes were initially collapsed.
- `Sprite.hitTest()` method was not working properly with `nonScaling = true`.
- If a `MapChart` had geodata loaded via `geodataSource.url`, the map used to disappear after div size changed.
- If a legend of a `MapChart` was disposed, a JS error might happen in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-06-29 12:09 UTC
Labels: bug, in next release
