### ISSUE TITLE
Having 2 types of yAxes on same chart - Question

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts4#291] opened 2018-08-27 14:44 UTC
How can I accomplish this:
oX-CategoryAxis() and oY-ValueAxis() on chart and
inside XYChartScrollbar() oX-ValueAxis() and oY-ValueAxis() with different data for each.

Something like this: https://codepen.io/aniov/pen/LJNBvg?editors=0010 but one with oX-CategoryAxis().
Or it has to have same ox Axis type?

Thank you.

**Comment by martynasma** [comment] 2018-08-29 05:39
Sorry for not getting back earlier.

So essentially you need to have a chart in the XYChartScrollbar that is absolutely not related to the chart below it?

Technically, it's possible, however I'm trying to make a sense out of it, since it sounds a bit unusual.

**Comment by aniov** [comment] 2018-08-29 07:54
Yes it was unusual, so I change it to have same oX type axis to be both CategoryAxis(). But something is off with representing charts when category axes has numbers as data.
Shouldn't be oX values for both axes consecutive?

Here is a pen example: https://codepen.io/aniov/pen/jvrmNz?editors=0010

**Comment by martynasma** [comment] 2018-08-29 09:39
OK, so the issue is that both category axes use the same data set. Even though the fields in some data point are missing, it skews the total number of data items for a category axis, hence the anomaly.

Solution is to assign isolated data to both category axes with just the categories they are supposed to have.

To illustrate the point, I have modded your pen:

https://codepen.io/team/amcharts/pen/78602b03b5a807505517218cfad377ab/

Hope it makes sense.

**Comment by aniov** [comment] 2018-08-29 17:02
This is what I wanted. Thank you.

**Comment by martynasma** [comment] 2018-08-30 11:55
Perfect!

I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2018-08-30 11:55 UTC
Labels: question
