### ISSUE TITLE
tooltipHTML content space is cut in half on retina displays

### ISSUE THREAD

**Issue by mfamilia** [amcharts/amcharts4#684] opened 2018-12-13 18:53 UTC
The below is a screenshot of one of the demos from the docs, the tooltip is cut of but only on Safari on a retina display. Does not occur in Chrome on the same display.

https://www.amcharts.com/docs/v4/tutorials/tooltips-with-rich-html-content/
https://codepen.io/team/amcharts/pen/xaBYme

<img width="258" alt="screen shot 2018-12-13 at 1 47 31 pm" src="https://user-images.githubusercontent.com/1612331/49960209-adafb080-fedd-11e8-8479-bafbb25908cd.png">

Was able to correct this by changing the function from `Utils.getPixelRatio` to always return 1.

**Comment by martynasma** [comment] 2018-12-13 20:07
Duplicate of #676.

I'm going to go ahead and close this. Please subscribe to the above issue for updates.

**Closed by martynasma** 2018-12-13 20:07 UTC

**Comment by martynasma** [comment] 2018-12-17 14:36
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.
