### ISSUE TITLE
do not preventDefault on keydown!

### ISSUE THREAD

**Issue by evazzadeh** [amcharts/amcharts4#47] opened 2018-05-29 08:55 UTC
We found that amCharts4 preventDefault on keydown and after use v4 $(document).keydown() is not fire!

**Comment by martynasma** [comment] 2018-05-29 09:33
OK, that's definitely not good :)

We've already fixed a bunch of errors like that. Looks like we missed on.

Will keep you posted here about the progress.

Thanks for the heads up!

**Comment by martynasma** [comment] 2018-05-29 13:22
I'm trying to reproduce this and can't seem to be able to.

`"keydown"` events fire just fine on a page with amCharts. Tried it in plain JS and jQuery like in your post.

Can you please double check you are running the latest version? (4.0.0-beta.25)

If you are loading from CDN, make sure you clear your browser cache.

If the problem persists, could you please provide a link or some chart config you are using so that we can test?

Thanks!

**Comment by martynasma** [comment] 2018-05-30 13:32
Since I can't seem to be able to reproduce it, I'm going to go ahead and close this.

But feel free to reopen should you have a way to reproduce it.

Thanks!

**Closed by martynasma** 2018-05-30 13:32 UTC
Labels: bug
