### ISSUE TITLE
Maps of Russia

### ISSUE THREAD

**Issue by zaombr** [amcharts/amcharts4#1656] opened 2019-09-12 21:50 UTC
Hello.
Could you help me please.
1. I noticed that in "russiaCrimeaLow" and "russiaCrimeaHigh" geodata-maps there is no Karelia Republic (https://ibb.co/wBBdCKM). How to fix it?
2. Is it possible not to move to the other side of the map of Russia region "Chukotka"? (https://ibb.co/JyQ7X36). Current arrangement of  "Chukotka" causes problems with the positioning of the map on the page and zooming the map.

Thank you in advance. You are the best.

**Comment by martynasma** [comment] 2019-09-13 07:19
OK, so the issue is that in our maps Karelia (RU-KR) shares an id with Crimea, which causes one of them to be missing - ids must be unique. That's in part oversight on our end.

The correct fix for this would be to apply different code to Crimea, but there's a problem: Russian ISO does not seem to be listing any codes for Crimea. I wasn't able to find any official codes, either.

Are you aware of any information you can point me to? Or maybe we should just use Ukrainian ISO code for Crimea? Any insight would be welcome.

As for the second question, take a look here:
https://www.amcharts.com/docs/v4/tutorials/fixing-maps-for-countries-that-span-180-longitude/

**Comment by zaombr** [comment] 2019-09-13 10:13
Thank you very much. We can use RU-CR for Crimea.https://ru.m.wikipedia.org/wiki/%D0%9A%D0%BE%D0%B4%D1%8B_%D1%81%D1%83%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%B9_%D0%A4%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B810:19, 13 сентября 2019 г., Martynas Majeris <notifications@github.com>:OK, so the issue is that in our maps Karelia (RU-KR) shares an id with Crimea, which causes one of them to be missing - ids must be unique. That's in part oversight on our end.
The correct fix for this would be to apply different code to Crimea, but there's a problem: Russian ISO does not seem to be listing any codes for Crimea. I wasn't able to find any official codes, either.
Are you aware of any information you can point me to? Or maybe we should just use Ukrainian ISO code for Crimea? Any insight would be welcome.
As for the second question, take a look here:
https://www.amcharts.com/docs/v4/tutorials/fixing-maps-for-countries-that-span-180-longitude/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
priut-poeta.ru

**Comment by martynasma** [comment] 2019-10-23 06:32
Heads up, we've released a new version of geodata package, which contains fixed map of Russia.

**Closed by martynasma** 2019-10-23 06:32 UTC
Labels: bug, in next release
