### ISSUE TITLE
Series Sticky tooltips not removed while updating with new data.

### ISSUE THREAD

**Issue by mathimani** [amcharts/amcharts4#2001] opened 2019-12-29 08:33 UTC
There is an issue on sticky tooltip with property fields.

When I update chart data the previous sticky tooltip still showing in the chart.

link for demonstrating the same.

https://codepen.io/mathim/pen/WNbEyVZ

As you see from the link when I update the chart data first column tooltip must be removed, but it doesn't it always remains in the chart.

Please let me know if there any other way to fix it(if any fix available).

**Comment by martynasma** [comment] 2020-01-07 16:44
Fixed in [4.7.19](https://github.com/amcharts/amcharts4/releases/tag/4.7.19).

## [4.7.19] - 2020-01-07

### Added
- `Annotation` plugin: Added experimental setting `autoSize` (default: `false`). If set to `true`, it will try to relocated annotations relatively to chart size when it changes.

### Fixed
- Changing `fill`/`stroke` property with a `Color` with non-integer alpha was resulting in either fully opaque or fully transparent color.
- Sometimes ordering of columns of `ColumnSeries3D` was off.
- `XYSeries` on super-wide/tall charts (more than 100K pixels) were being distorted.
- `Regression` plugin: Updating data directly for regression series was not being properly invalidating it.
- Toggling `groupData` on `DateAxis` from initial `false` to `true` after the chart was inited was not working.
- Toggling `groupData` on `DateAxis` from initial `false` to `true` was resulting in icorrect `ValueAxis` scale.
- A tooltip used to remain visible after disposing sprite, if it had a tooltip shown because of `alwaysShowTooltip = true`.
- Events `datavalidated` and `beforedatavalidated` were not being fired if data was being updated to an empty array.
- Toggling `stacked` from `true` to `false` on `XYSeries` was not working properly.
- `Component.removeData()` was causing all the data to be invalidated which caused some wrong behavior.
- If some format changed (number formatter) you must now call `invalidateLabels()` in order for the new format to be applied.
- `DurationAxis` now animates newly added data in the same way as `DateAxis` does.
- Adding/removing multiple series at once to/from `XYChartScrollbar` could result error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-01-07 16:44 UTC
Labels: bug, in next release
