### ISSUE TITLE
TensionX regression

### ISSUE THREAD

**Issue by gribblem** [amcharts/amcharts4#2353] opened 2020-04-14 11:24 UTC
I have used a tensionX of 0.77, to show smoothed lines. This was working fine in 4.8.x, but since upgrading to 4.9.16 the rendering is very bad . It seems to happen when more than one series entry has same Date. See first screen shot I used to reproduce in simple example. Second Screen shot is more extreme in live system.
![image](https://user-images.githubusercontent.com/42220687/79219551-66775e00-7e4a-11ea-88ca-65e96f5dbd45.png)
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/42220687/79219686-a1799180-7e4a-11ea-8ea5-25f9e3fb846e.png">

**Comment by martynasma** [comment] 2020-04-14 15:16
The tensions algo was improved to better act in normal situations. Having two data items per timestamp is not such a situation :)

I'm afraid there's no "fix" for it, as it's not a bug, it's just how algorithm draws curve between two overlapping points.

Sorry.

**Comment by gribblem** [comment] 2020-04-14 15:32
Thank you for your prompt response. 
Looking at the screen shots, I dont think you can consider this as not a bug, the algo has not been improved it obviously has a regression. Our real-time live data may have same data stamps due to the capture resolultion. Considering how much we've just spent for a commerical AM license , I had expected more of a constructive response. How can this be resolved, via support from our license ?

**Comment by martynasma** [comment] 2020-04-15 05:09
Taking a second look. If you can provide the data for the chart in the second screenshot, that would be great. We're having trouble reproducing it.

**Comment by gribblem** [comment] 2020-04-15 14:33
Have been looking at providing the data to repro in the second screenshot. When I export from the chart (csv export), as expected we see duplicate entries (as that is what we are seeing beign rendered), but that didnt align with the server data. So, I then re-checked the call to series.addChart(), actioned in the client from the server via a WebSocket update. Now I'm only calling addChart(data) with one object each call, but if I look at that series.data, i can see that after the addChart() call, there are two duplicates entries added.
So the quesiton is  : what would cause addChart(object) to add an object twice like this ? 
My server update (which causes the addData) is coming from a websocket update, when I make a small repro to demonstrate the issue using a setInterval instead, then the issue does not happen. Is there a circumstance where series.addChart() could cause duplicate entries to be added from such an update ?

**Comment by martynasma** [comment] 2020-04-15 14:36
You are mentioning `addChart()` method. We don't have such method. Do you by any chance mean `series.addData()`?

**Comment by gribblem** [comment] 2020-04-15 14:42
Yep...sorry Lockdown fogging brain !

**Comment by martynasma** [comment] 2020-04-15 14:46
No worries. Let's see if we can make it work.

**Comment by gribblem** [comment] 2020-04-16 15:52
Is there an update on my questions yesterday, what would cause addData(object) to add an object twice ?

**Comment by martynasma** [comment] 2020-04-17 05:48
> Is there an update on my questions yesterday, what would cause addData(object) to add an object twice ?

It's entirely different issue. We're fixing the tensionX irregularity which this issue is about.

I kindly ask you open a separate issue or a ticket with amCharts support if you'd like to pursue the double data point thing.

Let's keep GitHub from multi-themed megathreads.

**Comment by martynasma** [comment] 2020-04-20 14:54
Fixed in [4.9.17](https://github.com/amcharts/amcharts4/releases/tag/4.9.17).

## [4.9.17] - 2020-04-20

### Added
- Global option `am4core.options.nonce` added. If set, amCharts will use this as a nonce-parameter for all dynamically created stylesheets, so it can be addressed in `Content-Security-Policy` headers.
- New `Popup` property: `dynamicResize`. If set to `true` (default) and contents contains unloaded images it will resize itself when those finish loading.
- `gradientUnits` added to `LinearGradient`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `filterUnits` added to `Filter`. If you're setting gradient on a perfectly straight line, set it to `userSpaceOnUse`.
- `startLocation` and `endLocation` added to `CategoryAxisBreak`. Can use to indicate where exactly within category break should start and end.

### Changed
- `Popup` now will size itself to accommodate images inside it as they are being loaded. To disable, set `Popup`'s `dynamicResize = false`. Also make sure you enable `maxWidth`/`maxHeight` in your CSS to avoid unreasonably large popups for unsized images.

### Fixed
- Week number in date format (`"ww"`) was not accounting for daylight saving.
- Pressing ENTER on a focused Legend item will no longer toggle related series if legend's item containers are sett to be not togglable.
- Exporting to SVG no longer breaks if chart contains `foreignObject` elements with SVG's in them.
- Line smoothing (`tensionX` / `tensionY`) now drops out duplicate points to avoid weird loops on overlapping data items.
- Chart was zooming incorrectly, when data was added directly to stacked series and one of the series was hidden.
- Some performance issues with `XYCursor` and a lot of series fixed.
- `LinearGradient` fill was not working on `LineSeries` under EDGE.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-04-20 14:54 UTC
Labels: bug, in next release
