### ISSUE TITLE
Bug: Changing data while zooming causes cannot set property segment of undefined

### ISSUE THREAD

**Issue by AndiLi99** [amcharts/amcharts4#979] opened 2019-02-15 15:54 UTC
When changing the data in a line series while zooming (for example when using a callback on "rangechangeended") sometimes it will throw an error. This can be caused if the new data is shorter length and the index goes out of bounds while it is processing. I'm going to submit a PR with a fix for this.

**Comment by martynasma** [comment] 2019-02-15 17:02
This might be caused by the latest update.

Here's a simplified version of a possibly related issue:
https://codepen.io/team/amcharts/pen/7e02fe86e568913ebe6f1f622b95418e?editors=0010

**Comment by AndiLi99** [comment] 2019-02-15 17:08
I had this issue before 4.1.8

**Comment by AndiLi99** [comment] 2019-02-15 17:38
The issue I was facing was introduced in 4.1.6
I tested this by changing the versions until it broke.

**Comment by martynasma** [comment] 2019-02-20 13:46
Fixed in [4.1.9](https://github.com/amcharts/amcharts4/releases/tag/4.1.9).

## [4.1.9] - 2019-02-20

### Added
- New `Sprite` property: `baseSprite`. On objects, even deep in hierarchy it will contain a reference to the main chart object.

### Changed
- Axis `min`/`max` calculation algorightm updated.

### Fixed
- On a chart with `DateAxis` and multiple series with same-date data items, bullets could sometimes disappear while scrolling the chart.
- On `DateAxis` with yearly granularity could sometimes show wrong year.
- Updating chart `data` with less data points was sometimes resulting in JavaScript error.
- `DateAxis` labels/ticks/grid was not placed in the correct position if `baseInterval.count > 1` and `location > 0`.
- Dynamically changing `ZoomControl` value of `layout` was not working correctly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-02-20 13:46 UTC
Labels: bug, in next release

**Comment by ciarancourtney** [comment] 2019-02-26 08:01
Something causes a crash in >4.1.8  when I admittedly trash `chart.data` in a loop, previously I would see the `Cannot set property 'segment' of undefined` error

**Comment by asifmehboob** [comment] 2019-02-26 21:24
> Something causes a crash in >4.1.8 when I admittedly trash `chart.data` in a loop, previously I would see the `Cannot set property 'segment' of undefined` error

Getting the same issue. 4.1.4 to 4.1.8 gives the "Cannot set property 'segment' of undefined" error and then browser crash in higher versions. For now we downgraded to the 4.1.3 version.
We are not even trashing the chart.data in a loop. Just resetting the chart.data value to a different array.
