### ISSUE TITLE
Irregular Date Intervals Tooltip Behavior

### ISSUE THREAD

**Issue by arm1n** [amcharts/amcharts4#22] opened 2018-05-11 14:25 UTC
Hi guys,

I'm trying to use the latest am4-charts to setup a date-based line chart containing dates with irregular intervals. Scaling and everything else works like a charm, but it seems that as soon as date intervals are not on a regular base, the tooltip gets only shown when hovering on the exact data point, which is nearly impossible for large datasets. I've setup a small code pen to illustrate the problem:

https://codepen.io/arm1n/pen/gzzmVQ

So my question is: Is this a bug? Or is it intended to not work with this kind of setup? I haven't found any demos using irregular date intervals. If it's by design (or simply not possible), what would you recommend to do? The only workaround, which came to my mind is using an axis range guide showing the actual value. Thanks for any help!

**Comment by martynasma** [comment] 2018-05-15 08:48
It's definitely NOT by design :)

It looks like we still have a fat `@todo` in `DateAxis` code that looks for the closest data item to be used for a tooltip.

It just uses the one that is exactly the same timestamp as position of cursor, hence the issue you described.

We'll need to fix this.

Make sure you subscribed to notifications on this issue, so you know when it is implemented.

I also tried to look for some workaround you could use in the interim, but could not find one :(

Hope it's not superurgent for you.

**Comment by arm1n** [comment] 2018-05-17 07:57
Hey, thanks for your response and insights. Yes, I weren't able to find a client-side solution for this. But there's always the possibility to do data resampling and interpolation on a database level, although this is not something I'm striving for. So yes, for my current problem I can get around this relatively easy by not using the `DateAxis`, but the actual database rows as `ValueAxis` and showing the timestamp information in tooltip - saving me from writing awful SQL queries.

Looking forward to issue resolution and thanks again for this library 👍

**Comment by martynasma** [comment] 2018-06-05 13:21
Solved in [4.0.0-beta.28](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.28) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta28---2018-06-05)).

**Comment by nhosko** [comment] 2018-12-18 06:38
Hello,

I have a similar issue when using a lot more data and with irregular date intervals - sometimes more than two values in the same minute (but never two on the same second). The tooltip is only shown for a couple of them.
Here is my code with sample data:
https://codepen.io/anon/pen/yGaXLB

@martynasma Is 4.0.0-beta.28 already included in amcharts.com/lib/4/core.js and amcharts.com/lib/4/charts.js

**Comment by nhosko** [comment] 2018-12-18 11:06
Another issue happening on data with irregular intervals is that the tooltips overlap when the mouse is not exactly on the lines where it "should be".
See this sample: https://codepen.io/anon/pen/roMzVY
Example not overlapping when cursor is on an exact point:
![image](https://user-images.githubusercontent.com/23018070/50149985-f6d87980-02bc-11e9-8820-23726475929b.png)

If I move the cursor a little bit, the tooltips will overlap:
![image](https://user-images.githubusercontent.com/23018070/50150011-09eb4980-02bd-11e9-8016-a68fb8102e9b.png)

Using Chrome Version 71.0.3578.98

**Comment by martynasma** [comment] 2018-12-24 13:00
Fixed in [4.0.11](https://github.com/amcharts/amcharts4/releases/tag/4.0.11).

## [4.0.11] - 2018-12-24

### Added
- `"disabled"` and `"enabled"` events added to `Sprite`.
- `cursorTooltipEnabled` added to `XYSeries`  If set to `false` cursor will not trigger bullet/item tooltips on series.

### Changed
- IMPORTANT (CODE-BREAKING CHANGES) For performance reasons we no longer create axis elements if they are disabled. For the same reasons we disabled by `axis.ticks` and `axis.axisFills` by default. Previously to enable them you had to set their `strokeOpacity` and/or `fillOpacity` to non-zero. This no longer will work. You will need to set `disabled` to `false` instead.
- `axisRanges` now take their default values from `dateAxis.axisRanges.template` items (`axisFill`, `grid`, `tick`, `label`). Previously they were using the defaults from `dateAxis.renderer.label` etc. This was not comfortable and counter-intuitive.

### Fixed
- `XYChartScrollbar`'s value axis was calculating `min`/`max` with a very big step.
- Ember plugin was throwing console errors.
- Fixed occasional zoom-in issue on Mobile Safari.
- `MapChart` mouse wheel zoom direction was inverted on some browsers.
- Cursor was not snapping correctly to `DateAxis` items.
- Multiple floating columns on the same category were disappearing when scrolling the chart.
- Date range fills were off when zooming on Gantt Chart.
- Overlapping tooltips problem solved.
- When `snapToSeries` was set for a tooltip, it was flickering a lot on slower browsers.
- `alignLabels = false` on a `PieSeries3D` was causing labels to be positioned incorrectly.
- `PieSeries.dataFields.radiusValue` was not accounting for `chart.innerRadius`.
- Dynamically updating `alignLabels` for `PieSeries` did not work correctly.
- Legend: `itemValueText` only worked if `valueText` was set.
- `ValueAxis` setting `maxZoomFactor = 1` was not working as expected.
- Changing values for all data items sometimes was resulting in `ValueAxis` scale going into negative.
- Some more tooltip and cursor related issues fixed.
- Axis Fill did not properly fill the whole span when axis was scaled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2018-12-24 13:00 UTC
Labels: enhancement, in next release
