### ISSUE TITLE
Series.hiddenInLegend causing browser to freeze

### ISSUE THREAD

**Issue by johnpozy** [amcharts/amcharts4#583] opened 2018-11-21 13:25 UTC
https://www.amcharts.com/docs/v4/reference/series/#hiddenInLegend_property

if i set `Series.hiddenInLegend` to `true` the browser (Chrome, Firefox) will freeze

**Comment by BrkCoder** [comment] 2018-11-21 13:45
Hey I confirm this issue, it causing the browser to freeze, any chance for a quick fix?

**Comment by martynasma** [comment] 2018-11-21 15:37
Bug confirmed.

Example:
https://codepen.io/team/amcharts/pen/fbc3073deb632beec65bd5c06add1b7f?editors=0010

(uncomment `series3.hiddenInLegend = true;`)

**Comment by BrkCoder** [comment] 2018-11-27 09:50
Hey Apparently the browser not freeze when set Series.hiddenInLegend to true , but there is no effect of hiddenInLegend on the series of current chart.

**Comment by johnpozy** [comment] 2018-11-27 10:06
> Hey Apparently the browser not freeze when set Series.hiddenInLegend to true , but there is no effect of hiddenInLegend on the series of current chart.

i see the legend is hidden in this example.. the freezing also gone.. is this already resolved?
https://codepen.io/team/amcharts/pen/fbc3073deb632beec65bd5c06add1b7f?editors=0010

**Comment by martynasma** [comment] 2018-11-28 02:47
Yes, it was fixed in 4.0.0.

Sorry guys. In the turmoil of the first non-beta release, for got to notify you :)

**Closed by martynasma** 2018-11-28 02:47 UTC
Labels: bug

**Comment by BrkCoder** [comment] 2018-11-29 15:02
Does this fix apply also for JSON Base config?
because apparently when I adding hiddenInLegend: true for the series nothing happens, this is the code:
{
      name: 'User Defined',
      type: 'LineSeries',
      hiddenInLegend: true,
      fill: '#55a2c7',
      stroke: '#55a2c7',
      dataFields: {
       dateX: 'date',
       valueY: 'UserDefined'
      },
      strokeWidth : 2,
      strokeOpacity : 1,
      strokeDasharray : '3,3',
      tooltipText: 'Threshold: [bold]{valueY}[/]',
    }

**Comment by martynasma** [comment] 2018-11-30 05:49
@BrkCoder This is something entirely different. I posted a separate issue for that: #616. Make sure you subscribe to it.

**Comment by martynasma** [comment] 2018-11-30 14:18
> @BrkCoder This is something entirely different. I posted a separate issue for that: #616. Make sure you subscribe to it.

Heads up, 4.0.3 just released, fixes this bug as well.

**Comment by BrkCoder** [comment] 2018-11-30 20:29
You rocks!!! 🥇
