### ISSUE TITLE
disable zoomout on data updated

### ISSUE THREAD

**Issue by ramarro123** [amcharts/amcharts4#392] opened 2018-09-25 12:50 UTC
i would like to disable zoomout when i change/update the dataset of a certain chart.

it's that possible? maybe with a function to check some rules like
"it's the datas on the zoom still present on dataset updated? if yes, stay with zoom, if not go out"

**Comment by martynasma** [comment] 2018-09-25 14:14
Duplicate of #354.

We're going to implement it at some time.

**Comment by rocos-david** [comment] 2018-11-23 21:35
Great, we are looking for charting tools with this capability as well.  V4 + this would work well for us.  We need it to work where we are calling both addData and removeData.  For example we want to show a continuously updated most recent 1h of telemetry data.  If you for example zoom to a specific historic segment but we continue to load data in the end and remove data at the start of the dataset we need the exact time segment to remain in zoom.  We can deal with what happens when you have zoomed in on data where we are about to remove it.

**Comment by martynasma** [comment] 2019-02-05 13:40
Fixed in [4.1.2](https://github.com/amcharts/amcharts4/releases/tag/4.1.2).

## [4.1.2] - 2019-02-05

### Added
- New `Sprite` property `strokeDashoffset` added. Can be used in conjunction with `strokeDasharray`.
- `Label` has two new properties: `path` and `locationOnPath`. If set, will layout the SVG text along a curvature of the SVG path. HTML and multi-line text is not supported.
- `AxisLabelCircular` new property `bent` added. If set to `true`, the label will be bent to follow the curvature of the circle. Distance from the circle can be adjusted using `radius` and `label.paddingBottom`. For `PieSeries` the alignLabels need to to be set to `false` for this feature to work.

### Fixed
- JSON: Having property values with both percent and minus signs in them, was resulting in error.
- "Z" code in `DateFormatter` was not taking UTC setting into account.
- Exporting SVG with Unicode characters in Edge/IE was resulting in invalid SVG.
- Fixed JavaScript error which used happen when disposing chart/changing data in some cases.
- Gantt chart sometimes was not displaying first/last data item.
- Newly added `MapLine` elements were not respecting `nonScalingStroke = true` until zoom level changed.
- Series' tooltip was not always visible with `DateAxis`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-02-05 13:40 UTC
Labels: duplicate, enhancement, in next release
