### ISSUE TITLE
Week grouping gives weird looking

### ISSUE THREAD

**Issue by sdapkus** [amcharts/amcharts4#2694] opened 2020-07-13 11:45 UTC
**Bug description**
Giving one week of data from Monday to Sunday and then changing grouping option to `{ timeUnit: "week", count: 1 }` gives weird look. If using same settings, but giving one week for example from Sunday - Saturday gives two points in graph which is okay.

**Environment (if applicable)**
amcharts4 - 4.7.0
tried updating to 4.9.30 same issue

**Additional context**

![image](https://user-images.githubusercontent.com/58326108/87300914-5dfcf500-c517-11ea-962c-e543f36f7b60.png)
![image](https://user-images.githubusercontent.com/58326108/87300954-6d7c3e00-c517-11ea-9730-ee55c91d411f.png)

**Comment by zeroin** [comment] 2020-07-14 08:22
Thanks for the heads up. This issue happens because by default we do not group to intervals if the date range in your data is less than the duration of the groupInterval (for performance reasons). This is ok when groupInterval is picked automatically, however doesn't work in your case. The only proper solution I could think of is that in case groupInterval is set from outside, dateAxis will group data of series into all dateAxis.groupIntervals`. Meaning that you'll have to set initial groupInterval to {timeUnit:"day", count:1}. I will implement this change in next release and will notify you.

**Comment by martynasma** [comment] 2020-07-23 10:28
Fixed in [4.9.31](https://github.com/amcharts/amcharts4/releases/tag/4.9.31).

## [4.9.31] - 2020-07-21

### Changed
- Global adapters are being deprecated due to performance reasons. They will still work on some properties, but may be turned off at some future version. If you are using `am4core.globalAdapter`, please consider refactoring your code in some other way.
- If `groupInterval` is manually set, `DateAxis` now prepares all intervals. Normally, the chart does not prepare data sets for time intervals longer than the span of dates in the data. This causes problem in case user sets these intervals manually using `groupInterval`. Note, the groupInterval must be set initially, before data parsing in order data to be grouped into all groupIntervals.

### Fixed
- "Year of week" (`YYYY`) was not being calculated correctly by `DateFormatter`.
- Regression plugin was not working correctly in an all-`ValueAxis` scenarios.
- `ColumnSeries` were not working with `dropFromPreviousState`.
- If data was changed on a chart which was zoomed and there were less data items in the new data than there was before, a JS error was triggered.
- Sometimes a chart with `XYChartScrollbar` with series in it could produce a JS error if series has its `fillOpacity > 0`.
- Series in an `XYChartScrollbar` was not being shown if `options.onlyShowOnViewport = true`.
- `zoomToRectangle()` call was resulting in an error if called after the `MapChart` was rotated.
- `CurvedColumnSeries` columns were not being filled with proper color (black was being used instead).
- A chart with multiple series starting/ending not at the same position could result in wrong zoom on `ValueAxis`.
- `DateAxis` with millisecond `baseInterval` sometimes could show one millisecond less than actual data point in its tooltip.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-07-23 10:28 UTC
Labels: bug
