### ISSUE TITLE
Rendering datapoints with value 0

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#650] opened 2018-12-07 23:08 UTC
At some zoom-levels datapoints with value 0 appear as small strokes. If you zoom in, they disappear. You can even hover over them and see a tooltip with value 0.

<img width="1046" alt="Screenshot" src="https://user-images.githubusercontent.com/29127314/49677086-14b40c00-fa7d-11e8-8779-3259da258921.png">

**Comment by martynasma** [comment] 2018-12-08 08:54
OK, so zero (0) is a perfectly normal value like any other numeric value. I think it's normal that a thin line is displayed for zero-value columns, indicating that "there is a value", as opposed to `null` which indicates "absence of value".

That said, there is a bug that makes `null` values still display a thin line, which is listed in this issue: #651. We'll fix it.

As for thin lines that disappear, I was not able to reproduce that. Can you provide a CodePen for such chart, so that we can test?

Finally, about tooltips. Like I wrote, zero is a perfectly good value, and it would be wrong to treat it as not a value. If you don't want tooltips displayed, indicating that there is no value, use `null` instead.

**Comment by lucianholt97** [comment] 2018-12-08 11:59
I understand your point. I inspected the objects and the height is 0, too. So this seems to be a rendering problem which also depends on the current window size. Unfortunately, I wasn't able to reproduce the behavior in a pen. Still wondering why those strokes are above the rest of the chart...
Setting 0 to null in the backend solved it for me.

**Comment by martynasma** [comment] 2018-12-08 12:56
Alright. If going to `null` solves the issue at hand, I'm going to assume you're all set.

Please feel free to close this issue if that is the case, or post any follow ups.

**Closed** 2018-12-11 21:59 UTC
Labels: help wanted, question
