### ISSUE TITLE
How to get the size of cell in one heat map as the size of cell in other heat Map

### ISSUE THREAD

**Issue by VineelaKantamneni** [amcharts/amcharts4#3880] opened 2021-11-12 04:43 UTC
I have two heat map tables like below. I want size of cell of second heat map table as the size of cell of first heat map table.
![Screenshot from 2021-11-12 10-08-05](https://user-images.githubusercontent.com/74599304/141410793-8d17b27d-9af2-4d2f-b3bc-6192f8a33223.png)

Thank You.

**Comment by martynasma** [comment] 2021-11-12 06:30
Duplicate of #3837

**Closed by martynasma** 2021-11-12 06:30 UTC

**Comment by VineelaKantamneni** [comment] 2021-11-12 06:33
No both are not same. That is about aligning both the heat maps. It is about size of cells in heat map.

**Comment by martynasma** [comment] 2021-11-13 09:00
If it's about height of the cells, then you can refer to the tutorial you mentioned in that other thread yourself:

https://github.com/amcharts/amcharts4/issues/3837#issuecomment-947718063
