### ISSUE TITLE
Cannot read property 'touch' of undefined

### ISSUE THREAD

**Issue by jeremypanelli1** [amcharts/amcharts4#3326] opened 2021-02-24 01:42 UTC
This bug started popping up for us. I found this thread, and looked added a comment and attached a video of the bug in the original thread. That thread appeared to be closed, so I am creating a new one 

https://github.com/amcharts/amcharts4/issues/3125

**Comment by martynasma** [comment] 2021-02-24 05:47
What exactly do you do to get this error? I'm trying to do exactly what you're doing in the video on Chrome, and can't reproduce it.

**Comment by jeremypanelli1** [comment] 2021-02-24 05:52
Press and hold the click/touch. I've been getting it regularly every time I try it.

**Comment by martynasma** [comment] 2021-02-24 05:54
Still no go. What version of Chrome are you using?

**Comment by jeremypanelli1** [comment] 2021-02-24 05:59
I am on the latest version of Chrome on Mac

**Comment by martynasma** [comment] 2021-02-24 06:12
I've tried this on latest MacOS with Chrome 88.0.4324.192

Still can't reproduce the error.

Do you perhaps have some kind of plugins installed. Or maybe you can try clearing browser's cache, in case there's some older version of the library is cached.

**Comment by jeremypanelli1** [comment] 2021-02-24 07:21
Definitely not any of my plugins haha - maybe try pressing and not lifting up on your mouse / touch pad? It's 100% reproducible for me, not sure what else to say - maybe you need to try a different computer or ask a coworker if they can reproduce? Because I'm able to reproduce it on the amcharts website with a newly updated browser and all plugins disabled....

Anyway, here's the full stack trace of the error - maybe even if you can't reproduce, you can see what's happening: 

`TypeError Cannot read property 'touch' of undefined 
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:2501:20 t.restoreCursorDownStyle
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1341:13 t.handleUp
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1326:22 
    node_modules/@amcharts/amcharts4/.internal/core/utils/Array.js:74:8 Object.o
    node_modules/@amcharts/amcharts4/.internal/core/utils/List.js:734:8 A.each
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1325:28 
    node_modules/@amcharts/amcharts4/.internal/core/utils/Iterator.js:57:8 
    node_modules/@amcharts/amcharts4/.internal/core/utils/List.js:40:29 
    node_modules/@amcharts/amcharts4/.internal/core/utils/Iterator.js:56:4 Object.a
    node_modules/@amcharts/amcharts4/.internal/core/interaction/Interaction.js:1324:8 t.handleDocumentLeave`

**Comment by martynasma** [comment] 2021-02-24 07:25
OK, so looking at our code base, it looks like we have already implemented a fix for that in dev version.

We should release a new version later this week.

I'll ping you once it's out, so you can check, since I can't seem to be able to reproduce this error anyway :P

**Comment by jeremypanelli1** [comment] 2021-02-24 07:36
Perfect! Thanks :)

**Comment by martynasma** [comment] 2021-03-03 07:17
Fixed in [4.10.16](https://github.com/amcharts/amcharts4/releases/tag/4.10.16).

## [4.10.16] - 2021-03-03

### Fixed
- In some rare cases an critical error could happen on hoverable objects on touch-only displays.
- Zooming and drag-rotating a resized `MapChart` could throw off the map position.
- It was possible to continue zooming the chart using mouse wheel even when max zoom was reached.
- Zooming "inverted" horizontal axis was incorrect.
- Updating data on `SankeyDiagram` in some cases could result in an SO.
- `TreeMap` was showing incorrectly sized nodes with empty children array.
- Sometimes wrapping long strings were causing punctuation at the end of the word to wrap into the next line.
- Dynamically switching `logarithmic` setting for a `ValueAxis` was not updating its scale properly in some cases.
- `SliceGrouper` plugin was not updating properly when manipulating data and/or series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2021-03-03 07:17 UTC
Labels: bug, in next release
