### ISSUE TITLE
Rendering Arrows at the end of lines in MapLineSeries

### ISSUE THREAD

**Issue by garunski** [amcharts/amcharts4#515] opened 2018-11-01 16:41 UTC
Is it possible to render Arrows at the end of lines like in version 3?

I thought that maybe adding bullets to the line series would do the trick, but that doesnt seem to do anything.

https://codepen.io/anon/pen/Lgwopr

**Comment by martynasma** [comment] 2018-11-02 10:04
Technically, yes. There's a [`MapLine.arrow`](https://www.amcharts.com/docs/v4/reference/mapline/#arrow_property) property.

```
lineSeries.mapLines.template.arrow.position = 1;
```

I'm saying technically, because it does not seem to be working :)

I'm marking this as a bug, and will get back to you here, once the issue is resolved, or if there's some other workaround.

**Comment by martynasma** [comment] 2018-11-07 17:29
Fixed in [4.0.0-beta.73](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.73).

## [4.0.0-beta.73] - 2018-11-07

### Changed
- `axisFills.template.interactionsEnabled` is now set to `false` by default. If you need to attach events on an axis fill, you will need to set it to `true`.

### Added
- `autoDispose` property added to `Series` and `Axis` classes with default value `true`. This means that series/axis will be automatically disposed when removed from chart's `series`, `xAxes`, or `yAxes` lists.
- It is now possible to have 3D stacked columns (by setting `clustered = false` on series).

### Fixed
- If chart container was moved in DOM tree, it stopped sensing resize and was not updating its size anymore.
- Sometimes `ValueAxis` could show zero label with a minus sign.
- Arrows on `MapLine` were not drawn.
- It was not possible to change the text color of the tooltip on `TreeMap` diagram.
- `axis.tooltipPosition = "pointer"` was not working as it should - always follow the mouse/pointer.
- If series had `data` set directly, it was still using chart's global `data`, resulting in combined datasets and potentially visual anomalies.
- Setting `cellStartLocation` did not have any effect on an already inited chart.
- Line series could be cut off in the beginning (when zoomed-in closely).
- Vertical axis ticks were not being positioned properly if axis had a title.
- 3D columns were not using chart's `depth`/`angle`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2018-11-07 17:29 UTC
Labels: bug, in next release
