### ISSUE TITLE
Multiple ValueAxes with JSON not working

### ISSUE THREAD

**Issue by CipSoft-Components** [amcharts/amcharts4#805] opened 2019-01-11 12:15 UTC
See Example: https://codepen.io/anon/pen/MZPLrW
If you setup a chart from a JSON config, with multiple ValueAxis referred by IDs, all series are only bind to the first ValueAxis, instead to referred one.

I did it like in the following tutorial page: https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Multiple_axes

**Comment by martynasma** [comment] 2019-01-11 13:30
I suppose the issue is that `id` needs to be a string. Whereas you ids are now numbers. Try converting `1` and `2` to `"1"` and `"2"` respectively.

That should fix it.

**Comment by CipSoft-Components** [comment] 2019-01-11 15:18
In my project, I tried strings, but there nothing changed. In my first example, it works with strings, you are right.
Now, I could figure out, that it has something to do, that I use the original JSON config, add the second value axis and series, and draw the chart again with `createFromConfig`.
By debugging into this, in my project, I can see, that the yAxis `id`s of the series in the JSON config are replaced by the objects directly in the configuration. So, the second time the chart is drawn, the JSON has mixed references to the yAxis, strings and objects. I think, it has something todo with this.
Here an adjusted example: https://codepen.io/anon/pen/NeOmZz

**Comment by martynasma** [comment] 2019-01-14 12:56
Yes. JSON processor finds the actual object referred by id and replaces it directly in the configuration.

This is by design.

So, if you need to refer to the object's id later on, you can refer to that object's id.

Or, if you need to reuse config across several chart instances, we suggest you duplicate it, before passing on to `createFromConfig()`.

**Comment by martynasma** [comment] 2019-01-25 13:12
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2019-01-25 13:12 UTC
Labels: question
