### ISSUE TITLE
Chart resize sensor does not work after chart container is moved in DOM tree

### ISSUE THREAD

**Issue by ysneo** [amcharts/amcharts4#524] opened 2018-11-05 03:43 UTC
<a href="https://codepen.io/ysneo/pen/EOaXLe" target="_blank">example</a>
chart resize not work when vue router toggle in <keep-alive>;

with the example,
1, go to bar; **chart can be resized when window resized**
2, then go to foo, and return to bar, **the chart can't be resized.**

**Comment by martynasma** [comment] 2018-11-05 07:07
Seems like it's not related to Vue, but rather resize sensor we are using. It seems once the chart container's position in DOM tree is manipulated, it loses ability to detect size changes.

Super simple example:
https://codepen.io/team/amcharts/pen/d573618e98d0d84c7065c9527040ea53

We are going to resolve this.

Thanks for the heads up.

**Comment by martynasma** [comment] 2018-11-05 07:43
This is a related issue on ResizeSensor repo (lib we are using to detect resizes)
https://github.com/marcj/css-element-queries/issues/246

**Comment by CipSoft-Components** [comment] 2018-12-20 13:21
When will this fix be integrated in amCharts 4. I have the same problem with a dashboard of charts. My workaround at the moment is,  to always call `<ChartObject>.svgContainer.measure()` after resizing.

**Comment by martynasma** [comment] 2018-12-20 13:41
@CipSoft-Components This has already been fixed. Just forgot to close the issue.

Are you seeing it with the latest version of amChart? If that is so, can you provide a demo?

**Closed by martynasma** 2018-12-20 13:41 UTC
Labels: bug

**Comment by CipSoft-Components** [comment] 2019-01-07 10:59
@martynasma The issue also occurs in the latest version (4.0.16).
I'm not sure if I can provide a simple demo. The dashboard uses jQuery and jQueryUI. From jQueryUI it uses sortable() and resizable(), if this helps.

**Comment by CipSoft-Components** [comment] 2019-01-07 14:14
Here is a working demo: [https://codepen.io/anon/pen/EGLePg](https://codepen.io/anon/pen/EGLePg)
It only works if the charts div is in an addition dragable div, like it is in my dashboard. If the div is dragged (it must not be sorted to a new position), and afterwards is resized, resizing is not working any longer.
Reproduce steps:

1. drag a bit
2. release the div
3. resize by dragging the border (right, bottom or the corner in between)

**Comment by NPC** [comment] 2019-01-07 23:38
I'm seeing a very similar issue (as far as I can tell), also inside a draggable/resizeable dashboard widget. Not after dragging, but after switching to a different Bootstrap tab and then returning — this created the chart anew in the same resizable container, but chart would not react to resize anymore (btw, chart.dispose() triggers "EventDispatcher is disposed" exception, so far I can't reproduce it in a simple case). 

For now I solved it by deleting the container too, and recreating everything from scratch.

**Comment by mxrugg** [comment] 2019-08-16 00:05
I’m experiencing this issue with the latest version of amcharts through using the popular gridstack layout library for my dashboard layout.

The chart resizes fine until you shrink the browser window width so far which causes gridstack to arrange all charts vertically within one column to be responsive. In their source code, to perform such a change and keep the order, they rearrange each chart container using “parentContainer.append(chartContainer)” which is effectively moving the chart container in the DOM tree.

Past this point, the charts themselves no longer resize anymore when resizing the chart containers.

Note that gridstack source code also uses jQueryUI to handle the resizing of the chart containers.

For testing, I commented out the line in their source code where it does the “append” and the charts resized properly which further points to the moving of the chart containing in the DOM tree causing the chart not to resize anymore.

**Comment by mxrugg** [comment] 2019-10-30 02:39
@martynasma can we get an update please regarding this issue?

You closed the issue but the problem still exists, at least in AmCharts 4.

**Comment by lticadler** [comment] 2020-02-07 05:49
> When will this fix be integrated in amCharts 4. I have the same problem with a dashboard of charts. My workaround at the moment is, to always call `<ChartObject>.svgContainer.measure()` after resizing.

This also works for me - thanks.
But all the chart.invalidate... Methods do not.

**Comment by compunect** [comment] 2021-04-03 22:40
Unrelated to this but I've found that the X/Y position of the chart cursor to be wrong when dynamically adding data to it.
Calling <ChartObject>.svgContainer.measure(); after first data update fixed it.
