### ISSUE TITLE
Tooltip html is blur on firefix

### ISSUE THREAD

**Issue by roshnidevadiga** [amcharts/amcharts4#724] opened 2018-12-20 06:05 UTC
When  you hover over an html tooltip in firfox it blurs after some time

**Comment by martynasma** [comment] 2018-12-21 14:13
This can be fixed by setting `pixelPerfect = true` on a tooltip.

E.g.:

```
series.tooltip.pixelPerfect = true;
```

**Comment by martynasma** [comment] 2018-12-21 14:14
Example:
https://codepen.io/team/amcharts/pen/1b86d997c9913ad2ffc5450d8aa36e9e?editors=0010

**Comment by roshnidevadiga** [comment] 2018-12-24 04:41
This doesn't seem to help me. I still find the tooltips blurred

**Comment by martynasma** [comment] 2018-12-28 16:13
How about if you set it on tooltip label directly?

```
series.tooltip.label.pixelPerfect = true;
```

The reason I'm asking is that I can't seem to be able to reproduce blurring effect anymore.

**Comment by martynasma** [comment] 2019-01-25 13:08
I'm closing this, but please feel free to post any follow up questions you may have.

**Closed by martynasma** 2019-01-25 13:08 UTC
Labels: question
