### ISSUE TITLE
addData is adding points twice

### ISSUE THREAD

**Issue by armujahid** [amcharts/amcharts4#1292] opened 2019-05-11 10:01 UTC
Example: https://codepen.io/armujahid/pen/jorPdG

I have 5 points static chart. On calling chart.addData once without removeCount parameter its adding same point twice in chart.

You can check console log of  `chart.data.length` before and after chart.addData call

**Comment by martynasma** [comment] 2019-05-11 14:59
It's a known bug, which we are trying to fix.

It only manifests itself when `XYChartScrollbar` is used in the chart.

We'll ping you once the issue is resolved.

**Comment by martynasma** [comment] 2019-05-13 18:04
Fixed in [4.4.5](https://github.com/amcharts/amcharts4/releases/tag/4.4.5).

## [4.4.5] - 2019-05-13

### Changed
- Exporting chart data to JSON format now respects `dataFields` setting.

### Fixed
- Setting `showSystemTooltip = false` on a `Scrollbar` now correctly disables tooltips on its thumb and grips.
- When data for `ForceDirectedSeries` was changed for the second time, the old links remained visible.
- Initial scatter of `ForceDirectedSeries` nodes reduced. Results in a better initial animation.
- Adding data using `addData()` method to a chart with `XYChartScrollbar` was resulting data to be added twice.
- With some special combination of axes config `XYChart` sometimes could fall into infinite loop.
- Some JS error when converting coordinates out of bounds of AlbersUSA projection fixed.
- Tooltip bounds were not being copied when cloning a `Tooltip`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-05-13 18:04 UTC
Labels: bug, in next release

**Comment by armujahid** [comment] 2019-05-14 16:52
That was fast. Thank you so much @martynasma.
