### ISSUE TITLE
Annotation enhancement

### ISSUE THREAD

**Issue by lucasgdutra** [amcharts/amcharts4#1995] opened 2019-12-23 23:17 UTC
Annotation elements not resize when chart is resized, causing overflow and sobreposition on another elements

**Comment by martynasma** [comment] 2019-12-24 12:02
We're aware about this. However, I'm not entirely sure how this should work. I guess there's no silver bullet.

Should annotations resize proportionally? What about icons? How they should be repositioned? Or resized?

**Comment by martynasma** [comment] 2020-01-07 16:44
Fixed in [4.7.19](https://github.com/amcharts/amcharts4/releases/tag/4.7.19).

## [4.7.19] - 2020-01-07

### Added
- `Annotation` plugin: Added experimental setting `autoSize` (default: `false`). If set to `true`, it will try to relocated annotations relatively to chart size when it changes.

### Fixed
- Changing `fill`/`stroke` property with a `Color` with non-integer alpha was resulting in either fully opaque or fully transparent color.
- Sometimes ordering of columns of `ColumnSeries3D` was off.
- `XYSeries` on super-wide/tall charts (more than 100K pixels) were being distorted.
- `Regression` plugin: Updating data directly for regression series was not being properly invalidating it.
- Toggling `groupData` on `DateAxis` from initial `false` to `true` after the chart was inited was not working.
- Toggling `groupData` on `DateAxis` from initial `false` to `true` was resulting in icorrect `ValueAxis` scale.
- A tooltip used to remain visible after disposing sprite, if it had a tooltip shown because of `alwaysShowTooltip = true`.
- Events `datavalidated` and `beforedatavalidated` were not being fired if data was being updated to an empty array.
- Toggling `stacked` from `true` to `false` on `XYSeries` was not working properly.
- `Component.removeData()` was causing all the data to be invalidated which caused some wrong behavior.
- If some format changed (number formatter) you must now call `invalidateLabels()` in order for the new format to be applied.
- `DurationAxis` now animates newly added data in the same way as `DateAxis` does.
- Adding/removing multiple series at once to/from `XYChartScrollbar` could result error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-01-07 16:44 UTC
Labels: enhancement, in next release
