### ISSUE TITLE
tooltipHTML does not work properly

### ISSUE THREAD

**Issue by zmey-nosak** [amcharts/amcharts4#730] opened 2018-12-21 13:46 UTC
Hello. TooltipHTML does not work properly when I use it with XYCursor and LabelBullet. You can see it there:
https://jsfiddle.net/StepanKoledov/y21tbhf9

**Comment by martynasma** [comment] 2018-12-21 13:58
This is a duplicate of #668.

I'm gonna close this issue. Please subscribe to the original one.

**Closed by martynasma** 2018-12-21 13:58 UTC
Labels: bug, duplicate

**Comment by zmey-nosak** [comment] 2018-12-21 14:01
Oh, sorry! Thank you
