### ISSUE TITLE
Print/Export to image does not render custom fonts in IE11 (beta 30)

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#99] opened 2018-06-22 13:26 UTC
Using Internet Explorer 11, the custom font being used in the chart is not rendering when exporting the chart to an image or when printing the chart.

Here's an example that shows the problem:
https://codepen.io/anon/pen/xzjmbr

Here's what the exported chart looks like in Chrome (and basically every other browser):
![amcharts_chrome](https://user-images.githubusercontent.com/900497/41778853-fe11218a-75fd-11e8-9785-714c34651cfc.png)

Here's what it looks like in IE11:
![amcharts_ie11](https://user-images.githubusercontent.com/900497/41778823-e6e85492-75fd-11e8-8db3-9ccb5994bfe8.png)

Likewise, here's what the printout looks like in [Chrome](https://github.com/amcharts/amcharts4/files/2127785/print_chrome.pdf) vs [Internet Explorer 11](https://github.com/amcharts/amcharts4/files/2127788/print_ie11.pdf).

**Comment by martynasma** [comment] 2018-06-22 13:30
Yes, I'm aware of this issue. It's relative not just to IE11, but to most of the recent browsers as well. It's in the internal TODOs.

The issue is that it's quite complicated.

Just wanted you to know, that we're looking into it.

**Comment by dswitzer** [comment] 2018-06-22 13:44
I thought it was working correctly on modern browser, but I have the font installed locally so that might be why I'm seeing the desired font.

**Comment by martynasma** [comment] 2018-08-31 11:56
Fixed in [4.0.0-beta.48](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.48).

## [4.0.0-beta.48] - 2018-08-31

### Added
- `useWebFonts` setting in `Export`. Allows disabling of download of web fonts when exporting.
- `useRetina` setting in `Export`. Images are now exported scaled up on retina displays by default. Set `useRetina = false` to disable.

### Changed
- Export fallback mechanism for older browsers changed from FabricJS to canvg, which is much lighter and has better text formatting support.
- On retina displays images will now export supersized in order not to lose quality. Set `useRetina = false` to disable.
- amCharts logo will now auto-hide on supersmall chart sizes.

### Fixed
- Cursor was zooming the chart even if drag motion was performed on an external element positioned over the chart.
- Cursor was not hidden when it was no longer hovering the chart area if chart had no padding.
- `urlTarget` was not carried over from `ListTemplate` template to new items.
- Cursor could cause chart to freeze up on a DateAxis with empty cells in the axis' beginning or end.
- Export will now correctly handle web fonts, such as Google Fonts. Please note that FontAwesome is not supported, since they forbid any kind of usage, except inclusion via CSS.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2018-08-31 11:56 UTC
Labels: bug, in next release
