### ISSUE TITLE
Legend should not interfere with touchmove events

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts4#475] opened 2018-10-21 11:01 UTC
Hello,

Is there a way to remove touchmove event capture on legend but keep the click event for hide/show series ?

Thanks for your help !

**Comment by martynasma** [comment] 2018-10-22 11:53
This is a much wider issue we are working on. I'm going to use this issue as a "base of operations", and will inform you once the issue is solved.

A legend does not have any need for zoom/select so it should not steal whole page's scroll or other touchmove events.

**Comment by martynasma** [comment] 2018-10-28 09:37
Fixed in [4.0.0-beta.64](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.64).

## [4.0.0-beta.64] - 2018-10-27

### Added
- `shouldClone` flag added to `EventDispatcher`'s `on` and `once` methods. Can be used to restrict cloning of events when object itself is cloned.
- [`showOnInit`](https://www.amcharts.com/docs/v4/reference/sprite/#showOnInit_property) property added to `Sprite`. If this is set to `true`, the `Sprite`, when inited will be instantly hidden ("hidden" state applied) and then shown (animate properties form "hidden" state to "default" state). Animation will take `defaultState.transitionDuration`. `Series`, `Chart` classes has this set to `true`, so that they would perform initial animations. If you want a sprite (chart, series) not to be shown initially, you can set Sprite's [`hidden`](https://www.amcharts.com/docs/v4/reference/sprite/#hidden_property) to `true`. (`setting sprite.visible = true` won't work as expected anymore).

### Changed
- If chart rendering takes too long, it now is split into chunks, which makes the browser/page remain responsive even if you have a lot of charts to build.
- Changed how pre-hiding Series works. If you want series to be initially hidden, use `series.hidden = true` instead of `series.visible = false`.
- Removed `"hold"` and `"rotate"` interaction events and releated options and functionality, since they weren't used anywhere.
- Removed `"delayFirstHit"` option from `Sprite.hitOptions`.
- `chart.defaultState.transitionDuration` is set to `1`. This allows the chart to appear one frame after init and helps to avoid various flickers that happen while chart is building. Animated theme has this value set to `2000`.

### Fixed
- Performance enhancements.
- Non-draggable/trackable but otherwise interactive elements of the chart no longer prevent scrolling and other gestures on touch screens.
- `PieSeries` labels sometimes were positioned incorrectly (using non-default start/end angles).
- Slices (also columns of `RadarChart`) were not drawn if `radius <= 0` (even if `innerRadius > 0`). This resulted in radar columns not rendered in some cases.
- `MapChart` was not resizing properly when div size changed.
- `PictorialStackedSeries`, while `containerdiv` was resized did flicker a lot.
- If a Tooltip is visible while its Sprite changes size/position, it updates its position as well.
- Setting `chart.data = []` was not clearing data properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2018-10-28 09:37 UTC
Labels: enhancement, good first issue

**Comment by ahmedalashhab** [comment] 2023-01-15 17:39
Hi, my chart still prevents scrolling when the user touches the chart while trying to scroll. Is there any known fix for this?
