### ISSUE TITLE
Error when disposing a chart with XYChartScrollbar

### ISSUE THREAD

**Issue by cam-m** [amcharts/amcharts4#111] opened 2018-06-29 00:30 UTC
When including an xychartscrollbar, the component initially displays and behaves as expected, but when the chart is disposed i get a (seemingly) endless loop of: EventDispatcher Error: EventDispatcher is disposed

**Comment by cam-m** [comment] 2018-07-05 12:30
Thanks for trying to replicate this @martynasma. 

My setup where I can replicate this is a bit complex and not easy to share unfortunately.

I have an angular app with many different charts a user can navigate between. I abstracted out the config for these, and just have a component per chart type (PieCharts and XYChart) into which I pass the config. 

Each component subscribes to an observable of chart config in ngAfterViewInit and, based on emissions from this stream, each component disposes of existing chart (if exists) and then creates a new one for the latest config. Here's a snippet that might make this pattern clearer...

```
   ngAfterViewInit(): void {
        this.chartSubscription = this.chartActionStreamService.chart$.pipe(
            filter((chart: Chart) => {
                const existingChartId = this.chart ? this.chart.id : -1;
                return chart && chart.amChartConfig.type === 'XYChart' && existingChartId !== chart.id;
            })
        ).subscribe(chart => {
            this.tearDownActiveChart();

            this.chart = chart;

            this.createChart();
```
The `Chart` type is just my own class for chart config and other settings like labels/tooltips etc. 

The config itself is pretty simple.
 
Without the XYChartScrollbar in the XYChart config my set up 'appears' to work fine. I can switch between charts and navigation is performant. When I add XYChartScrollbar to the config, there is huge performance degradation. Switching from the chart with the scrollbar to another chart and back again triggers the exception.

Can you offer any general guidance on the approach? Is there an event 'Dispose complete' I could wait for before triggering a create? Any help would be appreciated.

Cam

**Comment by Pauan** [comment] 2018-07-05 14:43
@cam-m To be clear, have you verified (using `console.log` or similar) that you're disposing of the chart **before** calling `am4core.create("chartdiv", am4charts.XYChart)`?

And, if you have multiple charts displayed at once, are you using different chart IDs for each one (e.g. `chartdiv1`, `chartdiv2`, etc.)?

**Comment by cam-m** [comment] 2018-07-05 21:56
I have verified via logs that im calling create and dispose in the right
order.

If these calls are not synchronous then i suppose dispose may not be
complete when create is called. I am also currently not using distinct
element ids for each chart instance, rather im relying on dispose to have
completly removed the previous chart. Ill rework my set up to ensure unique
ids for every chart... sounds like this might be my fix...

Ill update this issue with my findings...

Cheers,

Cam

**Comment by cam-m** [comment] 2018-07-06 01:18
I had a look at the pen from @martynasma and I've modified it slightly to replicate the issue.

https://codepen.io/cam-m/pen/LrvyPv

The only fundamental differences I can see are:

1. I'm using JSON config rather that programatically building the chart.
2. I've got stacked columns

**Comment by martynasma** [comment] 2018-07-06 05:46
Thanks @cam-m 

Now, this is something we can work with.

**Comment by martynasma** [comment] 2018-07-06 12:49
OK, so I think the issue is that you are reusing the same `config1` and `config2` objects to create charts.

Once chart is created from config, it will alter the original config object, supplemennting with missing items, and in some cases even creating instances of objects, like `XYChartScrollbar` in it.

Once you dispose such chart, all its children are disposed, including the scrollbar. However, it continues sitting in your `config1`. Once you supply that config to a new chart again, you get a chart with disposed scrollbar, hence the error.

We will think of how this can be worked around transparently so that original config object remains untouched. However, I'm not sure if and when that is going to happen.

It's much safer, and better, to work with standalone copies of the config objects. I have modified your codepen as per above:

https://codepen.io/team/amcharts/pen/cb8d4ddc2393d75c33f0f915b9b4fc0a/

Hope that makes sense and helps.

**Comment by martynasma** [comment] 2018-07-06 13:00
I'm gonna go ahead and close this. But feel free to reopen it if you feel there's more to this :)

**Closed by martynasma** 2018-07-06 13:00 UTC
