### ISSUE TITLE
durationFormat for export

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts4#751] opened 2018-12-29 20:33 UTC
Condensed options for the chart below.

```
chart = am4core.create("chart_chart", am4charts.XYChart);
chart.durationFormatter.durationFormat = "hh'h' mm'm' ss's'";
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
var valueAxis = chart.yAxes.push(new am4charts.DurationAxis());
valueAxis.baseUnit = "second";

var series = chart.series.push(new am4charts.ColumnSeries());
series.dataFields.valueY = "Active";
var series2 = chart.series.push(new am4charts.ColumnSeries());
series2.dataFields.valueY = "Idle";
var series3 = chart.series.push(new am4charts.ColumnSeries());
series3.dataFields.valueY = "Total";

//makes sure the exports have the correct date format
chart.exporting.dateFields.push("Timestamp");
chart.exporting.dateFormat = "MM/dd/yyyy";
```

Fiddle example at [https://jsfiddle.net/10bj3gnc/](https://jsfiddle.net/10bj3gnc/).

When I export to csv, json, etc it shows the actual total (in this case amount of seconds) for the Active, Idle, and Total columns.  What is the proper method to specify a durationFormat() for those columns when exporting same as the actual chart is set as?

**Comment by martynasma** [comment] 2018-12-30 10:51
There's currently no way to automatically format certain fields as duration when exporting.

I'm adding this as a possible enhancement to implement. Thanks for the suggestion.

**Comment by morrow95** [comment] 2018-12-30 15:40
@martynasma 
Yes, please add that as a suggestion.  I'd also like to make another suggestion... exporting should format to what the chart displays by default.  Only if you want to change the format of the exported data should you need to do so.  This is the second time where I've had a question about formats when exporting... it seems redundant and non-intuitive to specify the format for the chart and then again for the exporting.  Maybe I'm the only one, but I expect the export to show the same values the chart does.  Maybe there is a reason for this I'm not thinking of or due to the logic of the code though.

**Comment by martynasma** [comment] 2018-12-31 06:53
Unfortunately, that's not so easy as it may seem. A chart can display dates in a number of places using different formats. They may even change dynamically, e.g. when you zoom in, the scale and thus format may change on date axis. You may have different formats in tooltips than rest of the chart.

So yeah, if not specified directly in exporting settings, it will use `chart.dateFormatter.dateFormat`.

**Comment by martynasma** [comment] 2019-01-04 14:42
Fixed in [4.0.15](https://github.com/amcharts/amcharts4/releases/tag/4.0.15).

## [4.0.15] - 2019-01-04

### Added
- `color` property added to `LegendDataItem`. Can be used for coloring `label` or `valueLabel` text like `text = "[{color}] {name}"`.
- `minZoomCount` added to `Component`.
- Export now allows formatting numberic values as durations. Use newly added `durationFields` and `durationFormat` settings.

### Changed
- Export: When exporting date to XLSX, date fields will now export as true date fields in Excel (which in turn will format them according to regional settings), unless `useLocal` is set to `false`.

### Fixed
- Charts were not working properly in FireFox Extended Support Release.
- Some computer setups were not properly registering mouse movement.
- `legendSettings` was being ignored initially if legend was in external container.
- "Week year" (format code `"YYYY"`) was not being properly calculated.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-01-04 14:42 UTC
Labels: enhancement, in next release

**Comment by morrow95** [comment] 2019-01-04 14:47
@martynasma Nice - thank you.  Is it possible to get an example since this isn't in the docs yet?

**Comment by martynasma** [comment] 2019-01-04 14:49
Sure.

```
chart.exporting.durationFields.push("field3");

// Setting durationFormat is optional.
// If not set export will use chart.durationFormatter.durationFormat
chart.exporting.durationFormat = "mm:ss";
```

**Comment by martynasma** [comment] 2019-01-04 15:36
Yes, that is correct.

It's not an array, but rather `List` object. Its `push()` method does not accept multiple parameters.

For multiple elements use `pushAll()` instead:

```
chart.exporting.durationFields.pushAll(["field1", "field2", "field3"]);
```

**Comment by morrow95** [comment] 2019-01-04 15:38
Great - works perfect.  Thank you so much for all your help!

**Comment by morrow95** [comment] 2019-01-08 01:03
I spoke too soon.  The duration format for exporting isn't working when the chart's data is in json format.  I am using ajax to retrieve data from my database and returning it as json - `chart.data = response.data;`

The chart visually shows fine, the exporting works including the date formatting, but the duration formatting doesn't for exports (only tested CSV).  Same code, but not providing chart's data in json, but rather directly in js and the duration formatting works.

Bug or is there yet another option I need set?  From what I gather from the docs json is the default format, but only if using `chart.dataSource.url` which I am not using because I need to pass data to the my script.  Instead I just use ajax to hit my script, return the data as `response`, where `response.data` is the chart data, in json.

example : 

```
$.ajax({ 
    type: 'post',
    url: '/assets/process/create-chart-am4.php',
    data: {
    	'type': typeSelect.val(),
    	'id': idSelect.val(),
    	'user_id': userSelect.val(),
    	'start_date': $('#date-start').text(),
    	'end_date': $('#date-end').text()
    },
    dataType : 'json'
}).done(function (response) {
	
	if (response.data)
	{

		chart = am4core.create("chart_chart", am4charts.XYChart);
								
		chart.data = response.data;
		chart.fontSize = 12;
		chart.padding(10, 0, 0, 0);

		chart.cursor = new am4charts.XYCursor();
		chart.cursor.lineX.disabled = true;
		chart.cursor.lineY.disabled = true;
		
		chart.durationFormatter.durationFormat = "hh'h' mm'm' ss's'";
		chart.legend = new am4charts.Legend();
		
		var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
		dateAxis.dateFormats.setKey("day", "EEE, MMM dd");
		dateAxis.periodChangeDateFormats.setKey("day", "EEE, MMM dd");	
		dateAxis.tooltip.background.pointerLength = 0;
		dateAxis.tooltip.background.fill = am4core.color("#0E0F10");
		dateAxis.tooltip.background.strokeOpacity = 0;
		dateAxis.tooltip.fontSize = 12;
		dateAxis.renderer.grid.template.strokeDasharray = 6;
		dateAxis.renderer.grid.template.strokeWidth = 1;
		dateAxis.renderer.grid.template.location = 0;
		
		var valueAxis = chart.yAxes.push(new am4charts.DurationAxis());
		valueAxis.baseUnit = "second";
		valueAxis.min = 0;
		valueAxis.tooltip.background.fill = am4core.color("#0E0F10");
		valueAxis.tooltip.disabled = true;
		valueAxis.tooltip.fontSize = 12;
		valueAxis.renderer.grid.template.strokeDasharray = 6;
		valueAxis.renderer.grid.template.strokeWidth = 1;
		//valueAxis.strictMinMax = true;

		var series = chart.series.push(new am4charts.ColumnSeries());
		series.dataFields.dateX = "Timestamp";
		series.dataFields.valueY = "Total";
		series.fill = am4core.color("#347FC0");
		series.fillOpacity = 0.75;
		series.name = "Total";
		series.strokeWidth = 0;

		series.tooltip.background.fill = am4core.color("#fff");
		series.tooltip.background.fillOpacity = 1;
		series.tooltip.background.pointerLength = 0;
		series.tooltip.background.stroke = am4core.color("#BBB");
		series.tooltip.background.strokeWidth = 2;
		series.tooltip.dy = -10;
		series.tooltip.fontSize = 13;
		series.tooltip.getFillFromObject = false;
		series.tooltip.label.fill = am4core.color("#000");
		series.tooltip.pointerOrientation = "vertical";
		series.tooltipText = "Total : [bold]{Total.formatDuration()}[/]";
		//removes filters like shadow
		series.tooltip.filters.clear();
		series.tooltip.background.filters.clear();
		
		var topContainer = chart.chartContainer.createChild(am4core.Container);
		topContainer.layout = "absolute";
		topContainer.paddingBottom = 30;
		topContainer.paddingLeft = 10;
		topContainer.toBack();
		topContainer.width = am4core.percent(100);
		
		var title = topContainer.createChild(am4core.Label);
		title.align = "left";
		title.fontSize = 13;
		title.text = "test";						
		
		//makes sure the exports have the correct date format
		chart.exporting.dateFields.push("Timestamp");
		chart.exporting.dateFormat = "MM/dd/yyyy";
		
		//makes sure the exports have the correct formation format
		chart.exporting.durationFields.push("Total");
		//chart.exporting.durationFields.pushAll(["Active", "Idle", "Total"]);
		//chart.exporting.durationFormat = "hh'h' mm'm' ss's'"; // If not set export will use chart.durationFormatter.durationFormat

	}
});
```

and example to get my data : 

```
*db query stuff*

$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
	
if($results)
{		
	foreach($results as $row)
	{	
		$ajax_result['data'][] = array('Timestamp' => $row['date'], 'Total' => $row['total']);
	}
}
// return result
echo json_encode($ajax_result);
```

**Comment by martynasma** [comment] 2019-01-08 15:08
Wait, are you referring that you are trying to load data which has durations as formatted strings?

If that is so, it's a wholly different matter. `DataSource` does not support parsing of string-based durations in data.

**Comment by morrow95** [comment] 2019-01-08 15:30
@martynasma I'm not using `DataSource`.  In the example I gave above the durations are provided as an integer (amount of seconds).

**Comment by martynasma** [comment] 2019-01-08 15:40
OK, just checking. Because your code looks good to me, and should be exporting contents of the field "Total" as formatted durations, even as JSON.

If it isn't, it might mean that you are using some older version :)

**Comment by morrow95** [comment] 2019-01-08 15:51
The exported csv does show formatted durations, with the exact code above, when chart.data is not given json.  That is why I never noticed it earlier as I just passed some random data to it within my js script to test it.  Soon as I pass 'real' data coming from the ajax response the duration isn't formatted in csv.  Everything else still works fine though.

**Comment by martynasma** [comment] 2019-01-08 15:54
Gotcha. Unfortunately, I can't seem to be able to reproduce it in my tests.

Can you whip up a codepen with your actual data so that we can test?

**Comment by morrow95** [comment] 2019-01-08 16:03
@martynasma I would have already done that, but I don't believe you can do ajax on any of the sandbox sites.  If I provide the data directly in js it works fine.

**Comment by morrow95** [comment] 2019-01-08 16:15
I figured it out.  json encode was sending the integers as a string for some reason and while everything else worked... the durationformat for the exports wasn't due to that.  If I cast the integers values before sending out... json encode sends them properly and the duration is formatted in csv now.  I probably wouldn't have noticed that if you didn't mention your string comment.  Sorry for the confusion.

```
*db query stuff*

$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
	
if($results)
{		
	foreach($results as $row)
	{	
		$ajax_result['data'][] = array('Timestamp' => $row['date'], 'Total' => (int)$row['total']);
	}
}
// return result
echo json_encode($ajax_result);
```

**Comment by martynasma** [comment] 2019-01-08 16:15
Hm, could it be that jQuery AJAX loader converts numbers in your data to strings?

What happens when you `console.log()` the data loaded via AJAX?

**Comment by martynasma** [comment] 2019-01-08 16:16
There you go. Great minds think alike ;)
