### ISSUE TITLE
Extension of amchart markers in limited numbers

### ISSUE THREAD

**Issue by dvodvo** [amcharts/amcharts4#1364] opened 2019-06-08 20:41 UTC
Implementing custom markers - using [Leaflet.js](https://leafletjs.com/examples/quick-start/) but mainly its child library [MakiMarkers](https://github.com/jseppi/Leaflet.MakiMarkers) for the motives that this allows many variations on how markers can appear - leads to an odd behaviour.

If there are limited numbers of markers, they render.  A high number of markers and the whole map div is blank.  I have not yet found a tipping point (quantity 2 (even if markers almost overlap perfectly) works, while quantity 16 renders a blank div); but that is not material, as the behaviour ought to be consistent.

I have generated data the following way:
```
var marker_89 = imageSeriesTemplate.createChild(am4core.Image);
marker_89.href = "https://api.mapbox.com/v4/marker/pin-m-circle+bad533.png?access_token=pk.[long_string]";
marker_89.fill = am4core.color("#bad533");
marker_89.width = 30;
marker_89.height = 50;
marker_89.nonScaling = true;
marker_89.tooltipText = "uluru ";
marker_89.horizontalCenter = "middle";
marker_89.verticalCenter = "middle";
var marker_94 = imageSeriesTemplate.createChild(am4core.Image);
marker_94.href = "https://api.mapbox.com/v4/marker/pin-m-circle+bad533.png?access_token=pk.[long_string]";
marker_94.fill = am4core.color("#bad533");
marker_94.width = 30;
marker_94.height = 50;
marker_94.nonScaling = true;
marker_94.tooltipText = "Mitchell street darwin ";
marker_94.horizontalCenter = "middle";
marker_94.verticalCenter = "middle";
var marker_204 = imageSeriesTemplate.createChild(am4core.Image);
marker_204.href = "https://api.mapbox.com/v4/marker/pin-m-circle+bad533.png?access_token=pk.[long_string]";
marker_204.fill = am4core.color("#bad533");
marker_204.width = 30;
marker_204.height = 50;
marker_204.nonScaling = true;
marker_204.tooltipText = "Rocky!  Where Weird is... weird! in a certain season, one tree out of 5 is chocker-block full of parakeets (the other 4 are empty).  Drive in a 5 a.m. with a perforated muffler and wake up the whole town (after the parakeeets have been bothered).  Then one day, they all fly off...";
marker_204.horizontalCenter = "middle";
marker_204.verticalCenter = "middle";
var marker_205 = imageSeriesTemplate.createChild(am4core.Image);
marker_205.href = "https://api.mapbox.com/v4/marker/pin-m-circle+bad533.png?access_token=pk.[long_string]";
marker_205.fill = am4core.color("#bad533");
marker_205.width = 30;
marker_205.height = 50;
marker_205.nonScaling = true;
marker_205.tooltipText = " ";
marker_205.horizontalCenter = "middle";
marker_205.verticalCenter = "middle";
```
What could be leading to this failure?

**Comment by martynasma** [comment] 2019-06-11 12:10
No sure what to say. Every element takes up resources, so having awful lot of elements/markers has theoretical limits.

However those should not be small. Map should be able to function with relatively high number of markers. Certainly 16 markers could not bring it down.

If you could post your whole working setup, we'd be happy to take a look.

**Comment by dvodvo** [comment] 2019-06-12 13:34
I have prepared a file with various scenarios:

1. "relatively heavy" case that renders amCharts circles (16).
2. small scenario with 3 markers generated via href
3. "relatively heavy" case that should render markers generated via href  with circles code included
4. "relatively heavy" case that should render markers generated via href  with circles code excluded
(the latter two were different attempts)

the file is [available here](https://images-sportstourism-events.s3-us-west-2.amazonaws.com/amcharts_with_href_markers.txt).

**Comment by martynasma** [comment] 2019-06-12 14:23
I tried reproducing your ""relatively heavy" case that should render markers generated via href with circles code included" case on a live map:

https://codepen.io/team/amcharts/pen/7319a99e7ed3ff6160bb300a4438a76f?editors=0010

Shows up relatively fast for me.

BTW, description for one of the markers had a multi-line text, which breaks JavaScript. So maybe that was the cause of the issue for you?

```
marker_206.tooltipText = "just another test will my notes be kept in eternity?



and keep on writing to see how long this gets, where do we go and how do we get out of a ditch just in case...



oh bull bars are nice, sand pits not really...";
```

If you need those line breaks, you can insert `\n` symbols instead:

```
marker_206.tooltipText = "just another test will my notes be kept in eternity?\n\nand keep on writing to see how long this gets, where do we go and how do we get out of a ditch just in case...\n\noh bull bars are nice, sand pits not really...";
```

**Comment by dvodvo** [comment] 2019-06-13 08:19
Yes, it does work and the linebreaks have been properly escaped.  I stand corrected.

However, the associated text rendered for **all** points is that of the last point... 
I am not certain if there is confusion between the 'title' or 'tooltipText' and whether one should be dropped or not.

**Comment by martynasma** [comment] 2019-06-13 08:34
OK, now that I'm looking at this closer, the code is a bit weird.

It seems you are adding a lot of markers to a template as children. So those X markers are multiplied for each and every item in the series.

You just have to add one. Then use `tooltipText = "{title}"`.

I updated my demo here.

https://codepen.io/team/amcharts/pen/7319a99e7ed3ff6160bb300a4438a76f?editors=0010

**Comment by dvodvo** [comment] 2019-06-13 08:51
Ah! great to have an extension possibility for the markers and to have ironed that out!

**Comment by dvodvo** [comment] 2019-06-14 09:56
The children issue has another manifestation.

although there may be a different href for the child
```
marker_89.href = "https://api.mapbox.com/v4/marker/pin-m-attraction+bad533.png?
 marker_94.href = "https://api.mapbox.com/v4/marker/pin-m-circle+bad533.png?
```
The rendering is the same for all points and appears to be that of the last marker href provided. (circle)

**Comment by martynasma** [comment] 2019-06-15 05:18
Yes. If you add multiple images to the same marker template, you get multiple images in the results on every marker.

You need to add an image, then connect it to data via `propertyFields` like you correctly pointed out.

```
marker.propertyFields.href = "any_string";
```

This essentially means that whenever new marker (which is an instance of `Image`) is created, the map will look for "any_string" in related data and assign it to `href` property of the image.

**Closed** 2019-08-03 07:27 UTC
Labels: question
