### ISSUE TITLE
Generating server-based charts using wkhtmltopdf/wkhtmltoimage

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#3390] opened 2021-03-17 18:33 UTC
So I've been working on getting AmCharts 4 working with wkhtmltopdf & wkhtmltoimage. AmCharts does not work out-of-the-box, but it will work with a little finagling. I'm opening this ticket to document the solution (in hopes it helps others) but also in hopes that maybe the issues could be addressed with some transpiling changes.

The first issue, is that when the code gets transpiled from TS to JS there's a single instance of the `const` keyword in the `core.js` code and wkhtmltopdf v0.12.6 (lastest version stable) does not support either the `const` or `let` keywords. The offending line is:

```
const r=window.Promise,a=String.prototype.startsWith,o=String.prototype.endsWith;
```
Until you change the `const` to `var`, wkhtmltopdf will throw JavaScript errors when the page loads.

However, once you make this change, wkhtmltopdf will hang trying to load the resources. This one was oh so much fun to track down. The problem appears to be in Core-JS, which AmCharts uses in the code. The problem ends up being in the `array-method-uses-to-length.js` module of Core-JS. The issue is that this module passes JS `Object` as the context to calls to Array prototyped methods. There are two methods specifically that this causes issues with—Array.prototype.indexOf() and Array.prototype.splice(). Now I have no idea why they've chosen to use `{ length: -1 }` to represent an Array instead just using `[]`. If I update the code an use an empty array, everything appears to work. However, I wanted to avoid trying to hack the source code any more than I have to. The solution that works for me is to polyfill those two methods and override the native methods.

I've tested a number of different charts and this seems to be all working as expected. So to get AmCharts 4 working with wkhtmltopdf & wkhtmltoimage, there a few things you need to do:

1. Update `core.js` and replace the instance of `const` with `var`. This should not change the behavior of AmCharts at all.
2. Add the `wkhtmltopdf-shim.js` (see [wkhtmltopdf-shims.zip](https://github.com/amcharts/amcharts4/files/6158791/wkhtmltopdf-shims.zip)). This is a generic shim that adds polyfills (e.g. `Function.prototype.bind()`, `window.requestAnimationFrame()`, etc.) for which the version of Webkit in wkhtmltopdf lacks proper support.
3. Add the `wkhtmltopdf-corejs-shim.js` (see [wkhtmltopdf-shims.zip](https://github.com/amcharts/amcharts4/files/6158791/wkhtmltopdf-shims.zip)). This is a shim is designed to specifically target the issues with Core-JS and might need to be added to any page that uses Core-JS, like AmCharts.

I split the shims up, because the `wkhtmltopdf-corejs-shim.js` is not always going to be needed for my use cases, but you can certainly merge them together.

Is there any chance we could get AmCharts transpiled to convert the `const` keyword to `var`?

If this change was made, it would be very easy to use AmCharts with wkhtmltopdf/image. All a user would need to do is include the shim on pages where they wanted to render the charts.

*NOTE* — I suspect that these shims might fix some problems in other headless HTML CLI tools, like PhantomJS.

**Comment by dswitzer** [comment] 2021-03-17 18:34
I'm hoping to have time to play around with transpiling AmCharts myself later today to see if there's a way to get AmCharts working without any shims at all. However, I realize that it's possible no one is interested in a build of AmCharts that would work with older Webkit engines w/out having to use any shims.

**Comment by dswitzer** [comment] 2021-03-17 18:50
Also, I just stumbled across this:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4640

It appears that the Core-JS issue is fixed in v3.9+, so updating the version of Core-JS being sounds like it would remove the necessity of including the `wkhtmltopdf-corejs-shim.js` shim.

**Comment by dswitzer** [comment] 2021-03-23 11:04
I've confirmed that update Core-JS to v3.9.1 resolves a couple of the issues. The following contains a simple yarn project that will export AmCharts v4.10.16 using Core-JS v3.9.1. To use AmCharts with wkhtmltopdf/image you will still need to include wkhtmltopdf-shim.js I attached early (as this adds the polyfills for `Function.prototype.bind` and `window.requestAnimationFrame`). I could have added these as polyfills to the project, but I thought it better to keep these separate since the shims might be required for other pages being used in wkhtmltopdf/image.

To transpile your own version of AmCharts, download 
[amcharts_custom_build.zip](https://github.com/amcharts/amcharts4/files/6188983/amcharts_custom_build.zip).

Extract the folder and then run the following to download all the dependencies:

```
yarn install
```

Then run to build the project:

```
yarn run build
```

Alternatively, you can use either of the following:

```
// build the development branch
yarn run dev
// build the production branch
yarn run prod
```

**Comment by Pauan** [comment] 2021-04-03 18:41
@dswitzer Thanks for the very detailed report!

If you are using the npm version of amCharts then it is already using the latest version of core-js.

`const` and `let` are supported in all browsers (even IE11!), so it is quite unusual for wkhtmltopdf to not support them. However, you can use Babel to compile them into `var`. Our [Webpack tutorial](https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/) shows how to setup a working Webpack + Babel + amCharts project.

core-js should already be including polyfills for `Array.prototype.indexOf`, `Array.prototype.splice`, and `Function.prototype.bind`. Is that not the case?

amCharts already uses `setTimeout` as a fallback if `requestAnimationFrame` isn't supported, so are you sure that the problem is caused by `requestAnimationFrame`?

**Comment by dswitzer** [comment] 2021-04-04 13:07
@Pauan,

My previous comment has a zip which contains just what you said, a custom package which compiles things down. Unfortunately, unless you specifically add those polyfills as I detailed, they are not included by default. Or perhaps I'd need to tweak the browserlist more to target even an old version browser. However, since the problem is so specific to wkhtmltopdf/image, I didn't want to add the polyfill for all the modern browsers that do not need it. I decided it was better to just keep it separate and include it when I need it (especially since it was possible they'd be needed to address problems with other libraries).

**Comment by Pauan** [comment] 2021-04-04 19:50
@dswitzer If core-js is not including a polyfill, you can use the configurator to force it to enable that specific polyfill:

https://github.com/zloirock/core-js#configurable-level-of-aggressiveness

Alternatively, you can import the specific polyfills which you need:

```js
import "core-js/modules/es.array.index-of.js";
import "core-js/modules/es.array.splice.js";
import "core-js/modules/es.function.bind.js";
import "core-js/modules/es.string.starts-with.js";
import "core-js/modules/es.string.repeat.js";
import "core-js/modules/es.string.includes.js";
import "core-js/modules/es.object.assign.js";
```

**Comment by dswitzer** [comment] 2021-04-05 12:04
@Pauan 

Since the polyfills would be likely required by other pages, I decided it was better to separate the polyfills into a wkhtmltopdf/image file that I just include on any page where wkhtmltopdf/image is processing the page. I thought this better than inflating the file size for something that is generally not required.

**Comment by Pauan** [comment] 2021-04-06 12:00
@dswitzer Since the polyfills create global variables, you can simply take the above `import`s and compile them into a separate `.js` file (since Webpack can compile multiple different files at the same time), and then include that file where you need it:

```js
entry: {
    main: "./path/to/main.js",
    polyfills: "./path/to/polyfills.js"
}
```

But that's up to you, if your current setup is working then there's no need to change it.

Since it sounds like you got everything working, I'm going to close this. Thanks for the report.

**Closed by Pauan** 2021-04-06 12:00 UTC
Labels: question
