### ISSUE TITLE
Percentage formatter is not working

### ISSUE THREAD

**Issue by a30000329** [amcharts/amcharts4#2067] opened 2020-01-22 23:49 UTC
Reproduction link:
https://codepen.io/alexfan/pen/NWPeOdm

if using "%", the value axis does not show the percentage for either labels and tooltips

if using "#%", the incorrect percentage is shown in the black tooltip. the tooltip of second bar (10:01) is showing 30%, but it should show 32%

**Comment by xorspark** [comment] 2020-01-23 00:19
I'm pretty sure that you need the `#` next to the percent formatter.

As for the tooltip, the axis currently rounds tooltips to the step values used for the axis increment. You can work around this by adding an adapter `getTooltipText` to take the cursor position, map it to the exact value on the axis and then run the value through the formatter:

```
valueAxis.adapter.add("getTooltipText", function(text, target, key) {
  return target.numberFormatter.format(
    target.positionToValue(target.baseSprite.cursor.yPosition), 
    '#.%'
  );
});
```

[Updated codepen](https://codepen.io/team/amcharts/pen/e36a5a05b515c715b3524c8d1eeb4b53?editors=0010)

**Comment by a30000329** [comment] 2020-01-23 03:30
Thanks for the work around. Are you going to fix this issue in the later release so that we can remove this work-around code.

**Comment by martynasma** [comment] 2020-01-23 06:35
A `numberFormat` like this `"%"` does not make sense. Percent sign is a modifier, not a format itself. So in order to make sense, it needs to be preceded with actual number format options, e.g. `"#%"`.

Now, regarding 30% versus 40%. This is due to how `ValueAxis` works.

Actual scale for your axis is from 0 to 1, with granularity of one decimal point. So if you had non-percent numbers, you would get numbers in axis tooltip like 0.1, 0.2, 0.3. You would not get for example 0.32.

When reformatted into percent, this translates into 10%, 20%, 30%, and no 32%.

It's not a bug, it's by design, so I doubt we are going to change anything there. So it's @xorspark solution if you need better granularity.

**Comment by a30000329** [comment] 2020-01-24 00:56
Hi @martynasma thanks for your reply. I do agree that the format string should be "#%". My question is actually about @xorspark 's workaround. The reason I ask is that as a customer, it feels most naturally that when I specify "#%" and provide 0.32, the library should show 32% without any workaround. If you are the user of a library, would you be surprised that it shows 30% and you have to apply some workaround for all graphs in the solution where you are using percentage?

**Comment by martynasma** [comment] 2020-01-24 05:27
> I remember that in the documentation, "#" means taking the number as it is without any rounding. But if "#%" and 0.32 gives 30%. It is contradicting with the documented behavior :)

Well, it's not contradicting :) I tried to explain why above.

If you used the format `"#"` you would still get tooltip numbers like 0.2, 0.3, 0.4 etc., not 0.32.

Using percent sign is just reformatting the absolute number into percent. Format can't increase precision of the source number, if the axis reports 0.3 and then jumps straight to 0.4 (which is by design), formatter simply reformats those to 30% and to 40% respectively.

We are going to discuss if maybe we can introduce some kind of setting which allows bigger precision of numbers used for tooltips. Will let you know if/when that happens.

**Comment by martynasma** [comment] 2020-01-24 06:13
OK that was easy to add. New `ValueAxis` setting `extraTooltipPrecision` will be in the next version we release (today).

Will ping you here once more when it happens.

**Comment by martynasma** [comment] 2020-01-24 10:19
Fixed in [4.8.3](https://github.com/amcharts/amcharts4/releases/tag/4.8.3).

## [4.8.3] - 2020-01-24

### Added
- New `ValueAxis` setting: `extraTooltipPrecision`. Set it to a number of extra decimal places to use for numbers in axis tooltip on top of current axis label precision. Default is `0`.

### Fixed
- Syncing of `ValueAxis` grid improved.
- Using `timezoneOffset` was incorrectly affecting labels of `DateAxis`.
- If `MapChart` was initialized in a hidden container, subsequent `zoomToMapObject()` calls were zooming incorrectly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-01-24 10:19 UTC
Labels: enhancement, in next release

**Comment by a30000329** [comment] 2020-01-28 01:08
Thanks a lot for your help. It is all working now.

**Comment by a30000329** [comment] 2020-02-26 23:26
Hi, we are at the final stage of purchase decision making and would like to know the download size. For the example discussed here: https://codepen.io/alexfan/pen/BayvVgB
If we do the same thing in our current Angular 7 app, how much will it increase our application size in production build with tree shaking all that?

**Comment by a30000329** [comment] 2020-02-27 01:03
Also in the Angular instruction page, it mentions to use: [--build-optimizer=false](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/)

- What is the reason of that? 
- How to get around this as we want to turn on optimizer for prod build?
