### ISSUE TITLE
tooltipX as percent doesn't work

### ISSUE THREAD

**Issue by yenniSuresh** [amcharts/amcharts4#2897] opened 2020-09-11 11:07 UTC
When I assign `chart.cursor.lineY.tooltipX = 1400;` I get below output with tooltip aligned right
![X1400](https://user-images.githubusercontent.com/61043119/92917931-94d68500-f44c-11ea-8836-719809f8c05b.gif)

As I can't assign static number, when I assign `chart.cursor.lineY.tooltipX = am4core.percent(100);`, it doesnt align tooltip to right like above

**Comment by martynasma** [comment] 2020-09-11 11:26
Duplicate of #2889. Closing.

**Closed by martynasma** 2020-09-11 11:26 UTC

**Comment by yenniSuresh** [comment] 2020-09-11 11:31
@martynasma as per doc https://www.amcharts.com/docs/v4/reference/sprite/#tooltipX_property tooltipX also supports percent.
