### ISSUE TITLE
Issue in 4.9.20 Version.

### ISSUE THREAD

**Issue by sameerrswt** [amcharts/amcharts4#2469] opened 2020-05-13 07:04 UTC
Error is getting while building application in version 4.9.20 but in 4.9.19 is working fine.

Please check or suggest.

![4_9_20_amcharts](https://user-images.githubusercontent.com/17155131/81781482-cd556900-9515-11ea-97b6-422fed57d013.PNG)

**Comment by martynasma** [comment] 2020-05-13 07:18
Duplicate of #2462. Please follow that issue.

**Closed by martynasma** 2020-05-13 07:18 UTC
