### ISSUE TITLE
XY Chart legend is positioned wrong when using paddingTop

### ISSUE THREAD

**Issue by Ekliptor** [amcharts/amcharts4#533] opened 2018-11-06 08:07 UTC
Hi,
the legend of my XY charts gets displayed too far to the left when I use the `paddingTop` property.
Example screen: https://ibb.co/jU1tCq
Using `4.0.0-beta.72` from NPM.

```
        let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
        categoryAxis.dataFields.category = "day";
        categoryAxis.title.text = "Days";
       
        categoryAxis.renderer.minGridDistance = 1;
        categoryAxis.renderer.labels.template.rotation = 85;
        //categoryAxis.renderer.labels.template.paddingTop = 35; // removing this line places the legend properly
```

Sorry it's not a full code sample, but I hope that helps

**Comment by martynasma** [comment] 2018-11-06 08:36
Just to make sure I understand your situation: do you have `legend.position` set to `"left"` or `"bottom"`?

I tried both on a sample chart, and was not able to reproduce the effect you described, so I'm assuming it's something else.

If you could share your complete code, or better yet, a working example, that would be great.

Here's what I was experimenting with:
https://codepen.io/team/amcharts/pen/9da637e1fc353dc0fc811ac76ab672ae?editors=0010

**Comment by Ekliptor** [comment] 2018-11-06 09:08
On your Codepen example, when I uncomment this line:
`categoryAxis.renderer.labels.template.paddingTop = 35;`
I can see the x axis labels moving to the left a few cm. For an XY chart using a LineSeries with many data points (see my screenshot)this causes the x labels to be misaligned with the data, which becomes visible with `minGridDistance = 1`
I am using the legend without modification, just the defaults which is `bottom`
`chart.legend = new am4charts.Legend();`

**Comment by martynasma** [comment] 2018-11-06 10:48
OK, so just to make it clear - this has nothing to do with the legend, right? :)

As for labels, here's the deal: when you add a top padding to a label, it shifts the label down. Now, when you rotate the label to be almost vertical, as it is the case with your setup, the whole label, including all its paddings is rotated, so that your "top" padding becomes "right" padding.

To fix that, simple use `paddingLeft` instead.

Or, better yet, use `dy` setting, which will push the label down by X pixels, regardless of the rotation setting:

```
categoryAxis.renderer.labels.template.dy = 35;
```

Hope this helps.

**Comment by Ekliptor** [comment] 2018-11-07 10:44
yes that helps. Thx! sorry my for my wrong terminology - I meant x axis description, not labels.

**Comment by martynasma** [comment] 2018-11-07 12:39
No worries. Glad it helped.

I'm gonna go and close this, but please feel to post any follow ups about this here, or open a new issue.

**Closed by martynasma** 2018-11-07 12:39 UTC
Labels: question
