### ISSUE TITLE
Unequal Space on Top and Bottom Of Arial Text (And Possibly Others)

### ISSUE THREAD

**Issue by bfailing** [amcharts/amcharts4#1246] opened 2019-04-26 23:22 UTC
See [this pen](https://codepen.io/anon/pen/eoxyoP).  The range label (turquoise on the right side) has equal space on top and bottom.

Now compare [this pen](https://codepen.io/anon/pen/oOmpQK) using Arial text.  There is more space on the bottom of the text than the bottom.

Note that changing the CSS in the pen and allowing the chart to refresh automatically causes weird behavior with regard to this spacing.  You must refresh the page after saving (not always required though)

How can the space be made equal when using Arial as the chart font?

**Comment by martynasma** [comment] 2019-04-29 07:20
This is because different fonts have different proportions for their base line.

It would be awfully inefficient to try to detect perfect base line ratio for each label/font (it's possible but the process is super cumbersome), so we use a "golden middle" for everything.

Which, apparently is not so "golden", as it does not work perfectly for all fonts.

When there's a padding, the pixel there or there is not as prominent as in your extreme case example where you don't have padding for a label at all.

The only solution I can see now, is to make base line ratio configurable so you can adjust it as per your requirements and font usage. We'll add that to next version (`Label.baseLineRatio`).

**Comment by martynasma** [comment] 2019-05-02 12:35
Fixed in [4.4.2](https://github.com/amcharts/amcharts4/releases/tag/4.4.2).

## [4.4.2] - 2019-05-02

### Added
- New property for `Label`: `baseLineRatio` (default `-0.27`) controls how "base line" for a label is calculated, and affects positioning of text. The default might not work for all fonts, so this setting can be used to adjust it for precise positioning.
- New event for `Sprite`: `"dragged"`. It kicks in right after `"drag"` and can be used to manipulate or correct element's position, which might not be possible using `"drag"` which has built-in position-altering handlers.

### Fixed
- Export to SVG was not working on Firefox.
- Some touch issues wit iOS Safari fixed.
- `ValueAxis` could display non-rounded numbers (caused by floating point problem) sometimes.
- `maxPanOut` of `MapChart` was being ignored.
- Chart scrollbar was not being zoomed out when data of a chart changed.
- `RadarChart` with multiple `RadarColumnSeries` with Y as base axis was displaying columns of a 2nd+ series from wrong position.
- `chart.dispose()` with a lot of data was very slow. Now it's super fast.
- Zoom with mouse wheel was buggy when zooming already zoomed-in `XYChart`.
- Gant chart was not updating columns when `chart.invalidateRawData()` was called.
- Issue with some `propertyFields` set on a `LineSeries` with no data fixed.
- Reseting `relativeRotation` of `AxisLabelCircular` to `undefined` didn't work.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-05-02 12:35 UTC
Labels: enhancement, in next release
