### ISSUE TITLE
XYChart issues with tooltip snapping and data display 

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#661] opened 2018-12-11 04:18 UTC
This post is in reference to the XYChart from the ["Line Chart with Scroll and Zoom" demo](http://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/).

When zooming in, at times, the right side of the chart does not connect to the next data point, and the data point itself vanishes. In the screenshot below, there should be a data point where the line ends above Mar 24, and notice that it does not continue on to the right edge of the chart to connect the next data point.

[Imgur](https://i.imgur.com/iGSt1BO.png)

If it doesn't happen to you immediately, keep trying to zoom in on different parts of the chart.

Also, I feel like something is wrong with the tooltips in this demo. They are offset forward by one data point...?

Exact same screenshot as above, but with my cursor hovering over the chart. Notice the crosshair location, yet the invisible data point, which is not the closest to my cursor, gets the tooltip.

[Imgur](https://i.imgur.com/8Eaxfe7.png)

**Comment by martynasma** [comment] 2018-12-11 07:57
Several of us from the team has spent considerable time zooming and panning this chart.

We couldn't reproduce any of the two mentioned issues even a single time.

A few things to consider.

1) Maybe your browser has some older version cached (longshot). Try clearing your browser cache and see if you can still reproduce the issue.

2) Does this happen in different browsers for you? If not, which one produces the issue? (couldn't make it from screenshots)

3) If you can reproduce the issue, when it happens, can you let us know precisely the range of selection at the time?

**Comment by Achilles1515** [comment] 2018-12-11 12:12
Weird. I can't even get to the same plot anymore. I think you may be right with some type of cache issue. I can't even find the same plot I was looking at on your site anymore. Was it recently changed or something?

If I google "dateAxis.zoomToDates(chart.data[chart.data.length - 40].date", you can see the first result is to the chart I linked above...yet I can't find that text in the demo at all anymore.

[Imgur](https://i.imgur.com/JzWNmgj.png)

This issue was regarding the same demo from [my other issue](https://github.com/amcharts/amcharts4/issues/660) that included pre-zoom (you can see it in the CodePen). I did not write that code.

BUT, I can't reproduce this in that CodePen from the issue above, when changing the y-values back from forced zeroes to the "visits" random number

I guess you can close this for now. I am very confused.

**Comment by martynasma** [comment] 2018-12-11 14:14
Well, I suppose the demo was updated since Google last crawled it. No mystery there. Don't be confused :)

If this is not reproducible to neither of us anymore, I'm gonna go and close this.

But feel free to reopen if you manage to hit the issue again.

**Closed by martynasma** 2018-12-11 14:14 UTC
Labels: help wanted, question
