### ISSUE TITLE
Issue with options.queue as true

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3015] opened 2020-10-19 22:00 UTC
Hi, I'm not quite sure how to replicate this in a fiddle, as it seems intermittent depending on the chart type, the data provided, the configs, etc. However, I can describe exactly what the issue is and some of the symptoms. We need suggestions ASAP, as we released this update to production and now we have already have several of our customers reporting issues on the same day.

In our update, we enabled the `am4core.options.queue = true;` in this last push and we get odd behavior. We've seen all of these happening in various charts:
- zoom button appears (seems to happen most frequently on stacked charts)
- chart has opacity present on whole chart (happens most frequently on pie charts)
- some data isn't rendered (happens on just about every chart type)
- some data is rendered outside the chart area (happens most frequently on line charts)
- labels don't always appear, or appear incorrectly (happens on just about every chart type)

Here's a gif of a specific example. When loading the chart after a hard refresh, it seems to appear properly. If we dispose the component, render a different chart, then come back to the original chart, it without fail misses rendering data and shows a zoom button. If I click the chart (which we don't actually allow, but it rather opens another component), then close that component, the chart is rendered properly.
![](http://g.recordit.co/XqBBOplcYg.gif)

It seems like the queueing isn't quite finishing a render cycle until something causes a change (like a click or switching components in react). I attempted to try using `chart.invalidate()` and `chart.deepInvalidate()` after the ready event fired to see if that might help, but nothing seems to work.

HOWEVER, as soon as I set `am4core.options.queue = false;`, the issue goes away and all the charts render properly every time. The only problem here is that they take 30-50% longer to load when we turn this flag off, depending on the number of charts on the page.

As mentioned, this is affecting more and more of our customers, so need to nip it in the bud quickly, but I'm out of ideas on how to fix this without turning off the queuing.

For reference, here's a few screenshots from the customers as a direct result of this queue being "true".

(Line chart - notice the zoom and the 77 way above the legend)
![image](https://user-images.githubusercontent.com/3292053/96516016-93eefb00-1223-11eb-93da-92880aada7de.png)
![image](https://user-images.githubusercontent.com/3292053/96516037-a10bea00-1223-11eb-8718-4a4ddaf9e50c.png)
![image](https://user-images.githubusercontent.com/3292053/96516078-aff29c80-1223-11eb-890f-7274d56c40c1.png)
![image](https://user-images.githubusercontent.com/3292053/96516207-f5af6500-1223-11eb-9c08-972f5b1191ec.png)

**Comment by martynasma** [comment] 2020-10-21 13:06
We'll try to reproduce this, and will get back to you.

Can you at least provide a code/data for a couple of those charts so that we know what you're doing?

If you could also provide any further details that would be great as well. E.g. are you using animated theme? Does this happen in all browsers? Anything else you think might be important?

**Comment by runfaj** [comment] 2020-10-21 14:43
@martynasma I'll work on trying to get you an example that somewhat simulates the situation.

In the meantime, most of our users are using chrome. We don't animate the charts or anything else that might produce slower loading times - rather just init the chart with data and set the various configurations. There are a handful of adapters for things like formatting labels certain ways, but nothing overly complex - especially nothing that would affect so many different chart types. Hopefully I'll be able to reproduce in a fiddle, but if not, you'll at least get to see a somewhat similar example of what we're doing.

**Comment by martynasma** [comment] 2020-10-21 15:21
Gotcha. Thanks!

**Comment by runfaj** [comment] 2020-10-21 16:27
@martynasma I was able to reproduce here: https://codesandbox.io/s/sample-amcharts4-queuing-o7fv8?file=/src/chart/renderer.js
In the chart/renderer.js file, you can see the chart configuring, as well as the `queue` property near the top of the file. In order to replicate, you'll need to switch dashboards via the button on the preview. You'll notice that the zoom icon shows up pretty consistently in the second chart each time.

**Comment by martynasma** [comment] 2020-10-23 05:29
Thanks, this is very useful.

We are looking into it, but as you can imagine, it's tricky and might take a while.

In the interim, instead of `queue` I would suggest using "deferred" instantiation, which is much more reliable, since it does not create any chart objects at all, until ready.

https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation

**Comment by martynasma** [comment] 2020-10-23 07:24
We have made some changes, which should fix the issue(s).

I'll ping you here once the new version is out, so you can test out in your internal app.

Thanks for hanging in!

**Comment by martynasma** [comment] 2020-10-23 13:27
Just released new version (4.10.9).

Can you check if this solves issues on your end? (I'm closing this just in case, but feel free to reopen if you're still seeing issues)

**Closed by martynasma** 2020-10-23 13:27 UTC
Labels: bug, in next release

**Comment by runfaj** [comment] 2020-10-23 14:25
@martynasma Thanks! I'll give it a shot and report back if we see any issues. So far it is looking good in the sandbox!
