### ISSUE TITLE
forceDirectedTree not in native javascript

### ISSUE THREAD

**Issue by Identity-labs** [amcharts/amcharts4#1195] opened 2019-04-12 11:39 UTC
In forceDirected.js code we have an anonymous ES6 function

![image](https://user-images.githubusercontent.com/600296/56034691-56eda280-5d28-11e9-8362-fe1ab7c314ba.png)

It's break all phantomjs script

Thx

**Comment by Identity-labs** [comment] 2019-04-12 12:05
I think https://github.com/d3/d3-force#simulation is not in native javascript

**Comment by Identity-labs** [comment] 2019-04-12 12:07
Here : https://github.com/d3/d3-force/blob/master/src/link.js#L54

**Comment by Identity-labs** [comment] 2019-04-12 12:29
I have created a pull request : https://github.com/d3/d3-force/pull/137
Wait & See :)

**Comment by martynasma** [comment] 2019-04-12 13:31
I doubt d3 will go for it. But let's wait.

If they don't do it, I guess we'll need to add Babel to our standalone .js builds.

If you are using it in your TS app, you can install Babel yourself:
https://babeljs.io/setup#installation

**Comment by Identity-labs** [comment] 2019-04-12 13:51
They have respond :

> the decision to ship ES6 was intentional.

**Comment by martynasma** [comment] 2019-04-12 13:53
Babel it is then.

**Comment by Pauan** [comment] 2019-04-20 09:38
@Identity-labs I looked through our `.js` files and I don't see `=>` anywhere.

Are you using the npm version of amCharts and then bundling with Webpack?

**Comment by Identity-labs** [comment] 2019-04-20 10:15
I use directly github dist.
The arrow function is from d3-force.
When you use forceDirectedTree in phantomjs the script crash because of it.

**Comment by Pauan** [comment] 2019-04-20 10:23
@Identity-labs The GitHub isn't intended for using directly. We recommend using [our npm packages](https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/) instead.

Unfortunately, since the problem is with `d3-force`, we can't actually fix this. Instead, [you need to add Babel to your Webpack setup](https://babeljs.io/setup#installation) so it can transpile `d3-force`.

We'll write some more detailed docs on how to do this.

**Comment by Pauan** [comment] 2019-04-20 11:07
@Identity-labs Also, the ES6 arrow function is supported in every single browser except IE11.

PhantomJS is extremely old (the last release [was in 2016](https://github.com/ariya/phantomjs/releases)), and [it isn't supported anymore](https://github.com/ariya/phantomjs/issues/15344).

Instead, I recommend using [Selenium](https://www.seleniumhq.org/).

**Comment by Pauan** [comment] 2019-04-21 16:55
To be clear, because we support IE11, we do plan to fix this in some way or other (such as better docs). I'm just explaining some workarounds you can use in the meantime.

**Comment by jackwagons** [comment] 2019-04-28 23:23
It may be worth updating the [browser compatibility page](https://www.amcharts.com/docs/v4/browser-compatibility/) to indicate that for Force Directed Tree is not tested or support with IE.

**Comment by jackwagons** [comment] 2019-05-13 03:09
It's been a month since this was reported...  Any plans on addressing this from amcharts side?  My concern is that I'm not currently implementing a babel like solution and don't want to just for a new 
awesome chart that amcharts has teased me with and btw I absolutely love.  I understand that D3's decision is the problem here but I believe we're all living in a pivotal shift in support for legacy browsers.  We'd all like to say screw IE but the reality is most of us can't.  If it comes to the point of the haves and the haves not then sad face for a lot of us.

**Comment by martynasma** [comment] 2019-05-13 05:38
The solution is to use Babel for your webpack setups.

We've updated our Webpack tutorial correspondingly:
https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/

That should fix ForceDirected for IEs.

**Comment by Pauan** [comment] 2019-05-13 14:01
@jackwagons We've spent the past month experimenting with many different solutions, but unfortunately none of them worked. JavaScript tooling just wasn't designed to pre-compile npm dependencies like that.

The simple fact is that this is d3's fault. We're definitely not happy about d3's decision, but there isn't really anything we can do about it.

So if people want to support IE, they need to use Babel.

**Comment by jackwagons** [comment] 2019-05-13 15:11
@martynasma @Pauan Thanks, I'll  @take a look at your solution.

**Comment by jaspreetnabha** [comment] 2020-01-15 18:24
Hello @martynasma @Pauan, I am facing similar issue and being directed to AMCharts team by D3 team. I am using  AMCHarts version 4 and used ForceDirected tree which is not comptible with IE (per AMCharts browser support doc). Please advise possible ways to get it working in IE.  Please confirm if suggested steps at https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/ will make FOrce Directed tree compatible with IE 11. 

Thanks !

**Comment by jaspreetnabha** [comment] 2020-01-15 22:23
or how do i make sure AMCharts 4.0 downloads D3-Force version 1.2.1 as internal dependency ?

**Comment by Pauan** [comment] 2020-01-16 17:39
@jaspreetnabha Yes, our Webpack tutorial will make your code work in IE11. The secret is using `babel-loader` to compile it from ES6 to ES5.

**Comment by jaspreetnabha** [comment] 2020-01-16 18:37
@Pauan , Thank you. I'll try that. Angular CLI is being used in my project though.

**Comment by Pauan** [comment] 2020-01-23 10:25
@jaspreetnabha In that case you'll have to use something like `@angular-builders/custom-webpack` in order to use the `babel-loader`.

Here is an article explaining how to setup `@angular-builders/custom-webpack`:

https://alligator.io/angular/custom-webpack-config/

**Comment by jaspreetnabha** [comment] 2020-01-23 16:44
@Pauan , Thanks for sharing it. For now, I am using package-lock with the supported versions. The only caveat is to push the same config every time we build the code.

**Comment by martynasma** [comment] 2020-08-06 13:09
Since issue is with a 3rd-party library, which they admitted won't be fixed, and @Pauan has provided workarounds, closing this.

**Closed by martynasma** 2020-08-06 13:09 UTC
Labels: question
