### ISSUE TITLE
unitTest fails on @amcharts-4.7.10

### ISSUE THREAD

**Issue by dad-of-ma-gr** [amcharts/amcharts4#1911] opened 2019-11-22 11:09 UTC
Hi,

After I updated amcharts from 4.7.9 to 4.7.10 
in my angular application I get the following error when I execute:
ng test --code-coverage --watch false

Chrome 78.0.3904 (Windows 10.0.0) ERROR
  {
    "message": "Uncaught TypeError: Object prototype may only be an Object or null: undefined\nat http://localhost:9876/_karma_webpack_/vendor.js:375714:5\n\nTypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Module.__extends (http://localhost:9876/node_modules/tslib/tslib.es6.js?:25:1)\n    at http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:62:22\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:1345:2)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/System.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/System.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/Sprite.js?:1:1)",
    "str": "Uncaught TypeError: Object prototype may only be an Object or null: undefined\nat http://localhost:9876/_karma_webpack_/vendor.js:375714:5\n\nTypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Module.__extends (http://localhost:9876/node_modules/tslib/tslib.es6.js?:25:1)\n    at http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:62:22\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:1345:2)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/System.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/System.js?:1:1)\n
  at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/Sprite.js?:1:1)"
  }

Chrome 78.0.3904 (Windows 10.0.0) ERROR
  {
    "message": "Uncaught TypeError: Object prototype may only be an Object or null: undefined\nat http://localhost:9876/_karma_webpack_/vendor.js:375714:5\n\nTypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Module.__extends (http://localhost:9876/node_modules/tslib/tslib.es6.js?:25:1)\n    at http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:62:22\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:1345:2)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/System.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/System.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/Sprite.js?:1:1)",
    "str": "Uncaught TypeError: Object prototype may only be an Object or null: undefined\nat http://localhost:9876/_karma_webpack_/vendor.js:375714:5\n\nTypeError: Object prototype may only be an Object or null: undefined\n    at setPrototypeOf (<anonymous>)\n    at Module.__extends (http://localhost:9876/node_modules/tslib/tslib.es6.js?:25:1)\n    at http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:62:22\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js?:1345:2)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/System.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/System.js?:1:1)\n
  at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/utils/Animation.js?:1:1)\n    at __webpack_require__ (http://localhost:9876/webpack/bootstrap?:83:1)\n    at Module../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js (http://localhost:9876/node_modules/@amcharts/amcharts4/.internal/core/Sprite.js?:1:1)"

**Comment by Pauan** [comment] 2019-11-23 02:57
@dad-of-ma-gr I'm not able to reproduce this, could you please share your code?

**Comment by develar** [comment] 2019-11-23 08:42
Same for me — I reverted to 4.7.9. I decided to not dig further and simply revert. Maybe it is webpack chunking issue, but 4.7.9 works (webpack version the same).

**Comment by MateEke** [comment] 2019-11-26 14:42
Same issue for me.

Someone mentioned it on stackoverflow: [link](https://stackoverflow.com/questions/58978245/ionic-amcharts4-object-prototype-may-only-be-an-object-or-null-undefined)

**Comment by martynasma** [comment] 2019-11-26 15:26
Can you guys try `4.7.11` just released?

**Comment by develar** [comment] 2019-11-27 10:01
Thanks, it is fixed in 4.7.11.

**Closed** 2019-11-27 12:21 UTC
Labels: can't reproduce
