### ISSUE TITLE
Rotated label is not aligned correctly

### ISSUE THREAD

**Issue by develar** [amcharts/amcharts4#997] opened 2019-02-20 19:18 UTC
I like amcharts. I like that mostly anything can be done easily and without a lot of code. My company is not to going to use or buy amcharts because front-end developers selected d3. But I am not front-end developer and I just want to visualize measurement results. D3 requires a lot of boilerplate code and I don't find that it is good.

That's why I decided to use amcharts — it is good designed and has very good LaF by default.

But one things make me sad — in most cases amcharts doesn't work as expected and a lot of tweaks/experiments are required to get desired result. Despite fact that API looks promising.

![image](https://user-images.githubusercontent.com/350686/53115809-6716ac00-3547-11e9-9e48-525ce9a7d757.png)

Please see screenshot.

What I want: rotated label.
How it should be implemented: just set angle and amcharts will do the rest.
How it is actually implemented: you need to read several times docs about `verticalCenter` and `horizontalCenter` and `minGridDistance` and `grid.template.location`

Ok... let's say that this complexity justified because developer gets the full control over rendering.

But reality... reality is that it doesn't work as expected. On full zoom (when one bar is shown) it is probably aligned correctly. But on initial zoom (not zoomed at all) alignment is not constant and depends on... ouch, I don't know on what.

Yes — I fixed this issue using `location = 0.4`, but it is definitly hack and want to clearly understand why. Is it amcharts bug? Or browser SVG issue?

Sample project:
[label-position.zip](https://github.com/amcharts/amcharts4/files/2886139/label-position.zip)

```
yarn
yarn dev
```
open `http://localhost:1234/`

File `ComponentsChartManager.ts:24`

Thanks again for your incredible work.

**Comment by martynasma** [comment] 2019-02-21 05:52
Thanks for the suggestion!

It's a question of philosophy: how much of a fuzzy logic are we comfortable with, and how much of flexibility we leave to users?

With v4 we decided to take a leap of faith, and minimize on fuzzy logic as much as possible, giving the complete control to our users.

This particular label placement is a very sensitive place. With so many options available, it would be extremely hard to created set of rules that would not seem overly opionated. I suppose we're going to remain where we are right now.

**Comment by develar** [comment] 2019-02-21 09:58
Ok, with so great documentation and tutorials it is ok. Problem is that this control doesn't bring what is expected (or I do something wrong). Look at the screenshot that I attached in my report — do you see that label tail is not aligned correctly? What I want — position label in the middle of column.

Yes — on this zoom level I can set `nameAxis.renderer.labels.template.location = 0.4` and label will be aligned correctly. But on higher zoom level it will be clear that 0.5 is the only correct value here (it is default).

Zoomed screenshot (0.5, default):

<img width="620" alt="screenshot 2019-02-21 at 10 52 11" src="https://user-images.githubusercontent.com/350686/53159749-c7006780-35c6-11e9-8771-215180efde5b.png">

If I will set location to 0.4 to fix initial zoom level, label will be not aligned correctly on other zoom levels.

Zoomed screenshot (0.4, default):
![image](https://user-images.githubusercontent.com/350686/53159916-22caf080-35c7-11e9-9470-5fe038fefd6b.png)

(`yarn dev` run parcel in a hot swap mode, so, it is very easy to play with — just change value in editor and save).

That's my issue about — given control doesn't bring what I want.
And yes — on these new screenshots you can see another problem — for some reasons first cell width is truncated (but I didn't set strict min/max) — or it is another bug of amcharts, or I should find yet another magic property to fix that :(

**Comment by martynasma** [comment] 2019-02-21 11:05
You're right. Looks like positioning of rotated axis labels with `horizontalCenter = "middle"` is a bit off.

![image](https://user-images.githubusercontent.com/1458520/53164457-e3a59b00-35d8-11e9-9188-48d078b5a301.png)

Example:
https://codepen.io/team/amcharts/pen/3eaff59434989c65944e68964fa6cfe4?editors=0010

I'm gonna mark this issue as a bug for the dev team.

**Comment by martynasma** [comment] 2019-02-24 07:39
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.

**Comment by develar** [comment] 2019-02-24 07:47
@martynasma Thanks a lot! I enjoy using amcharts even if sometimes I need to spend quite a lot time to find related properties or solution for "obvious" (for me) features ;) like https://github.com/JetBrains/intellij-community/commit/c1b95e4cea2ffdabd370825f6cfb97c2e3b5be69#diff-3ce4750da2c99a78fdd9bbdb87896b89R67 (documented pitfall https://www.amcharts.com/docs/v4/concepts/series/#Note_about_Series_data_and_Category_axis)

**Comment by martynasma** [comment] 2019-02-24 12:10
Fixed in [4.1.10](https://github.com/amcharts/amcharts4/releases/tag/4.1.10).

## [4.1.10] - 2019-02-24

### Added
- New chart type: [WordCloud](https://www.amcharts.com/docs/v4/chart-types/wordcloud/).

### Changed
- Rotated axis labels (`rotation != 0`) of the vertical and horizontal axes no longer have their `verticalCenter` and `horizontalCenter` overridden by renderer. This gives more freedom for positioning rotated labels.

### Fixed
- `exportable = false` was not working when set on various Series item templates.
- On Gantt chart date axis tooltip was snapping randomly when moving mouse.
- Export: For very large data sets (2MB and up) data export was failing silently in Chrome.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-02-24 12:10 UTC
Labels: bug, in next release

**Comment by develar** [comment] 2019-02-25 08:58
Strange, but now situation is worse than before.

Now it is more aligned to right than left (on initial zoom).

![screenshot 2019-02-25 at 09 46 23](https://user-images.githubusercontent.com/350686/53324886-3e453c80-38e2-11e9-9151-d1a19ee30e8b.png)

Nothing is changed in my code — it is still:

```
nameAxisLabel.rotation = -45
nameAxisLabel.verticalCenter = "middle"
nameAxisLabel.horizontalCenter = "right"
```

I am sure that is not cache issues, because I don't use official URLs to download amcharts lib, but versioned URLs (`https://cdn.jsdelivr.net/gh/amcharts/amcharts4@4.1.11/dist/script/core.js`)

What have changed since `4.1.9` — now `nameAxisLabel.verticalCenter` is respected and I can see difference in various values — `bottom` vs `middle` vs `top`. But it seems that here there is another issue still not fixed — if `minGridDistance` is set to lower value (`1` in my case), labels are not aligned correctly. But as you can see — there is space to align it  correctly.

**Comment by martynasma** [comment] 2019-02-25 16:18
Looks like you may have `location` set at zero. Is that the case?

**Comment by develar** [comment] 2019-02-25 16:27
@martynasma If I will set location to `0` (default is `0.5`):

![screenshot 2019-02-25 at 17 25 46](https://user-images.githubusercontent.com/350686/53352087-78363300-3922-11e9-9e96-d71170cb08df.png)

And from docs I see that default location 0.5 means `middle`. My code — https://github.com/JetBrains/intellij-community/blob/master/platform/built-in-server/start-up-visualizer/src/ItemChartManager.ts#L37 (and project attached here as sample is still valid).

**Comment by martynasma** [comment] 2019-02-25 16:33
Can you whip up a CodePen for the chart? I'm afraid it's too much overhead reproducing a testable case out of the whole app code in your link :(

**Comment by develar** [comment] 2019-02-25 17:10
@martynasma Thanks for quick responses. 

 https://codepen.io/develar/pen/aMbOYK?editors=0011

This CodePen is based on your CodePen (https://github.com/amcharts/amcharts4/issues/997#issuecomment-465958377):
* I changed amcharts lib urls to use versioned, not official URLs.
* `categoryAxis.renderer.minGridDistance = 1;`
* `categoryAxis.renderer.labels.template.horizontalCenter = "right"` (to correctly align long labels)
* changed "Distribution" to "Long Long Name" to demonstrate why "right" horizontal align is used.
* instead of only 3 items, now there are 60 items.

**Comment by martynasma** [comment] 2019-02-26 16:10
I must be slow today. Still not getting what's wrong there.

You set:

```
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
```

Which means that center along which rotation happens is in the middle of the labels right edge:

![image](https://user-images.githubusercontent.com/1458520/53427432-974fc600-39f1-11e9-9517-b3a44416a62f.png)

It might seem off when you have those labels densely packed because of the padding, but the center is still in the center of the column.

Try disabling all padding around the labels:

```
categoryAxis.renderer.labels.template.padding(0, 0, 0, 0);
```

**Comment by develar** [comment] 2019-02-26 16:53
What I want — I got in 10 minutes using Plottly :( Please see https://codepen.io/develar/pen/RdNVRB

<img width="389" alt="screen shot 2019-02-26 at 17 44 29" src="https://user-images.githubusercontent.com/350686/53430117-31ae0a80-39ee-11e9-9eb5-791e54368cd7.png">

Using Plottly, I can just set `tickangle: -45` and that's all — labels will be correctly aligned. I am totally unaware about Plotly but I got desired result in 10 minutes. 
In case of Amcharts I read docs several times, but still cannot achieve my very simple task — align label in the middle.

> disabling all padding around the labels:

No, doesn't help.

Maybe combination of 10 magic properties will help me, but it requires reading of source code and digging, in this case I will better to try Plottly instead (untill not clear is Plottly suitable for me or not). That's why I reported it as a bug here, because for me it looks strange that no easy way to do this not unique task. Great that you have time to help not yet paying customer to sort out :)

**Comment by martynasma** [comment] 2019-02-26 17:06
At this point this is becoming a philosophical opinion sharing :)

We chose the path of greater flexibility versus preset opinionated fuzzy logic. Both approaches have pros and cons, and both have place under the sun.

If amCharts is not working out for you, and Plotly seems like a better choice, you should take it.

**Comment by develar** [comment] 2019-02-26 17:49
So, you confirmed that it is not possible to do using amcharts?
Interesting... Thanks. At least now I am sure that I didn't miss something
in docs and it makes sense to debug source code.
