### ISSUE TITLE
How do you add circles/balls to a Force Directed Chart after the render/initial load is complete?

### ISSUE THREAD

**Issue by Reginald-Tolman** [amcharts/amcharts4#2466] opened 2020-05-12 14:21 UTC
Is there a way to add new circles to existing circles after the initial load is complete? 
I would like to dynamically add circles without reloading the entire chart. 

amCharts V4
Browser: Chrome

![image](https://user-images.githubusercontent.com/62833798/81703133-c5a6ad80-949e-11ea-9f3c-d5f4d79007fb.png)

**Comment by martynasma** [comment] 2020-05-13 05:44
I'm afraid we do not support incremental data updates on chart types that use hierarchical data.

For now, the only way is to reload complete data set.

We might add this in the future, hence marking it as "enhancement".

**Comment by martynasma** [comment] 2020-08-06 13:13
Duplicate of #2152. Closing. Please subscribe to the first issue.

**Closed by martynasma** 2020-08-06 13:13 UTC
Labels: duplicate, enhancement
