### ISSUE TITLE
right legend maxcolumn is not working in amcharts and not able to export full legend

### ISSUE THREAD

**Issue by hshahul** [amcharts/amcharts4#3440] opened 2021-04-08 20:52 UTC
Hi Team,

Please let me know how can use maxcolumns : 2 is not working right aligned legend?

chart.legend = new am4charts.Legend();
chart.legend.position = "right";
chart.legend.maxColumns=2;

If use chart.legend.scrollable = true; , export image is not showing full legend values

https://codepen.io/team/amcharts/pen/eYmLvoR
please suggest

**Comment by martynasma** [comment] 2021-04-09 04:54
Duplicate of #3440

**Closed by martynasma** 2021-04-09 04:54 UTC
