### ISSUE TITLE
Weekly period seems to be broke (see example below)

### ISSUE THREAD

**Issue by dk8996** [amcharts/amcharts4#1065] opened 2019-03-12 22:58 UTC
Put together a simple example of 5 weeks starting on Monday of every week.  Seems like it breaks the chart, see example below.

[Codepen Example](https://codepen.io/anon/pen/vPWprw?&editable=true)

**Comment by martynasma** [comment] 2019-03-13 08:32
Confirmed. This is happening only when timezone is west of the GMT.

![image](https://user-images.githubusercontent.com/1458520/54264244-4f957680-457b-11e9-8d6d-b50059b3b33c.png)

**Comment by martynasma** [comment] 2019-03-13 11:57
This is fixed in dev and will be released soon.

That said, it's healthy to specify granularity of your data:

```
dateAxis.baseInterval = { timeUnit:"week", count:1 };
```

**Comment by martynasma** [comment] 2019-03-13 15:54
Fixed in [4.2.2](https://github.com/amcharts/amcharts4/releases/tag/4.2.2).

## [4.2.2] - 2019-03-13

### Added
- `cursorHoverEnabled` added to `XYSeries`. Controls whether to trigger hover state on columns/bullets of the all series under hovered category/date.
- A new `plugins` property on all `Sprite`. [More info](https://www.amcharts.com/docs/v4/concepts/plugins/).
- New plugin: Regression. [More info](https://www.amcharts.com/docs/v4/tutorials/regression-trend-lines/).
- New `ExportMenu` setting: `closeOnClick` (default `true`). Will force export menu to close when export is initiated.

### Changed
- `DateFormat` will now parse even partial dates, e.g. format `"yyyy-MM-dd"` will parse `"2018"` correctly, and will assume Jan 1st.

### Fixed
- Export: `getImage()`/`getSVG()` will now correctly omit `exportable = false` elements.
- Export: Data export was not taking in additional columns after data updates.
- Some chart cloning issues fixed.
- Inccorrect behavior of Series' tooltip with `minBulletDistance` set fixed.
- Sometimes, when series had only one data item, chart used to zoom-in right after the init.
- In-line date formatting will now use `DateFormatter`'s parsing functions for string-based dates.
- `DateAxis` issues with certain timezones fixed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-03-13 15:54 UTC
Labels: bug, in next release

**Comment by dk8996** [comment] 2019-03-13 16:06
@martynasma it seems like the labels are not correctly lined up.

**Comment by martynasma** [comment] 2019-03-13 17:01
Do you mean that they're off to the left?

It's by design to left-align the labels on axes where each cell does not represent single increment (baseInterval).

You can center aligned them tho:

```
dateAxis.renderer.labels.template.location = 0.5;
```

Or is it something else?

**Comment by dk8996** [comment] 2019-03-13 17:32
@martynasma that seems to have worked, although its inconsistent, since in the monthly and daily view it's centered.

**Comment by dk8996** [comment] 2019-03-13 17:53
@martynasma  here is the monthly example.
[Monthly Example](https://codepen.io/anon/pen/xBpPyE)

**Comment by martynasma** [comment] 2019-03-14 05:02
Please check this for an explanation of what's going on:
https://www.amcharts.com/docs/v4/concepts/axes/positioning-axis-elements/#_location_and_DateAxis
