### ISSUE TITLE
Huge memory usage when using this.data and events don't stop after chart.dispose() on Vue

### ISSUE THREAD

**Issue by peluprvi** [amcharts/amcharts4#106] opened 2018-06-27 12:40 UTC
The dispose issues (#17, #48, #65) has been fixed here on Vue when `this.chart.dispose()`,
but even after dispose it, the events still emitting (animation frame and all) like the chart is still there.

I have [this profiling tests](https://github.com/amcharts/amcharts4/issues/97#issuecomment-399499287) saved here. @martynasma say the team is aware about the memory leak difference when using `this` and you are working about it. Let me know if you wan't to check my profiling it and how I can send you it (~8MB zipped).

There are two points to fix, in my option:
- The memory grows up when assign the chart to `this.chart` comparing to not using it (+200MB of memory for 2 simple 12 columns chart)
- The chart events still running after dispose the chart

Possible solutions:
- A way to dispose a chart and its related events by its element or dom ID (like the `am4core.create` method). Something like `am4core.disposeChart(elementOrId)`.
- A way to get a chart object by its element and then dispose it (can be used to live update its data and other things too). Something like `am4core.getChart(elementOrId)`.
- A way to dispose and stop all charts events at once. Something like `am4core.disposeAllCharts()`.

In my case, with that possible solutions I would't need the chart in `this.chart` at the moment.

**Comment by jimmykane** [comment] 2018-06-27 15:44
That is my experience as well. I think I mentioned this at some ticket.

**Comment by martynasma** [comment] 2018-06-27 16:35
@peluprvi Thanks for the details!

This is super useful. We're looking into it. Will let you know if we need those test dumps.

**Comment by arm1n** [comment] 2018-07-02 21:53
Can confirm the high memory usage after using `dispose()`. Let me know if you need further profile dumps or anything else, whereas I suppose there's no major difference if it's Vue or Angular.

**Comment by peluprvi** [comment] 2018-07-03 14:06
I created a base that you can download and edit to test it https://codesandbox.io/s/828rxoq2lj

**Comment by peluprvi** [comment] 2018-07-24 15:31
Since I can't use `this.chart` with this memory issue, to dispose the chart in Vue I created this workaround: https://github.com/peluprvi/vue-amcharts4-teste/commit/23a09ef6b7dc14c499b75971e72da55c04cbf859

**Comment by Pauan** [comment] 2018-07-25 15:55
We've fixed a lot of disposer leaks, please try version `4.0.0-beta.36` and let me know if the memory leak is still there or not.

**Comment by Pauan** [comment] 2018-07-27 01:01
@peluprvi Thanks for looking into it!

Yeah, the `requestAnimationFrame` not being cleaned up is a known problem, but it's tricky to fix.

Since it sounds like the problem has been fixed (other than `requestAnimationFrame`), I'm going to go ahead and close this.

**Closed by Pauan** 2018-07-27 01:01 UTC
Labels: bug

**Comment by b49015** [comment] 2019-04-08 16:48
@Pauan  I don't think issue is fixed completely. In vuejs, assigning the chart to this.chart takes additional 150+ MB and as stated by @peluprvi  https://github.com/amcharts/amcharts4/issues/106#issuecomment-407833027 on this.chart.dispose() memory not freed completely.
I am using version 4.3.2 and still facing this issue. when you guys going to fix this issue? or can you please provide an alternate way to dispose the chart as mentioned in the ticket description, so that we don't need to store the chart to this.chart at all?

**Comment by b49015** [comment] 2019-04-08 16:50
@peluprvi Can you please share this workaround https://github.com/amcharts/amcharts4/issues/106#issuecomment-407449480 again? The link is broken.

**Comment by peluprvi** [comment] 2019-04-19 18:15
@b49015 Sure! Sorry! I set it to public again and update the link.

**Comment by b49015** [comment] 2019-04-28 07:27
Thanks @peluprvi

**Comment by adamturski** [comment] 2019-08-04 21:32
@peluprvi Hello I've found root cause of the issue of requestAnimationFrame events after disposing all charts on a page. Additionally I've added workaround for that issue.

https://github.com/amcharts/amcharts4/issues/1524

**Comment by parameciostudio** [comment] 2019-10-18 04:10
Hello @peluprvi!
I've tried your workaround and I confirm that a global variable solves my memory leaks.
Since Vue doesn't detect nested value changes inside Objects, I've tried to use a nested property and seems to work as well as your workaround.

```
data: function() {
    let data = {
      chart: {},
    }
    return data;
  },
mounted () {
this.chart.calories = am4core.create(this.id, am4charts.XYChart);
//...
}
```
