### ISSUE TITLE
Wrong focus of an area cut by map's ends

### ISSUE THREAD

**Issue by directcuteo** [amcharts/amcharts4#2725] opened 2020-07-22 09:21 UTC
Hi. I would like to focus some areas of the map chart. However, some of them are not in the middle, but crossing from left of the map to the right side. 

![image](https://user-images.githubusercontent.com/37619567/88158942-532c1980-cc15-11ea-90b9-3fd93ed4336e.png)

Now if I want to zoom the plane's route it won't focus in the wanted way.
I have also set `panBehavior = 'rotateLong';` and I expect the map should move itself so that the route is in the middle and then the zoom will work fine. Instead it behave strange, the map is moving half way: 

![image](https://user-images.githubusercontent.com/37619567/88159283-c2a20900-cc15-11ea-9200-c921778023d5.png)

Here is a CodePen demo: https://codepen.io/directcuteo/pen/QWyYvjX

I ask for some guidance about what I have to set, thank you very much!

**Comment by martynasma** [comment] 2020-07-23 06:56
I'm not sure I understand the issue. You don't like that the map does not extends all the way to the edge of its div?

**Comment by directcuteo** [comment] 2020-07-23 09:27
No.
So let's say I have a cruise in the Mediteranean Sea. I want to focus that area so I will use the `zoomToRectangle()` function.
These are the extreme points of the rectangle that will contain the cruise: 

north: 46.738285,
east: 31.438358,
south: 32.292806,
west: -8.319529

**Before zooming the map looks like this:**

![image](https://user-images.githubusercontent.com/37619567/88267437-82a45a00-ccd9-11ea-9c80-8b75e0196a89.png)

**After I use `chart.zoomToRectangle(north, east, south, west, 1, true, 1500);` the map will look like this:**

![image](https://user-images.githubusercontent.com/37619567/88267384-728c7a80-ccd9-11ea-899c-d392d14c89bd.png)

So far this is perfect.

Now having a flight from Los Angeles to Tokyo will be shown like this (**if we don't zoom**):

![image](https://user-images.githubusercontent.com/37619567/88268227-c8155700-ccda-11ea-9243-bf73f604610a.png)

Which is again fine, but since I don't have anything displayed on the map, I want to focus (using the function) the flight route itself, without being cut by the map. So the map should be somehow moved automatically so that the route is in the middle.
I have enabled paning using `chart.panBehavior = 'rotateLong';` but with no effect when using `zoomToRectangle()`.

The expected result after moving the map correctly using the function to have the entire route visible should be this:

![image](https://user-images.githubusercontent.com/37619567/88268706-8d5fee80-ccdb-11ea-91e4-aa7aeb00655b.png)

After this, zooming should work fine (like in the cruise case) and have the route focused:

![image](https://user-images.githubusercontent.com/37619567/88268785-a7013600-ccdb-11ea-9107-0809e25a6a5d.png)


But the map is not actually going where it should.
Here are the 4 cardinal points of the rectangle: north: 41.542617, east: 157.035889, south: 30.719324, west: -182.675048
If we create the rectangle we want to focus, the rectangle that contains the route itself based on the 4 extreme cardinal points, it would look like this:

![image](https://user-images.githubusercontent.com/37619567/88269632-0ca1f200-ccdd-11ea-9239-f5a114ec2c88.png)

The problem is that, when the map is in it's initial position, the rectangle is actually a lot bigger, and this is why the map doesn't focus at all, because the focusing area is actually the whole horizontal dimension of the map:

![image](https://user-images.githubusercontent.com/37619567/88270876-feed6c00-ccde-11ea-8fda-8f32b36b1595.png)

Having the Earth round, I expect the map should shift itself so that the area is not cut and the zoom will be completed correctly.

**Comment by martynasma** [comment] 2020-07-24 08:01
Awesome. Thanks for the explanation. I wish all users were as thorough :)

So basically it boils down to this: if extreme coordinates passed into `zoomToRectangle()` cross 180/-180 line, the map needs to rotate to accommodate it.

We will discuss whether this is something that we want to build into core.

In the interim, you might consider implementing this check yourself: if rectangle you are about to zoom to crosses 180th meridian, you apply [`deltaLongitude`](https://www.amcharts.com/docs/v4/chart-types/map/#Setting_map_center) to your `MapChart` so it brings map center to the center longitude of your rectangle.

Does that make sense?

**Comment by directcuteo** [comment] 2020-07-24 09:12
Indeed, I also had to check myself the antimeridian crossing cuz that is the only case when east longitude point is actually less than the west longitude point.
Didn't know about `deltaLongitude`.
It still behaves strange...`deltaLongitude` works fine, but when I run the `zoomToRectangle()` function it focuses a wrong area, and the map's width is cut in half. 
I've updated the CodePen, you can see that here (click the plane): https://codepen.io/directcuteo/pen/QWyYvjX

**Comment by martynasma** [comment] 2020-07-24 10:20
Mhm. Looks like maybe `zoomToRectangle()` is not compatible with `deltaLongitude`.

Will let you know when we have this figured out.

**Comment by martynasma** [comment] 2020-07-31 08:31
Fixed in [4.9.34](https://github.com/amcharts/amcharts4/releases/tag/4.9.34).

## [4.9.34] - 2020-07-31

### Added
- New bullet `ShapeBullet` in `Bullets` plugin. Please refer to [this documentation article](https://www.amcharts.com/docs/v4/tutorials/plugin-bullets/) for more info.
- `treatZeroAs` added to `ValueAxis`. Use it to work around zero-value restriction on a logarithmic scale.
- `stackToNegative` (default: `true`) added to `XYSeries`. Determines whether negative values in a stack will stack in relation to base (zero) line (`true`; default) or in relation to the previous value in the stack (`false`).

### Changed
- [xlsx](https://www.npmjs.com/package/xlsx) dependency was updated from `0.15.4` to `0.16.4`.
- Tooltip snapping on `DateAxis` now takes Series' location into account.

### Fixed
- Regression plugin: `reorder` option was not working properly.
- `snapToSeries` was not working properly if there was a hidden Series with exactly the same value as the other visible Series.
- `TreeMap` and `ForceDirectedTree` with a single data item and no children were not working properly with chart legend.
- Horizontal (X) Axis tooltip in a very small document was sometimes positioned with an offset.
- `zoomToRectangle()` method of `MapChart` with `deltaLongitude` was not working properly if a rectangle crossed the 180 meridian.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2020-07-31 08:31 UTC
Labels: bug, in next release
