### ISSUE TITLE
Maximum call stack size exceeded when using skipEmptyPeriods with baseInterval milliseconds

### ISSUE THREAD

**Issue by JKannekens** [amcharts/amcharts4#467] opened 2018-10-18 14:48 UTC
Hello,
I have an issue when using the skipEmptyPeriods property on the dateAxis. On my graph when the duration of the dataitems is between 1 and ~4 milliseconds, the property works great. But when a dataitem has a duration of 10 or more milliseconds I get a maximum call stack size exceeded error.

``RangeError: Maximum call stack size exceeded
    at Number (<anonymous>)
    at isNaN (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/core/utils/Type.js:52)
    at Object.isNumber (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/core/utils/Type.js:397)
    at Object.round (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/core/utils/Time.js:195)
    at DateAxis.getBreaklessDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:639)
    at DateAxis.getGridDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:614)
    at DateAxis.getGridDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:623)
    at DateAxis.getGridDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:623)
    at DateAxis.getGridDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:623)
    at DateAxis.getGridDate (webpack-internal:///../node_modules/@amcharts/amcharts4/.internal/charts/axes/DateAxis.js:623)``

**Comment by martynasma** [comment] 2018-10-18 17:48
Hm, I can't seem to be able to reproduce this.

Would you be able to post your chart code and actual data that generates the error?

**Comment by JKannekens** [comment] 2018-10-19 08:04
I commented out the parts for parsing the JSON because in my application I upload a file. But for demo purposes, I added the parsed JSON to the assets folder.
https://stackblitz.com/edit/angular-dabs6b

**Comment by martynasma** [comment] 2018-10-19 10:11
Thanks for the code.

It seems that the algo that looks for time units to remove takes too long. Since you are operating with milliseconds, there are simply too many time units to remove, hence the error.

If I set date axis' `baseInterval` to second, that seems to fix the issue.

```
dateAxis.baseInterval = {
  timeUnit: "second",
  count: 1
}
```

Although, I'm not sure if that won't skew the data for you.

Another option is to use `CategoryAxis` instead of `DateAxis` if the actual scale is not that important, since you are using `skipEmptyPeriods`.

**Comment by JKannekens** [comment] 2018-10-19 11:10
If is set it to seconds it only shows 2 dataitem points. I'm going to try to get categoryaxis to work.

**Comment by martynasma** [comment] 2018-10-19 12:13
Gotcha. Let me know if you figure out category axis.

I'm going to keep this open for now, even though I'm not sure how this can be resolved at this moment.

`skipEmptyPeriods` was meant for less granular data, such as skipping weekends on a day chart, etc.

It's not optimized for such large amount of "empty periods" :(

**Comment by JKannekens** [comment] 2018-11-14 09:34
After trying out some things I came to the conclusion that it was better to just not use skip empty periods. This gives a much better overview of the data.

**Comment by martynasma** [comment] 2018-11-14 13:35
@JKannekens Ha, problem solved ;)

That said, we found other problems with `skipEmptyPeriods` recently.

When we release the next version, and you're feeling like revising `skipEmptyPeriods` try it again.

I'm gonna close this, but feel free to reopen if you wish.

**Closed by martynasma** 2018-11-14 13:35 UTC
Labels: question

**Comment by Rapster** [comment] 2019-04-24 12:29
I reproduced this problem, see here: https://codepen.io/rapster/pen/LvgXWM?editors=1111

Thanks for having a look
