### ISSUE TITLE
Export to PNG demo broken: core.js:1 Uncaught (in promise) TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#1074] opened 2019-03-14 12:52 UTC
The Export to PNG export demo from our tutorial [Exporting Charts](https://www.amcharts.com/docs/v4/concepts/exporting/) seems to be broken.

When clicking the button that executes following code ...

```
chart.exporting.export("png");
```

... no PNG export is showing up. Instead, the browser console displays the error:

**core.js:1 Uncaught (in promise) TypeError: Cannot read property 'close' of undefined
    at e.<anonymous> (core.js:1)
    at core.js:1
    at Object.next (core.js:1)
    at a (core.js:1)**

Link to Codepen: https://codepen.io/team/amcharts/pen/ergXmr

---

Apparently it was working yesterday. I have cleared the cache, but the error remains.

**Comment by martynasma** [comment] 2019-03-14 15:27
Bug confirmed, and fixed in dev.

**Comment by martynasma** [comment] 2019-03-14 18:04
Fixed in [4.2.3](https://github.com/amcharts/amcharts4/releases/tag/4.2.3).

## [4.2.3] - 2019-03-14

### Fixed
- Exporting via API from a chart that did not have `ExportMenu` set, was resulting in error.
- Fixed tooltip flickering that were set directly on series objects (columns/bullets).
- Because of daylight saving, sometimes `DateAxis` could mistake yearly data for monthly data if `baseInterval` was not set explicitly.
- Sometimes Sankey nodes did not perfectly fit into chart area.
- Tick `location` on Y axis was being ignored.
- Ticks were positioned incorrectly when multiple axes were on the same side of the `XYChart`.
- Issue with `strictMinMax` and single data item fixed.
- `valueY` (or any other value) wasn't working in `legendSettings.itemLabelText`.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-03-14 18:04 UTC
Labels: bug, in next release
