### ISSUE TITLE
Fills drop over legend on Safari and tooltip has no styles

### ISSUE THREAD

**Issue by jimmykane** [amcharts/amcharts4#841] opened 2019-01-17 13:12 UTC
Hi please look at this

![screenshot 2019-01-17 at 14 11 02](https://user-images.githubusercontent.com/1268723/51320974-d5a4ad80-1a61-11e9-8c50-53b5b6c80d6f.png)

The above works fine in all browsers and I cannot figure out why on safari it breaks. 

I cannot create a codepen with the issue not matter how many hours I spent. 

I would appreciate any tip that could guide me to the correct place to look at

**Comment by jimmykane** [comment] 2019-01-17 13:35
One thing I found out already is that this happens when multiple axis are added.

**Comment by jimmykane** [comment] 2019-01-17 15:40
![screenshot 2019-01-17 at 16 39 39](https://user-images.githubusercontent.com/1268723/51329784-83ba5280-1a76-11e9-91ed-01f378f6e4e9.png)
AS you can see there is something quite wrong on safari.

**Comment by martynasma** [comment] 2019-01-17 17:52
Can you doublecheck if you are running 4.0.21 (the latest version)?

If you do, can you post your chart as a codepen so that we can test?

**Comment by jimmykane** [comment] 2019-01-18 09:23
@martynasma  yes running the latest version. Any tips too look for example why the tooltip styling is broken? I could not reproduct this to a codepen. I will give more try. 

But whatever I do the tooltip still stays with no styles and to be honest I hate safari

**Comment by jimmykane** [comment] 2019-01-18 09:50
What I also notice is that the Am4Charts "logo" is missing. 

Any clue what can be causing this? 

![screenshot 2019-01-18 at 10 49 47](https://user-images.githubusercontent.com/1268723/51379067-dba49800-1b0e-11e9-9e12-4c7b2478dcb1.png)

**Comment by jimmykane** [comment] 2019-01-18 15:06
Ok getting closer. 

Looks like the following: 

If I have a series with non 0 values to display on the axis this happens: 

![screenshot 2019-01-18 at 16 04 38](https://user-images.githubusercontent.com/1268723/51394541-eaa13f80-1b3a-11e9-98ed-2e005eed31c3.png)


But if I have a series with 0 values as well: 

![screenshot 2019-01-18 at 16 04 48](https://user-images.githubusercontent.com/1268723/51394568-f68d0180-1b3a-11e9-804f-428fe85ec7db.png)



So it looks like the yAxis for series that dont have 0 values is pushed to the bottom but is also infront of the chart (some z-index?)

**Comment by jimmykane** [comment] 2019-01-20 10:57
More on this. 
This happens to All iOS devices and browsers. I cannot pinpoint the issue but looks like it's related to iOS webkit etc.

**Comment by jimmykane** [comment] 2019-01-20 17:54
There is 100% something wrong with Angular + am4charts

I did a new app injected the getStarted Example 

Here is what I get 
![screenshot 2019-01-20 at 18 53 40](https://user-images.githubusercontent.com/1268723/51443156-d13bf700-1ce4-11e9-9703-fe14003a4fc0.png)

Same graphic issues for Safari + all ios browsers

**Comment by jimmykane** [comment] 2019-01-20 18:04
As per comment https://github.com/amcharts/amcharts4/issues/802 

@martynasma  I think those styles issues are important. Atm Am4 Charts fail in IOS (all browsers) + Safari (Latest + latest OSX).

**Comment by martynasma** [comment] 2019-01-21 18:18
Can you please produce a CodePen for us to test? Just so we are testing same setup, as I can't seem to be able to reproduce this.

**Comment by jimmykane** [comment] 2019-01-21 19:12
@martynasma 

example and bug one

https://stackblitz.com/edit/gantt-chart-tooltip-bug-hd5edu

does not include the amcharts logo

**Comment by jimmykane** [comment] 2019-01-21 19:19
@martynasma  here is how it looks :

https://stackblitz.com/edit/gantt-chart-tooltip-bug-xpjxil
This is how it runs natively on AG7 (ios all browsers, osx safari, and some old ff)
![screenshot 2019-01-21 at 20 18 10](https://user-images.githubusercontent.com/1268723/51494657-b1c2ce00-1db9-11e9-898f-073f38cd16a3.png)



The above is a combination of AG7 and your tutorial https://codepen.io/team/amcharts/pen/wmLZYM

**Comment by jimmykane** [comment] 2019-01-23 07:45
Hi @martynasma did you have time to check the issue with the above links? 

I would feel great if it's ack that its an issue with Angular 7, and I am not worying about the time it will take to get fixed.

**Comment by jimmykane** [comment] 2019-01-25 07:36
Atm this my only issue that blocks us to go to production

**Comment by jimmykane** [comment] 2019-02-07 21:23
hey @martynasma I dont mind if this takes long, no need to apologize you are going great guys, but I would like to know like a tiny bit if it's going to be more than 1 week from now so I might consider going live with this glitch, to boost some traffic. (Its an opensource GPX/FIT/SML/TCX/JSON file comparison tool only JS and runs on firebase powered at charts by amCharts ;-)

**Comment by jimmykane** [comment] 2019-02-07 21:24
ah it also now supports the Spartan JSON etc files that hold some more info on them ;-)

**Comment by martynasma** [comment] 2019-02-08 09:32
Hey, I'm sorry this is taking longer then expected. We still haven't quite figure out it yet because of added complexity of manifesting only with certain configuration of Angular and only in Safari.

It's not forgotten or shelved. It's on the back of our minds, trust me :)

**Comment by martynasma** [comment] 2019-02-11 14:03
Folks, just released 4.1.5 which should fix the issues with Angular and Safari/FF45.

At least it's so in our tests.

I'm gonna go ahead and close this, but feel free to reopen if you're still seeing issues after upgrading.

**Closed by martynasma** 2019-02-11 14:03 UTC
Labels: bug, question

**Comment by jimmykane** [comment] 2019-02-11 14:04
Already tested and fixed thanks boss @martynasma
