### ISSUE TITLE
Create your own custom Number Format?

### ISSUE THREAD

**Issue by DTwigs** [amcharts/amcharts4#2456] opened 2020-05-08 18:17 UTC
I want to create a custom number format like the ones found here:
https://www.amcharts.com/docs/v4/concepts/formatters/formatting-numbers/

I want to multiply the value by 10000 and add a string at the end, so the number "4" would become "40000foo" and would perhaps be represented by something like "#####foo".  Is this possible with the number formatter?

**Comment by martynasma** [comment] 2020-05-09 10:58
Seems like duplicate of #2457

**Closed by martynasma** 2020-05-09 10:58 UTC
