### ISSUE TITLE
Responsive state properties doesn't work

### ISSUE THREAD

**Issue by cipsicko** [amcharts/amcharts4#1850] opened 2019-11-06 11:09 UTC
I'm working on charts responsivities using [this](https://www.amcharts.com/docs/v4/concepts/responsive/) tutorial.

But `state.properties.paddingTop` don't work, so i go in deep trying some other property of `state` and using `sprite` it's working fine

here's my code
[edit] https://codepen.io/cipsicko/pen/pooVWLW
![Screenshot 2019-11-06 at 12 04 37](https://user-images.githubusercontent.com/3090092/68293252-df011400-008d-11ea-8133-0a640c71c83f.png)

I also see that `chart.responsive.useDefault` value is overwritten by rules?

There is something that i do bad? because i don't understand how to do responsive stuff well.

thanks

**Comment by xorspark** [comment] 2019-11-07 01:41
`properties` is working correctly as you can see [here](https://codepen.io/team/amcharts/pen/94eaec42ca0653d6ffa2172161e61e2c?editors=1010); the chart correctly applies the 60px padding to all sides when the chart width  exceeds 768px. I'm not seeing anything obviously wrong from your setup. Could you provide a fiddle or codepen that reproduces your problem?

**Comment by cipsicko** [comment] 2019-11-07 09:57
Hi, here the example of my code.

https://codepen.io/cipsicko/pen/pooVWLW

**Comment by martynasma** [comment] 2019-11-08 05:52
Looks like a bug. Investigating.

**Comment by martynasma** [comment] 2019-11-14 14:34
Fixed in [4.7.9](https://github.com/amcharts/amcharts4/releases/tag/4.7.9).

## [4.7.9] - 2019-11-14

### Added
- New `Sprite` property: `showTooltipOn`. Available options: `"hover"` (default), `"hit"`, and `"always"`.
- `ignoreZeroValues` added to `PercentSeries` (default: `false`). If set to `true` it will not show slices with zero values.

### Changed
- `Sprite` property `alwaysShowTooltip` is now being deprecated in favor of `showTooltipOn = "always"`.
- In `WordCloud` words connected with a dash without spaces will not be treated as a single word, e.g. "76-ers" is now a single word rather than two separate words "76" and "ers".
- JSON config based charts will now fail with a critical error if there's incorrect `type` specified for one of the objects.

### Fixed
- Initial chart responsive rules were sometimes not being applied.
- When `MapChart` was zoomed/panned, "always-on" tooltip were remaining in the same place.
- HTML labels with `maxWidth` and `wrap` set were not being sized correctly.
- Sides of `Column3D` were not being colored properly when `fill` was being set via `propertyFields` and string-based hex color codes were used in data.
- After click on chart with `XYCursor` that `behavior = "select*"` its `xRange` and `yRange` was not being reset and could show ranges from previous selection.
- `XYCursor` will now respect order of series when showing their tooltips if they share the same value.
- Tooltip position of rotated and/or scaled sprites was incorrect.
- Changing series of `XYChartScrollbar` was not working properly (old series could remain or new series were not appearing).
- `PictorialSeries`, and `PyramidSeries` were not working properly with slices with `<= 0` values.
- When removing data from a chart using `addData(data, removeCount)`, chart was rmeoving data items from series which had data set explicitly.
- Bullets on a `RadarChart` could be displayed in wrong positions when zooming/hiding series.
- When minimizing series they could animate to incorrect minimum values and adjust min/max values.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Closed by martynasma** 2019-11-14 14:34 UTC
Labels: bug, in next release
