### ISSUE TITLE
addData and removeData for Force Direct Tree chart

### ISSUE THREAD

**Issue by shichenglu** [amcharts/amcharts4#2474] opened 2020-05-14 20:55 UTC
I tried to use addData for Force Directed Tree chart, however I found there is no function to remove those added data easily, removeData function only works to remove very first N data, is there a way to remove very last N data for Force Directed Tree chart?

**Comment by martynasma** [comment] 2020-05-15 07:13
Duplicate of #2152. Please subscribe to that issue for any updates.

**Closed by martynasma** 2020-05-15 07:13 UTC
